// Code generated by ent, DO NOT EDIT.

package modelcall

import (
	"time"

	"entgo.io/ent/dialect/sql"
)

const (
	// Label holds the string label denoting the modelcall type in the database.
	Label = "model_call"
	// FieldID holds the string denoting the id field in the database.
	FieldID = "call_id"
	// FieldGenerationTaskID holds the string denoting the generation_task_id field in the database.
	FieldGenerationTaskID = "generation_task_id"
	// FieldCallerService holds the string denoting the caller_service field in the database.
	FieldCallerService = "caller_service"
	// FieldBusinessScene holds the string denoting the business_scene field in the database.
	FieldBusinessScene = "business_scene"
	// FieldOperation holds the string denoting the operation field in the database.
	FieldOperation = "operation"
	// FieldCapability holds the string denoting the capability field in the database.
	FieldCapability = "capability"
	// FieldModel holds the string denoting the model field in the database.
	FieldModel = "model"
	// FieldProvider holds the string denoting the provider field in the database.
	FieldProvider = "provider"
	// FieldStatus holds the string denoting the status field in the database.
	FieldStatus = "status"
	// FieldDeliveryStatus holds the string denoting the delivery_status field in the database.
	FieldDeliveryStatus = "delivery_status"
	// FieldErrorCategory holds the string denoting the error_category field in the database.
	FieldErrorCategory = "error_category"
	// FieldErrorCode holds the string denoting the error_code field in the database.
	FieldErrorCode = "error_code"
	// FieldErrorReason holds the string denoting the error_reason field in the database.
	FieldErrorReason = "error_reason"
	// FieldErrorMessage holds the string denoting the error_message field in the database.
	FieldErrorMessage = "error_message"
	// FieldInputTokens holds the string denoting the input_tokens field in the database.
	FieldInputTokens = "input_tokens"
	// FieldOutputTokens holds the string denoting the output_tokens field in the database.
	FieldOutputTokens = "output_tokens"
	// FieldTotalTokens holds the string denoting the total_tokens field in the database.
	FieldTotalTokens = "total_tokens"
	// FieldCachedTokens holds the string denoting the cached_tokens field in the database.
	FieldCachedTokens = "cached_tokens"
	// FieldReasoningTokens holds the string denoting the reasoning_tokens field in the database.
	FieldReasoningTokens = "reasoning_tokens"
	// FieldImageCount holds the string denoting the image_count field in the database.
	FieldImageCount = "image_count"
	// FieldImageSize holds the string denoting the image_size field in the database.
	FieldImageSize = "image_size"
	// FieldImageAspectRatio holds the string denoting the image_aspect_ratio field in the database.
	FieldImageAspectRatio = "image_aspect_ratio"
	// FieldVideoCount holds the string denoting the video_count field in the database.
	FieldVideoCount = "video_count"
	// FieldVideoResolution holds the string denoting the video_resolution field in the database.
	FieldVideoResolution = "video_resolution"
	// FieldVideoDurationSeconds holds the string denoting the video_duration_seconds field in the database.
	FieldVideoDurationSeconds = "video_duration_seconds"
	// FieldVideoAspectRatio holds the string denoting the video_aspect_ratio field in the database.
	FieldVideoAspectRatio = "video_aspect_ratio"
	// FieldLatencyMs holds the string denoting the latency_ms field in the database.
	FieldLatencyMs = "latency_ms"
	// FieldStartedAt holds the string denoting the started_at field in the database.
	FieldStartedAt = "started_at"
	// FieldFinishedAt holds the string denoting the finished_at field in the database.
	FieldFinishedAt = "finished_at"
	// FieldInputPayload holds the string denoting the input_payload field in the database.
	FieldInputPayload = "input_payload"
	// FieldOutputPayload holds the string denoting the output_payload field in the database.
	FieldOutputPayload = "output_payload"
	// FieldUsageDetail holds the string denoting the usage_detail field in the database.
	FieldUsageDetail = "usage_detail"
	// FieldCreatedAt holds the string denoting the created_at field in the database.
	FieldCreatedAt = "created_at"
	// FieldUpdatedAt holds the string denoting the updated_at field in the database.
	FieldUpdatedAt = "updated_at"
	// Table holds the table name of the modelcall in the database.
	Table = "model_call"
)

// Columns holds all SQL columns for modelcall fields.
var Columns = []string{
	FieldID,
	FieldGenerationTaskID,
	FieldCallerService,
	FieldBusinessScene,
	FieldOperation,
	FieldCapability,
	FieldModel,
	FieldProvider,
	FieldStatus,
	FieldDeliveryStatus,
	FieldErrorCategory,
	FieldErrorCode,
	FieldErrorReason,
	FieldErrorMessage,
	FieldInputTokens,
	FieldOutputTokens,
	FieldTotalTokens,
	FieldCachedTokens,
	FieldReasoningTokens,
	FieldImageCount,
	FieldImageSize,
	FieldImageAspectRatio,
	FieldVideoCount,
	FieldVideoResolution,
	FieldVideoDurationSeconds,
	FieldVideoAspectRatio,
	FieldLatencyMs,
	FieldStartedAt,
	FieldFinishedAt,
	FieldInputPayload,
	FieldOutputPayload,
	FieldUsageDetail,
	FieldCreatedAt,
	FieldUpdatedAt,
}

// ValidColumn reports if the column name is valid (part of the table columns).
func ValidColumn(column string) bool {
	for i := range Columns {
		if column == Columns[i] {
			return true
		}
	}
	return false
}

var (
	// DefaultCallerService holds the default value on creation for the "caller_service" field.
	DefaultCallerService string
	// DefaultBusinessScene holds the default value on creation for the "business_scene" field.
	DefaultBusinessScene string
	// DefaultDeliveryStatus holds the default value on creation for the "delivery_status" field.
	DefaultDeliveryStatus string
	// DefaultErrorCategory holds the default value on creation for the "error_category" field.
	DefaultErrorCategory string
	// DefaultErrorCode holds the default value on creation for the "error_code" field.
	DefaultErrorCode string
	// DefaultErrorReason holds the default value on creation for the "error_reason" field.
	DefaultErrorReason string
	// DefaultErrorMessage holds the default value on creation for the "error_message" field.
	DefaultErrorMessage string
	// DefaultImageSize holds the default value on creation for the "image_size" field.
	DefaultImageSize string
	// DefaultImageAspectRatio holds the default value on creation for the "image_aspect_ratio" field.
	DefaultImageAspectRatio string
	// DefaultVideoResolution holds the default value on creation for the "video_resolution" field.
	DefaultVideoResolution string
	// DefaultVideoAspectRatio holds the default value on creation for the "video_aspect_ratio" field.
	DefaultVideoAspectRatio string
	// DefaultLatencyMs holds the default value on creation for the "latency_ms" field.
	DefaultLatencyMs int64
	// DefaultInputPayload holds the default value on creation for the "input_payload" field.
	DefaultInputPayload map[string]interface{}
	// DefaultOutputPayload holds the default value on creation for the "output_payload" field.
	DefaultOutputPayload map[string]interface{}
	// DefaultUsageDetail holds the default value on creation for the "usage_detail" field.
	DefaultUsageDetail map[string]interface{}
	// DefaultCreatedAt holds the default value on creation for the "created_at" field.
	DefaultCreatedAt func() time.Time
	// DefaultUpdatedAt holds the default value on creation for the "updated_at" field.
	DefaultUpdatedAt func() time.Time
	// UpdateDefaultUpdatedAt holds the default value on update for the "updated_at" field.
	UpdateDefaultUpdatedAt func() time.Time
)

// OrderOption defines the ordering options for the ModelCall queries.
type OrderOption func(*sql.Selector)

// ByID orders the results by the id field.
func ByID(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldID, opts...).ToFunc()
}

// ByGenerationTaskID orders the results by the generation_task_id field.
func ByGenerationTaskID(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldGenerationTaskID, opts...).ToFunc()
}

// ByCallerService orders the results by the caller_service field.
func ByCallerService(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldCallerService, opts...).ToFunc()
}

// ByBusinessScene orders the results by the business_scene field.
func ByBusinessScene(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldBusinessScene, opts...).ToFunc()
}

// ByOperation orders the results by the operation field.
func ByOperation(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldOperation, opts...).ToFunc()
}

// ByCapability orders the results by the capability field.
func ByCapability(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldCapability, opts...).ToFunc()
}

// ByModel orders the results by the model field.
func ByModel(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldModel, opts...).ToFunc()
}

// ByProvider orders the results by the provider field.
func ByProvider(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldProvider, opts...).ToFunc()
}

// ByStatus orders the results by the status field.
func ByStatus(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldStatus, opts...).ToFunc()
}

// ByDeliveryStatus orders the results by the delivery_status field.
func ByDeliveryStatus(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldDeliveryStatus, opts...).ToFunc()
}

// ByErrorCategory orders the results by the error_category field.
func ByErrorCategory(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldErrorCategory, opts...).ToFunc()
}

// ByErrorCode orders the results by the error_code field.
func ByErrorCode(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldErrorCode, opts...).ToFunc()
}

// ByErrorReason orders the results by the error_reason field.
func ByErrorReason(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldErrorReason, opts...).ToFunc()
}

// ByErrorMessage orders the results by the error_message field.
func ByErrorMessage(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldErrorMessage, opts...).ToFunc()
}

// ByInputTokens orders the results by the input_tokens field.
func ByInputTokens(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldInputTokens, opts...).ToFunc()
}

// ByOutputTokens orders the results by the output_tokens field.
func ByOutputTokens(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldOutputTokens, opts...).ToFunc()
}

// ByTotalTokens orders the results by the total_tokens field.
func ByTotalTokens(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldTotalTokens, opts...).ToFunc()
}

// ByCachedTokens orders the results by the cached_tokens field.
func ByCachedTokens(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldCachedTokens, opts...).ToFunc()
}

// ByReasoningTokens orders the results by the reasoning_tokens field.
func ByReasoningTokens(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldReasoningTokens, opts...).ToFunc()
}

// ByImageCount orders the results by the image_count field.
func ByImageCount(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldImageCount, opts...).ToFunc()
}

// ByImageSize orders the results by the image_size field.
func ByImageSize(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldImageSize, opts...).ToFunc()
}

// ByImageAspectRatio orders the results by the image_aspect_ratio field.
func ByImageAspectRatio(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldImageAspectRatio, opts...).ToFunc()
}

// ByVideoCount orders the results by the video_count field.
func ByVideoCount(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldVideoCount, opts...).ToFunc()
}

// ByVideoResolution orders the results by the video_resolution field.
func ByVideoResolution(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldVideoResolution, opts...).ToFunc()
}

// ByVideoDurationSeconds orders the results by the video_duration_seconds field.
func ByVideoDurationSeconds(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldVideoDurationSeconds, opts...).ToFunc()
}

// ByVideoAspectRatio orders the results by the video_aspect_ratio field.
func ByVideoAspectRatio(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldVideoAspectRatio, opts...).ToFunc()
}

// ByLatencyMs orders the results by the latency_ms field.
func ByLatencyMs(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldLatencyMs, opts...).ToFunc()
}

// ByStartedAt orders the results by the started_at field.
func ByStartedAt(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldStartedAt, opts...).ToFunc()
}

// ByFinishedAt orders the results by the finished_at field.
func ByFinishedAt(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldFinishedAt, opts...).ToFunc()
}

// ByCreatedAt orders the results by the created_at field.
func ByCreatedAt(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldCreatedAt, opts...).ToFunc()
}

// ByUpdatedAt orders the results by the updated_at field.
func ByUpdatedAt(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldUpdatedAt, opts...).ToFunc()
}
