// Code generated by ent, DO NOT EDIT.

package modelcall

import (
	"time"

	"entgo.io/ent/dialect/sql"
	"github.com/wgdl666/wgModelHub/ent/predicate"
)

// ID filters vertices based on their ID field.
func ID(id string) predicate.ModelCall {
	return predicate.ModelCall(sql.FieldEQ(FieldID, id))
}

// IDEQ applies the EQ predicate on the ID field.
func IDEQ(id string) predicate.ModelCall {
	return predicate.ModelCall(sql.FieldEQ(FieldID, id))
}

// IDNEQ applies the NEQ predicate on the ID field.
func IDNEQ(id string) predicate.ModelCall {
	return predicate.ModelCall(sql.FieldNEQ(FieldID, id))
}

// IDIn applies the In predicate on the ID field.
func IDIn(ids ...string) predicate.ModelCall {
	return predicate.ModelCall(sql.FieldIn(FieldID, ids...))
}

// IDNotIn applies the NotIn predicate on the ID field.
func IDNotIn(ids ...string) predicate.ModelCall {
	return predicate.ModelCall(sql.FieldNotIn(FieldID, ids...))
}

// IDGT applies the GT predicate on the ID field.
func IDGT(id string) predicate.ModelCall {
	return predicate.ModelCall(sql.FieldGT(FieldID, id))
}

// IDGTE applies the GTE predicate on the ID field.
func IDGTE(id string) predicate.ModelCall {
	return predicate.ModelCall(sql.FieldGTE(FieldID, id))
}

// IDLT applies the LT predicate on the ID field.
func IDLT(id string) predicate.ModelCall {
	return predicate.ModelCall(sql.FieldLT(FieldID, id))
}

// IDLTE applies the LTE predicate on the ID field.
func IDLTE(id string) predicate.ModelCall {
	return predicate.ModelCall(sql.FieldLTE(FieldID, id))
}

// IDEqualFold applies the EqualFold predicate on the ID field.
func IDEqualFold(id string) predicate.ModelCall {
	return predicate.ModelCall(sql.FieldEqualFold(FieldID, id))
}

// IDContainsFold applies the ContainsFold predicate on the ID field.
func IDContainsFold(id string) predicate.ModelCall {
	return predicate.ModelCall(sql.FieldContainsFold(FieldID, id))
}

// GenerationTaskID applies equality check predicate on the "generation_task_id" field. It's identical to GenerationTaskIDEQ.
func GenerationTaskID(v string) predicate.ModelCall {
	return predicate.ModelCall(sql.FieldEQ(FieldGenerationTaskID, v))
}

// CallerService applies equality check predicate on the "caller_service" field. It's identical to CallerServiceEQ.
func CallerService(v string) predicate.ModelCall {
	return predicate.ModelCall(sql.FieldEQ(FieldCallerService, v))
}

// BusinessScene applies equality check predicate on the "business_scene" field. It's identical to BusinessSceneEQ.
func BusinessScene(v string) predicate.ModelCall {
	return predicate.ModelCall(sql.FieldEQ(FieldBusinessScene, v))
}

// Operation applies equality check predicate on the "operation" field. It's identical to OperationEQ.
func Operation(v string) predicate.ModelCall {
	return predicate.ModelCall(sql.FieldEQ(FieldOperation, v))
}

// Capability applies equality check predicate on the "capability" field. It's identical to CapabilityEQ.
func Capability(v string) predicate.ModelCall {
	return predicate.ModelCall(sql.FieldEQ(FieldCapability, v))
}

// Model applies equality check predicate on the "model" field. It's identical to ModelEQ.
func Model(v string) predicate.ModelCall {
	return predicate.ModelCall(sql.FieldEQ(FieldModel, v))
}

// Provider applies equality check predicate on the "provider" field. It's identical to ProviderEQ.
func Provider(v string) predicate.ModelCall {
	return predicate.ModelCall(sql.FieldEQ(FieldProvider, v))
}

// Status applies equality check predicate on the "status" field. It's identical to StatusEQ.
func Status(v string) predicate.ModelCall {
	return predicate.ModelCall(sql.FieldEQ(FieldStatus, v))
}

// DeliveryStatus applies equality check predicate on the "delivery_status" field. It's identical to DeliveryStatusEQ.
func DeliveryStatus(v string) predicate.ModelCall {
	return predicate.ModelCall(sql.FieldEQ(FieldDeliveryStatus, v))
}

// ErrorCategory applies equality check predicate on the "error_category" field. It's identical to ErrorCategoryEQ.
func ErrorCategory(v string) predicate.ModelCall {
	return predicate.ModelCall(sql.FieldEQ(FieldErrorCategory, v))
}

// ErrorCode applies equality check predicate on the "error_code" field. It's identical to ErrorCodeEQ.
func ErrorCode(v string) predicate.ModelCall {
	return predicate.ModelCall(sql.FieldEQ(FieldErrorCode, v))
}

// ErrorReason applies equality check predicate on the "error_reason" field. It's identical to ErrorReasonEQ.
func ErrorReason(v string) predicate.ModelCall {
	return predicate.ModelCall(sql.FieldEQ(FieldErrorReason, v))
}

// ErrorMessage applies equality check predicate on the "error_message" field. It's identical to ErrorMessageEQ.
func ErrorMessage(v string) predicate.ModelCall {
	return predicate.ModelCall(sql.FieldEQ(FieldErrorMessage, v))
}

// InputTokens applies equality check predicate on the "input_tokens" field. It's identical to InputTokensEQ.
func InputTokens(v int64) predicate.ModelCall {
	return predicate.ModelCall(sql.FieldEQ(FieldInputTokens, v))
}

// OutputTokens applies equality check predicate on the "output_tokens" field. It's identical to OutputTokensEQ.
func OutputTokens(v int64) predicate.ModelCall {
	return predicate.ModelCall(sql.FieldEQ(FieldOutputTokens, v))
}

// TotalTokens applies equality check predicate on the "total_tokens" field. It's identical to TotalTokensEQ.
func TotalTokens(v int64) predicate.ModelCall {
	return predicate.ModelCall(sql.FieldEQ(FieldTotalTokens, v))
}

// CachedTokens applies equality check predicate on the "cached_tokens" field. It's identical to CachedTokensEQ.
func CachedTokens(v int64) predicate.ModelCall {
	return predicate.ModelCall(sql.FieldEQ(FieldCachedTokens, v))
}

// ReasoningTokens applies equality check predicate on the "reasoning_tokens" field. It's identical to ReasoningTokensEQ.
func ReasoningTokens(v int64) predicate.ModelCall {
	return predicate.ModelCall(sql.FieldEQ(FieldReasoningTokens, v))
}

// ImageCount applies equality check predicate on the "image_count" field. It's identical to ImageCountEQ.
func ImageCount(v int) predicate.ModelCall {
	return predicate.ModelCall(sql.FieldEQ(FieldImageCount, v))
}

// ImageSize applies equality check predicate on the "image_size" field. It's identical to ImageSizeEQ.
func ImageSize(v string) predicate.ModelCall {
	return predicate.ModelCall(sql.FieldEQ(FieldImageSize, v))
}

// ImageAspectRatio applies equality check predicate on the "image_aspect_ratio" field. It's identical to ImageAspectRatioEQ.
func ImageAspectRatio(v string) predicate.ModelCall {
	return predicate.ModelCall(sql.FieldEQ(FieldImageAspectRatio, v))
}

// VideoCount applies equality check predicate on the "video_count" field. It's identical to VideoCountEQ.
func VideoCount(v int) predicate.ModelCall {
	return predicate.ModelCall(sql.FieldEQ(FieldVideoCount, v))
}

// VideoResolution applies equality check predicate on the "video_resolution" field. It's identical to VideoResolutionEQ.
func VideoResolution(v string) predicate.ModelCall {
	return predicate.ModelCall(sql.FieldEQ(FieldVideoResolution, v))
}

// VideoDurationSeconds applies equality check predicate on the "video_duration_seconds" field. It's identical to VideoDurationSecondsEQ.
func VideoDurationSeconds(v int) predicate.ModelCall {
	return predicate.ModelCall(sql.FieldEQ(FieldVideoDurationSeconds, v))
}

// VideoAspectRatio applies equality check predicate on the "video_aspect_ratio" field. It's identical to VideoAspectRatioEQ.
func VideoAspectRatio(v string) predicate.ModelCall {
	return predicate.ModelCall(sql.FieldEQ(FieldVideoAspectRatio, v))
}

// LatencyMs applies equality check predicate on the "latency_ms" field. It's identical to LatencyMsEQ.
func LatencyMs(v int64) predicate.ModelCall {
	return predicate.ModelCall(sql.FieldEQ(FieldLatencyMs, v))
}

// StartedAt applies equality check predicate on the "started_at" field. It's identical to StartedAtEQ.
func StartedAt(v time.Time) predicate.ModelCall {
	return predicate.ModelCall(sql.FieldEQ(FieldStartedAt, v))
}

// FinishedAt applies equality check predicate on the "finished_at" field. It's identical to FinishedAtEQ.
func FinishedAt(v time.Time) predicate.ModelCall {
	return predicate.ModelCall(sql.FieldEQ(FieldFinishedAt, v))
}

// CreatedAt applies equality check predicate on the "created_at" field. It's identical to CreatedAtEQ.
func CreatedAt(v time.Time) predicate.ModelCall {
	return predicate.ModelCall(sql.FieldEQ(FieldCreatedAt, v))
}

// UpdatedAt applies equality check predicate on the "updated_at" field. It's identical to UpdatedAtEQ.
func UpdatedAt(v time.Time) predicate.ModelCall {
	return predicate.ModelCall(sql.FieldEQ(FieldUpdatedAt, v))
}

// GenerationTaskIDEQ applies the EQ predicate on the "generation_task_id" field.
func GenerationTaskIDEQ(v string) predicate.ModelCall {
	return predicate.ModelCall(sql.FieldEQ(FieldGenerationTaskID, v))
}

// GenerationTaskIDNEQ applies the NEQ predicate on the "generation_task_id" field.
func GenerationTaskIDNEQ(v string) predicate.ModelCall {
	return predicate.ModelCall(sql.FieldNEQ(FieldGenerationTaskID, v))
}

// GenerationTaskIDIn applies the In predicate on the "generation_task_id" field.
func GenerationTaskIDIn(vs ...string) predicate.ModelCall {
	return predicate.ModelCall(sql.FieldIn(FieldGenerationTaskID, vs...))
}

// GenerationTaskIDNotIn applies the NotIn predicate on the "generation_task_id" field.
func GenerationTaskIDNotIn(vs ...string) predicate.ModelCall {
	return predicate.ModelCall(sql.FieldNotIn(FieldGenerationTaskID, vs...))
}

// GenerationTaskIDGT applies the GT predicate on the "generation_task_id" field.
func GenerationTaskIDGT(v string) predicate.ModelCall {
	return predicate.ModelCall(sql.FieldGT(FieldGenerationTaskID, v))
}

// GenerationTaskIDGTE applies the GTE predicate on the "generation_task_id" field.
func GenerationTaskIDGTE(v string) predicate.ModelCall {
	return predicate.ModelCall(sql.FieldGTE(FieldGenerationTaskID, v))
}

// GenerationTaskIDLT applies the LT predicate on the "generation_task_id" field.
func GenerationTaskIDLT(v string) predicate.ModelCall {
	return predicate.ModelCall(sql.FieldLT(FieldGenerationTaskID, v))
}

// GenerationTaskIDLTE applies the LTE predicate on the "generation_task_id" field.
func GenerationTaskIDLTE(v string) predicate.ModelCall {
	return predicate.ModelCall(sql.FieldLTE(FieldGenerationTaskID, v))
}

// GenerationTaskIDContains applies the Contains predicate on the "generation_task_id" field.
func GenerationTaskIDContains(v string) predicate.ModelCall {
	return predicate.ModelCall(sql.FieldContains(FieldGenerationTaskID, v))
}

// GenerationTaskIDHasPrefix applies the HasPrefix predicate on the "generation_task_id" field.
func GenerationTaskIDHasPrefix(v string) predicate.ModelCall {
	return predicate.ModelCall(sql.FieldHasPrefix(FieldGenerationTaskID, v))
}

// GenerationTaskIDHasSuffix applies the HasSuffix predicate on the "generation_task_id" field.
func GenerationTaskIDHasSuffix(v string) predicate.ModelCall {
	return predicate.ModelCall(sql.FieldHasSuffix(FieldGenerationTaskID, v))
}

// GenerationTaskIDIsNil applies the IsNil predicate on the "generation_task_id" field.
func GenerationTaskIDIsNil() predicate.ModelCall {
	return predicate.ModelCall(sql.FieldIsNull(FieldGenerationTaskID))
}

// GenerationTaskIDNotNil applies the NotNil predicate on the "generation_task_id" field.
func GenerationTaskIDNotNil() predicate.ModelCall {
	return predicate.ModelCall(sql.FieldNotNull(FieldGenerationTaskID))
}

// GenerationTaskIDEqualFold applies the EqualFold predicate on the "generation_task_id" field.
func GenerationTaskIDEqualFold(v string) predicate.ModelCall {
	return predicate.ModelCall(sql.FieldEqualFold(FieldGenerationTaskID, v))
}

// GenerationTaskIDContainsFold applies the ContainsFold predicate on the "generation_task_id" field.
func GenerationTaskIDContainsFold(v string) predicate.ModelCall {
	return predicate.ModelCall(sql.FieldContainsFold(FieldGenerationTaskID, v))
}

// CallerServiceEQ applies the EQ predicate on the "caller_service" field.
func CallerServiceEQ(v string) predicate.ModelCall {
	return predicate.ModelCall(sql.FieldEQ(FieldCallerService, v))
}

// CallerServiceNEQ applies the NEQ predicate on the "caller_service" field.
func CallerServiceNEQ(v string) predicate.ModelCall {
	return predicate.ModelCall(sql.FieldNEQ(FieldCallerService, v))
}

// CallerServiceIn applies the In predicate on the "caller_service" field.
func CallerServiceIn(vs ...string) predicate.ModelCall {
	return predicate.ModelCall(sql.FieldIn(FieldCallerService, vs...))
}

// CallerServiceNotIn applies the NotIn predicate on the "caller_service" field.
func CallerServiceNotIn(vs ...string) predicate.ModelCall {
	return predicate.ModelCall(sql.FieldNotIn(FieldCallerService, vs...))
}

// CallerServiceGT applies the GT predicate on the "caller_service" field.
func CallerServiceGT(v string) predicate.ModelCall {
	return predicate.ModelCall(sql.FieldGT(FieldCallerService, v))
}

// CallerServiceGTE applies the GTE predicate on the "caller_service" field.
func CallerServiceGTE(v string) predicate.ModelCall {
	return predicate.ModelCall(sql.FieldGTE(FieldCallerService, v))
}

// CallerServiceLT applies the LT predicate on the "caller_service" field.
func CallerServiceLT(v string) predicate.ModelCall {
	return predicate.ModelCall(sql.FieldLT(FieldCallerService, v))
}

// CallerServiceLTE applies the LTE predicate on the "caller_service" field.
func CallerServiceLTE(v string) predicate.ModelCall {
	return predicate.ModelCall(sql.FieldLTE(FieldCallerService, v))
}

// CallerServiceContains applies the Contains predicate on the "caller_service" field.
func CallerServiceContains(v string) predicate.ModelCall {
	return predicate.ModelCall(sql.FieldContains(FieldCallerService, v))
}

// CallerServiceHasPrefix applies the HasPrefix predicate on the "caller_service" field.
func CallerServiceHasPrefix(v string) predicate.ModelCall {
	return predicate.ModelCall(sql.FieldHasPrefix(FieldCallerService, v))
}

// CallerServiceHasSuffix applies the HasSuffix predicate on the "caller_service" field.
func CallerServiceHasSuffix(v string) predicate.ModelCall {
	return predicate.ModelCall(sql.FieldHasSuffix(FieldCallerService, v))
}

// CallerServiceEqualFold applies the EqualFold predicate on the "caller_service" field.
func CallerServiceEqualFold(v string) predicate.ModelCall {
	return predicate.ModelCall(sql.FieldEqualFold(FieldCallerService, v))
}

// CallerServiceContainsFold applies the ContainsFold predicate on the "caller_service" field.
func CallerServiceContainsFold(v string) predicate.ModelCall {
	return predicate.ModelCall(sql.FieldContainsFold(FieldCallerService, v))
}

// BusinessSceneEQ applies the EQ predicate on the "business_scene" field.
func BusinessSceneEQ(v string) predicate.ModelCall {
	return predicate.ModelCall(sql.FieldEQ(FieldBusinessScene, v))
}

// BusinessSceneNEQ applies the NEQ predicate on the "business_scene" field.
func BusinessSceneNEQ(v string) predicate.ModelCall {
	return predicate.ModelCall(sql.FieldNEQ(FieldBusinessScene, v))
}

// BusinessSceneIn applies the In predicate on the "business_scene" field.
func BusinessSceneIn(vs ...string) predicate.ModelCall {
	return predicate.ModelCall(sql.FieldIn(FieldBusinessScene, vs...))
}

// BusinessSceneNotIn applies the NotIn predicate on the "business_scene" field.
func BusinessSceneNotIn(vs ...string) predicate.ModelCall {
	return predicate.ModelCall(sql.FieldNotIn(FieldBusinessScene, vs...))
}

// BusinessSceneGT applies the GT predicate on the "business_scene" field.
func BusinessSceneGT(v string) predicate.ModelCall {
	return predicate.ModelCall(sql.FieldGT(FieldBusinessScene, v))
}

// BusinessSceneGTE applies the GTE predicate on the "business_scene" field.
func BusinessSceneGTE(v string) predicate.ModelCall {
	return predicate.ModelCall(sql.FieldGTE(FieldBusinessScene, v))
}

// BusinessSceneLT applies the LT predicate on the "business_scene" field.
func BusinessSceneLT(v string) predicate.ModelCall {
	return predicate.ModelCall(sql.FieldLT(FieldBusinessScene, v))
}

// BusinessSceneLTE applies the LTE predicate on the "business_scene" field.
func BusinessSceneLTE(v string) predicate.ModelCall {
	return predicate.ModelCall(sql.FieldLTE(FieldBusinessScene, v))
}

// BusinessSceneContains applies the Contains predicate on the "business_scene" field.
func BusinessSceneContains(v string) predicate.ModelCall {
	return predicate.ModelCall(sql.FieldContains(FieldBusinessScene, v))
}

// BusinessSceneHasPrefix applies the HasPrefix predicate on the "business_scene" field.
func BusinessSceneHasPrefix(v string) predicate.ModelCall {
	return predicate.ModelCall(sql.FieldHasPrefix(FieldBusinessScene, v))
}

// BusinessSceneHasSuffix applies the HasSuffix predicate on the "business_scene" field.
func BusinessSceneHasSuffix(v string) predicate.ModelCall {
	return predicate.ModelCall(sql.FieldHasSuffix(FieldBusinessScene, v))
}

// BusinessSceneEqualFold applies the EqualFold predicate on the "business_scene" field.
func BusinessSceneEqualFold(v string) predicate.ModelCall {
	return predicate.ModelCall(sql.FieldEqualFold(FieldBusinessScene, v))
}

// BusinessSceneContainsFold applies the ContainsFold predicate on the "business_scene" field.
func BusinessSceneContainsFold(v string) predicate.ModelCall {
	return predicate.ModelCall(sql.FieldContainsFold(FieldBusinessScene, v))
}

// OperationEQ applies the EQ predicate on the "operation" field.
func OperationEQ(v string) predicate.ModelCall {
	return predicate.ModelCall(sql.FieldEQ(FieldOperation, v))
}

// OperationNEQ applies the NEQ predicate on the "operation" field.
func OperationNEQ(v string) predicate.ModelCall {
	return predicate.ModelCall(sql.FieldNEQ(FieldOperation, v))
}

// OperationIn applies the In predicate on the "operation" field.
func OperationIn(vs ...string) predicate.ModelCall {
	return predicate.ModelCall(sql.FieldIn(FieldOperation, vs...))
}

// OperationNotIn applies the NotIn predicate on the "operation" field.
func OperationNotIn(vs ...string) predicate.ModelCall {
	return predicate.ModelCall(sql.FieldNotIn(FieldOperation, vs...))
}

// OperationGT applies the GT predicate on the "operation" field.
func OperationGT(v string) predicate.ModelCall {
	return predicate.ModelCall(sql.FieldGT(FieldOperation, v))
}

// OperationGTE applies the GTE predicate on the "operation" field.
func OperationGTE(v string) predicate.ModelCall {
	return predicate.ModelCall(sql.FieldGTE(FieldOperation, v))
}

// OperationLT applies the LT predicate on the "operation" field.
func OperationLT(v string) predicate.ModelCall {
	return predicate.ModelCall(sql.FieldLT(FieldOperation, v))
}

// OperationLTE applies the LTE predicate on the "operation" field.
func OperationLTE(v string) predicate.ModelCall {
	return predicate.ModelCall(sql.FieldLTE(FieldOperation, v))
}

// OperationContains applies the Contains predicate on the "operation" field.
func OperationContains(v string) predicate.ModelCall {
	return predicate.ModelCall(sql.FieldContains(FieldOperation, v))
}

// OperationHasPrefix applies the HasPrefix predicate on the "operation" field.
func OperationHasPrefix(v string) predicate.ModelCall {
	return predicate.ModelCall(sql.FieldHasPrefix(FieldOperation, v))
}

// OperationHasSuffix applies the HasSuffix predicate on the "operation" field.
func OperationHasSuffix(v string) predicate.ModelCall {
	return predicate.ModelCall(sql.FieldHasSuffix(FieldOperation, v))
}

// OperationEqualFold applies the EqualFold predicate on the "operation" field.
func OperationEqualFold(v string) predicate.ModelCall {
	return predicate.ModelCall(sql.FieldEqualFold(FieldOperation, v))
}

// OperationContainsFold applies the ContainsFold predicate on the "operation" field.
func OperationContainsFold(v string) predicate.ModelCall {
	return predicate.ModelCall(sql.FieldContainsFold(FieldOperation, v))
}

// CapabilityEQ applies the EQ predicate on the "capability" field.
func CapabilityEQ(v string) predicate.ModelCall {
	return predicate.ModelCall(sql.FieldEQ(FieldCapability, v))
}

// CapabilityNEQ applies the NEQ predicate on the "capability" field.
func CapabilityNEQ(v string) predicate.ModelCall {
	return predicate.ModelCall(sql.FieldNEQ(FieldCapability, v))
}

// CapabilityIn applies the In predicate on the "capability" field.
func CapabilityIn(vs ...string) predicate.ModelCall {
	return predicate.ModelCall(sql.FieldIn(FieldCapability, vs...))
}

// CapabilityNotIn applies the NotIn predicate on the "capability" field.
func CapabilityNotIn(vs ...string) predicate.ModelCall {
	return predicate.ModelCall(sql.FieldNotIn(FieldCapability, vs...))
}

// CapabilityGT applies the GT predicate on the "capability" field.
func CapabilityGT(v string) predicate.ModelCall {
	return predicate.ModelCall(sql.FieldGT(FieldCapability, v))
}

// CapabilityGTE applies the GTE predicate on the "capability" field.
func CapabilityGTE(v string) predicate.ModelCall {
	return predicate.ModelCall(sql.FieldGTE(FieldCapability, v))
}

// CapabilityLT applies the LT predicate on the "capability" field.
func CapabilityLT(v string) predicate.ModelCall {
	return predicate.ModelCall(sql.FieldLT(FieldCapability, v))
}

// CapabilityLTE applies the LTE predicate on the "capability" field.
func CapabilityLTE(v string) predicate.ModelCall {
	return predicate.ModelCall(sql.FieldLTE(FieldCapability, v))
}

// CapabilityContains applies the Contains predicate on the "capability" field.
func CapabilityContains(v string) predicate.ModelCall {
	return predicate.ModelCall(sql.FieldContains(FieldCapability, v))
}

// CapabilityHasPrefix applies the HasPrefix predicate on the "capability" field.
func CapabilityHasPrefix(v string) predicate.ModelCall {
	return predicate.ModelCall(sql.FieldHasPrefix(FieldCapability, v))
}

// CapabilityHasSuffix applies the HasSuffix predicate on the "capability" field.
func CapabilityHasSuffix(v string) predicate.ModelCall {
	return predicate.ModelCall(sql.FieldHasSuffix(FieldCapability, v))
}

// CapabilityEqualFold applies the EqualFold predicate on the "capability" field.
func CapabilityEqualFold(v string) predicate.ModelCall {
	return predicate.ModelCall(sql.FieldEqualFold(FieldCapability, v))
}

// CapabilityContainsFold applies the ContainsFold predicate on the "capability" field.
func CapabilityContainsFold(v string) predicate.ModelCall {
	return predicate.ModelCall(sql.FieldContainsFold(FieldCapability, v))
}

// ModelEQ applies the EQ predicate on the "model" field.
func ModelEQ(v string) predicate.ModelCall {
	return predicate.ModelCall(sql.FieldEQ(FieldModel, v))
}

// ModelNEQ applies the NEQ predicate on the "model" field.
func ModelNEQ(v string) predicate.ModelCall {
	return predicate.ModelCall(sql.FieldNEQ(FieldModel, v))
}

// ModelIn applies the In predicate on the "model" field.
func ModelIn(vs ...string) predicate.ModelCall {
	return predicate.ModelCall(sql.FieldIn(FieldModel, vs...))
}

// ModelNotIn applies the NotIn predicate on the "model" field.
func ModelNotIn(vs ...string) predicate.ModelCall {
	return predicate.ModelCall(sql.FieldNotIn(FieldModel, vs...))
}

// ModelGT applies the GT predicate on the "model" field.
func ModelGT(v string) predicate.ModelCall {
	return predicate.ModelCall(sql.FieldGT(FieldModel, v))
}

// ModelGTE applies the GTE predicate on the "model" field.
func ModelGTE(v string) predicate.ModelCall {
	return predicate.ModelCall(sql.FieldGTE(FieldModel, v))
}

// ModelLT applies the LT predicate on the "model" field.
func ModelLT(v string) predicate.ModelCall {
	return predicate.ModelCall(sql.FieldLT(FieldModel, v))
}

// ModelLTE applies the LTE predicate on the "model" field.
func ModelLTE(v string) predicate.ModelCall {
	return predicate.ModelCall(sql.FieldLTE(FieldModel, v))
}

// ModelContains applies the Contains predicate on the "model" field.
func ModelContains(v string) predicate.ModelCall {
	return predicate.ModelCall(sql.FieldContains(FieldModel, v))
}

// ModelHasPrefix applies the HasPrefix predicate on the "model" field.
func ModelHasPrefix(v string) predicate.ModelCall {
	return predicate.ModelCall(sql.FieldHasPrefix(FieldModel, v))
}

// ModelHasSuffix applies the HasSuffix predicate on the "model" field.
func ModelHasSuffix(v string) predicate.ModelCall {
	return predicate.ModelCall(sql.FieldHasSuffix(FieldModel, v))
}

// ModelEqualFold applies the EqualFold predicate on the "model" field.
func ModelEqualFold(v string) predicate.ModelCall {
	return predicate.ModelCall(sql.FieldEqualFold(FieldModel, v))
}

// ModelContainsFold applies the ContainsFold predicate on the "model" field.
func ModelContainsFold(v string) predicate.ModelCall {
	return predicate.ModelCall(sql.FieldContainsFold(FieldModel, v))
}

// ProviderEQ applies the EQ predicate on the "provider" field.
func ProviderEQ(v string) predicate.ModelCall {
	return predicate.ModelCall(sql.FieldEQ(FieldProvider, v))
}

// ProviderNEQ applies the NEQ predicate on the "provider" field.
func ProviderNEQ(v string) predicate.ModelCall {
	return predicate.ModelCall(sql.FieldNEQ(FieldProvider, v))
}

// ProviderIn applies the In predicate on the "provider" field.
func ProviderIn(vs ...string) predicate.ModelCall {
	return predicate.ModelCall(sql.FieldIn(FieldProvider, vs...))
}

// ProviderNotIn applies the NotIn predicate on the "provider" field.
func ProviderNotIn(vs ...string) predicate.ModelCall {
	return predicate.ModelCall(sql.FieldNotIn(FieldProvider, vs...))
}

// ProviderGT applies the GT predicate on the "provider" field.
func ProviderGT(v string) predicate.ModelCall {
	return predicate.ModelCall(sql.FieldGT(FieldProvider, v))
}

// ProviderGTE applies the GTE predicate on the "provider" field.
func ProviderGTE(v string) predicate.ModelCall {
	return predicate.ModelCall(sql.FieldGTE(FieldProvider, v))
}

// ProviderLT applies the LT predicate on the "provider" field.
func ProviderLT(v string) predicate.ModelCall {
	return predicate.ModelCall(sql.FieldLT(FieldProvider, v))
}

// ProviderLTE applies the LTE predicate on the "provider" field.
func ProviderLTE(v string) predicate.ModelCall {
	return predicate.ModelCall(sql.FieldLTE(FieldProvider, v))
}

// ProviderContains applies the Contains predicate on the "provider" field.
func ProviderContains(v string) predicate.ModelCall {
	return predicate.ModelCall(sql.FieldContains(FieldProvider, v))
}

// ProviderHasPrefix applies the HasPrefix predicate on the "provider" field.
func ProviderHasPrefix(v string) predicate.ModelCall {
	return predicate.ModelCall(sql.FieldHasPrefix(FieldProvider, v))
}

// ProviderHasSuffix applies the HasSuffix predicate on the "provider" field.
func ProviderHasSuffix(v string) predicate.ModelCall {
	return predicate.ModelCall(sql.FieldHasSuffix(FieldProvider, v))
}

// ProviderEqualFold applies the EqualFold predicate on the "provider" field.
func ProviderEqualFold(v string) predicate.ModelCall {
	return predicate.ModelCall(sql.FieldEqualFold(FieldProvider, v))
}

// ProviderContainsFold applies the ContainsFold predicate on the "provider" field.
func ProviderContainsFold(v string) predicate.ModelCall {
	return predicate.ModelCall(sql.FieldContainsFold(FieldProvider, v))
}

// StatusEQ applies the EQ predicate on the "status" field.
func StatusEQ(v string) predicate.ModelCall {
	return predicate.ModelCall(sql.FieldEQ(FieldStatus, v))
}

// StatusNEQ applies the NEQ predicate on the "status" field.
func StatusNEQ(v string) predicate.ModelCall {
	return predicate.ModelCall(sql.FieldNEQ(FieldStatus, v))
}

// StatusIn applies the In predicate on the "status" field.
func StatusIn(vs ...string) predicate.ModelCall {
	return predicate.ModelCall(sql.FieldIn(FieldStatus, vs...))
}

// StatusNotIn applies the NotIn predicate on the "status" field.
func StatusNotIn(vs ...string) predicate.ModelCall {
	return predicate.ModelCall(sql.FieldNotIn(FieldStatus, vs...))
}

// StatusGT applies the GT predicate on the "status" field.
func StatusGT(v string) predicate.ModelCall {
	return predicate.ModelCall(sql.FieldGT(FieldStatus, v))
}

// StatusGTE applies the GTE predicate on the "status" field.
func StatusGTE(v string) predicate.ModelCall {
	return predicate.ModelCall(sql.FieldGTE(FieldStatus, v))
}

// StatusLT applies the LT predicate on the "status" field.
func StatusLT(v string) predicate.ModelCall {
	return predicate.ModelCall(sql.FieldLT(FieldStatus, v))
}

// StatusLTE applies the LTE predicate on the "status" field.
func StatusLTE(v string) predicate.ModelCall {
	return predicate.ModelCall(sql.FieldLTE(FieldStatus, v))
}

// StatusContains applies the Contains predicate on the "status" field.
func StatusContains(v string) predicate.ModelCall {
	return predicate.ModelCall(sql.FieldContains(FieldStatus, v))
}

// StatusHasPrefix applies the HasPrefix predicate on the "status" field.
func StatusHasPrefix(v string) predicate.ModelCall {
	return predicate.ModelCall(sql.FieldHasPrefix(FieldStatus, v))
}

// StatusHasSuffix applies the HasSuffix predicate on the "status" field.
func StatusHasSuffix(v string) predicate.ModelCall {
	return predicate.ModelCall(sql.FieldHasSuffix(FieldStatus, v))
}

// StatusEqualFold applies the EqualFold predicate on the "status" field.
func StatusEqualFold(v string) predicate.ModelCall {
	return predicate.ModelCall(sql.FieldEqualFold(FieldStatus, v))
}

// StatusContainsFold applies the ContainsFold predicate on the "status" field.
func StatusContainsFold(v string) predicate.ModelCall {
	return predicate.ModelCall(sql.FieldContainsFold(FieldStatus, v))
}

// DeliveryStatusEQ applies the EQ predicate on the "delivery_status" field.
func DeliveryStatusEQ(v string) predicate.ModelCall {
	return predicate.ModelCall(sql.FieldEQ(FieldDeliveryStatus, v))
}

// DeliveryStatusNEQ applies the NEQ predicate on the "delivery_status" field.
func DeliveryStatusNEQ(v string) predicate.ModelCall {
	return predicate.ModelCall(sql.FieldNEQ(FieldDeliveryStatus, v))
}

// DeliveryStatusIn applies the In predicate on the "delivery_status" field.
func DeliveryStatusIn(vs ...string) predicate.ModelCall {
	return predicate.ModelCall(sql.FieldIn(FieldDeliveryStatus, vs...))
}

// DeliveryStatusNotIn applies the NotIn predicate on the "delivery_status" field.
func DeliveryStatusNotIn(vs ...string) predicate.ModelCall {
	return predicate.ModelCall(sql.FieldNotIn(FieldDeliveryStatus, vs...))
}

// DeliveryStatusGT applies the GT predicate on the "delivery_status" field.
func DeliveryStatusGT(v string) predicate.ModelCall {
	return predicate.ModelCall(sql.FieldGT(FieldDeliveryStatus, v))
}

// DeliveryStatusGTE applies the GTE predicate on the "delivery_status" field.
func DeliveryStatusGTE(v string) predicate.ModelCall {
	return predicate.ModelCall(sql.FieldGTE(FieldDeliveryStatus, v))
}

// DeliveryStatusLT applies the LT predicate on the "delivery_status" field.
func DeliveryStatusLT(v string) predicate.ModelCall {
	return predicate.ModelCall(sql.FieldLT(FieldDeliveryStatus, v))
}

// DeliveryStatusLTE applies the LTE predicate on the "delivery_status" field.
func DeliveryStatusLTE(v string) predicate.ModelCall {
	return predicate.ModelCall(sql.FieldLTE(FieldDeliveryStatus, v))
}

// DeliveryStatusContains applies the Contains predicate on the "delivery_status" field.
func DeliveryStatusContains(v string) predicate.ModelCall {
	return predicate.ModelCall(sql.FieldContains(FieldDeliveryStatus, v))
}

// DeliveryStatusHasPrefix applies the HasPrefix predicate on the "delivery_status" field.
func DeliveryStatusHasPrefix(v string) predicate.ModelCall {
	return predicate.ModelCall(sql.FieldHasPrefix(FieldDeliveryStatus, v))
}

// DeliveryStatusHasSuffix applies the HasSuffix predicate on the "delivery_status" field.
func DeliveryStatusHasSuffix(v string) predicate.ModelCall {
	return predicate.ModelCall(sql.FieldHasSuffix(FieldDeliveryStatus, v))
}

// DeliveryStatusEqualFold applies the EqualFold predicate on the "delivery_status" field.
func DeliveryStatusEqualFold(v string) predicate.ModelCall {
	return predicate.ModelCall(sql.FieldEqualFold(FieldDeliveryStatus, v))
}

// DeliveryStatusContainsFold applies the ContainsFold predicate on the "delivery_status" field.
func DeliveryStatusContainsFold(v string) predicate.ModelCall {
	return predicate.ModelCall(sql.FieldContainsFold(FieldDeliveryStatus, v))
}

// ErrorCategoryEQ applies the EQ predicate on the "error_category" field.
func ErrorCategoryEQ(v string) predicate.ModelCall {
	return predicate.ModelCall(sql.FieldEQ(FieldErrorCategory, v))
}

// ErrorCategoryNEQ applies the NEQ predicate on the "error_category" field.
func ErrorCategoryNEQ(v string) predicate.ModelCall {
	return predicate.ModelCall(sql.FieldNEQ(FieldErrorCategory, v))
}

// ErrorCategoryIn applies the In predicate on the "error_category" field.
func ErrorCategoryIn(vs ...string) predicate.ModelCall {
	return predicate.ModelCall(sql.FieldIn(FieldErrorCategory, vs...))
}

// ErrorCategoryNotIn applies the NotIn predicate on the "error_category" field.
func ErrorCategoryNotIn(vs ...string) predicate.ModelCall {
	return predicate.ModelCall(sql.FieldNotIn(FieldErrorCategory, vs...))
}

// ErrorCategoryGT applies the GT predicate on the "error_category" field.
func ErrorCategoryGT(v string) predicate.ModelCall {
	return predicate.ModelCall(sql.FieldGT(FieldErrorCategory, v))
}

// ErrorCategoryGTE applies the GTE predicate on the "error_category" field.
func ErrorCategoryGTE(v string) predicate.ModelCall {
	return predicate.ModelCall(sql.FieldGTE(FieldErrorCategory, v))
}

// ErrorCategoryLT applies the LT predicate on the "error_category" field.
func ErrorCategoryLT(v string) predicate.ModelCall {
	return predicate.ModelCall(sql.FieldLT(FieldErrorCategory, v))
}

// ErrorCategoryLTE applies the LTE predicate on the "error_category" field.
func ErrorCategoryLTE(v string) predicate.ModelCall {
	return predicate.ModelCall(sql.FieldLTE(FieldErrorCategory, v))
}

// ErrorCategoryContains applies the Contains predicate on the "error_category" field.
func ErrorCategoryContains(v string) predicate.ModelCall {
	return predicate.ModelCall(sql.FieldContains(FieldErrorCategory, v))
}

// ErrorCategoryHasPrefix applies the HasPrefix predicate on the "error_category" field.
func ErrorCategoryHasPrefix(v string) predicate.ModelCall {
	return predicate.ModelCall(sql.FieldHasPrefix(FieldErrorCategory, v))
}

// ErrorCategoryHasSuffix applies the HasSuffix predicate on the "error_category" field.
func ErrorCategoryHasSuffix(v string) predicate.ModelCall {
	return predicate.ModelCall(sql.FieldHasSuffix(FieldErrorCategory, v))
}

// ErrorCategoryEqualFold applies the EqualFold predicate on the "error_category" field.
func ErrorCategoryEqualFold(v string) predicate.ModelCall {
	return predicate.ModelCall(sql.FieldEqualFold(FieldErrorCategory, v))
}

// ErrorCategoryContainsFold applies the ContainsFold predicate on the "error_category" field.
func ErrorCategoryContainsFold(v string) predicate.ModelCall {
	return predicate.ModelCall(sql.FieldContainsFold(FieldErrorCategory, v))
}

// ErrorCodeEQ applies the EQ predicate on the "error_code" field.
func ErrorCodeEQ(v string) predicate.ModelCall {
	return predicate.ModelCall(sql.FieldEQ(FieldErrorCode, v))
}

// ErrorCodeNEQ applies the NEQ predicate on the "error_code" field.
func ErrorCodeNEQ(v string) predicate.ModelCall {
	return predicate.ModelCall(sql.FieldNEQ(FieldErrorCode, v))
}

// ErrorCodeIn applies the In predicate on the "error_code" field.
func ErrorCodeIn(vs ...string) predicate.ModelCall {
	return predicate.ModelCall(sql.FieldIn(FieldErrorCode, vs...))
}

// ErrorCodeNotIn applies the NotIn predicate on the "error_code" field.
func ErrorCodeNotIn(vs ...string) predicate.ModelCall {
	return predicate.ModelCall(sql.FieldNotIn(FieldErrorCode, vs...))
}

// ErrorCodeGT applies the GT predicate on the "error_code" field.
func ErrorCodeGT(v string) predicate.ModelCall {
	return predicate.ModelCall(sql.FieldGT(FieldErrorCode, v))
}

// ErrorCodeGTE applies the GTE predicate on the "error_code" field.
func ErrorCodeGTE(v string) predicate.ModelCall {
	return predicate.ModelCall(sql.FieldGTE(FieldErrorCode, v))
}

// ErrorCodeLT applies the LT predicate on the "error_code" field.
func ErrorCodeLT(v string) predicate.ModelCall {
	return predicate.ModelCall(sql.FieldLT(FieldErrorCode, v))
}

// ErrorCodeLTE applies the LTE predicate on the "error_code" field.
func ErrorCodeLTE(v string) predicate.ModelCall {
	return predicate.ModelCall(sql.FieldLTE(FieldErrorCode, v))
}

// ErrorCodeContains applies the Contains predicate on the "error_code" field.
func ErrorCodeContains(v string) predicate.ModelCall {
	return predicate.ModelCall(sql.FieldContains(FieldErrorCode, v))
}

// ErrorCodeHasPrefix applies the HasPrefix predicate on the "error_code" field.
func ErrorCodeHasPrefix(v string) predicate.ModelCall {
	return predicate.ModelCall(sql.FieldHasPrefix(FieldErrorCode, v))
}

// ErrorCodeHasSuffix applies the HasSuffix predicate on the "error_code" field.
func ErrorCodeHasSuffix(v string) predicate.ModelCall {
	return predicate.ModelCall(sql.FieldHasSuffix(FieldErrorCode, v))
}

// ErrorCodeEqualFold applies the EqualFold predicate on the "error_code" field.
func ErrorCodeEqualFold(v string) predicate.ModelCall {
	return predicate.ModelCall(sql.FieldEqualFold(FieldErrorCode, v))
}

// ErrorCodeContainsFold applies the ContainsFold predicate on the "error_code" field.
func ErrorCodeContainsFold(v string) predicate.ModelCall {
	return predicate.ModelCall(sql.FieldContainsFold(FieldErrorCode, v))
}

// ErrorReasonEQ applies the EQ predicate on the "error_reason" field.
func ErrorReasonEQ(v string) predicate.ModelCall {
	return predicate.ModelCall(sql.FieldEQ(FieldErrorReason, v))
}

// ErrorReasonNEQ applies the NEQ predicate on the "error_reason" field.
func ErrorReasonNEQ(v string) predicate.ModelCall {
	return predicate.ModelCall(sql.FieldNEQ(FieldErrorReason, v))
}

// ErrorReasonIn applies the In predicate on the "error_reason" field.
func ErrorReasonIn(vs ...string) predicate.ModelCall {
	return predicate.ModelCall(sql.FieldIn(FieldErrorReason, vs...))
}

// ErrorReasonNotIn applies the NotIn predicate on the "error_reason" field.
func ErrorReasonNotIn(vs ...string) predicate.ModelCall {
	return predicate.ModelCall(sql.FieldNotIn(FieldErrorReason, vs...))
}

// ErrorReasonGT applies the GT predicate on the "error_reason" field.
func ErrorReasonGT(v string) predicate.ModelCall {
	return predicate.ModelCall(sql.FieldGT(FieldErrorReason, v))
}

// ErrorReasonGTE applies the GTE predicate on the "error_reason" field.
func ErrorReasonGTE(v string) predicate.ModelCall {
	return predicate.ModelCall(sql.FieldGTE(FieldErrorReason, v))
}

// ErrorReasonLT applies the LT predicate on the "error_reason" field.
func ErrorReasonLT(v string) predicate.ModelCall {
	return predicate.ModelCall(sql.FieldLT(FieldErrorReason, v))
}

// ErrorReasonLTE applies the LTE predicate on the "error_reason" field.
func ErrorReasonLTE(v string) predicate.ModelCall {
	return predicate.ModelCall(sql.FieldLTE(FieldErrorReason, v))
}

// ErrorReasonContains applies the Contains predicate on the "error_reason" field.
func ErrorReasonContains(v string) predicate.ModelCall {
	return predicate.ModelCall(sql.FieldContains(FieldErrorReason, v))
}

// ErrorReasonHasPrefix applies the HasPrefix predicate on the "error_reason" field.
func ErrorReasonHasPrefix(v string) predicate.ModelCall {
	return predicate.ModelCall(sql.FieldHasPrefix(FieldErrorReason, v))
}

// ErrorReasonHasSuffix applies the HasSuffix predicate on the "error_reason" field.
func ErrorReasonHasSuffix(v string) predicate.ModelCall {
	return predicate.ModelCall(sql.FieldHasSuffix(FieldErrorReason, v))
}

// ErrorReasonEqualFold applies the EqualFold predicate on the "error_reason" field.
func ErrorReasonEqualFold(v string) predicate.ModelCall {
	return predicate.ModelCall(sql.FieldEqualFold(FieldErrorReason, v))
}

// ErrorReasonContainsFold applies the ContainsFold predicate on the "error_reason" field.
func ErrorReasonContainsFold(v string) predicate.ModelCall {
	return predicate.ModelCall(sql.FieldContainsFold(FieldErrorReason, v))
}

// ErrorMessageEQ applies the EQ predicate on the "error_message" field.
func ErrorMessageEQ(v string) predicate.ModelCall {
	return predicate.ModelCall(sql.FieldEQ(FieldErrorMessage, v))
}

// ErrorMessageNEQ applies the NEQ predicate on the "error_message" field.
func ErrorMessageNEQ(v string) predicate.ModelCall {
	return predicate.ModelCall(sql.FieldNEQ(FieldErrorMessage, v))
}

// ErrorMessageIn applies the In predicate on the "error_message" field.
func ErrorMessageIn(vs ...string) predicate.ModelCall {
	return predicate.ModelCall(sql.FieldIn(FieldErrorMessage, vs...))
}

// ErrorMessageNotIn applies the NotIn predicate on the "error_message" field.
func ErrorMessageNotIn(vs ...string) predicate.ModelCall {
	return predicate.ModelCall(sql.FieldNotIn(FieldErrorMessage, vs...))
}

// ErrorMessageGT applies the GT predicate on the "error_message" field.
func ErrorMessageGT(v string) predicate.ModelCall {
	return predicate.ModelCall(sql.FieldGT(FieldErrorMessage, v))
}

// ErrorMessageGTE applies the GTE predicate on the "error_message" field.
func ErrorMessageGTE(v string) predicate.ModelCall {
	return predicate.ModelCall(sql.FieldGTE(FieldErrorMessage, v))
}

// ErrorMessageLT applies the LT predicate on the "error_message" field.
func ErrorMessageLT(v string) predicate.ModelCall {
	return predicate.ModelCall(sql.FieldLT(FieldErrorMessage, v))
}

// ErrorMessageLTE applies the LTE predicate on the "error_message" field.
func ErrorMessageLTE(v string) predicate.ModelCall {
	return predicate.ModelCall(sql.FieldLTE(FieldErrorMessage, v))
}

// ErrorMessageContains applies the Contains predicate on the "error_message" field.
func ErrorMessageContains(v string) predicate.ModelCall {
	return predicate.ModelCall(sql.FieldContains(FieldErrorMessage, v))
}

// ErrorMessageHasPrefix applies the HasPrefix predicate on the "error_message" field.
func ErrorMessageHasPrefix(v string) predicate.ModelCall {
	return predicate.ModelCall(sql.FieldHasPrefix(FieldErrorMessage, v))
}

// ErrorMessageHasSuffix applies the HasSuffix predicate on the "error_message" field.
func ErrorMessageHasSuffix(v string) predicate.ModelCall {
	return predicate.ModelCall(sql.FieldHasSuffix(FieldErrorMessage, v))
}

// ErrorMessageEqualFold applies the EqualFold predicate on the "error_message" field.
func ErrorMessageEqualFold(v string) predicate.ModelCall {
	return predicate.ModelCall(sql.FieldEqualFold(FieldErrorMessage, v))
}

// ErrorMessageContainsFold applies the ContainsFold predicate on the "error_message" field.
func ErrorMessageContainsFold(v string) predicate.ModelCall {
	return predicate.ModelCall(sql.FieldContainsFold(FieldErrorMessage, v))
}

// InputTokensEQ applies the EQ predicate on the "input_tokens" field.
func InputTokensEQ(v int64) predicate.ModelCall {
	return predicate.ModelCall(sql.FieldEQ(FieldInputTokens, v))
}

// InputTokensNEQ applies the NEQ predicate on the "input_tokens" field.
func InputTokensNEQ(v int64) predicate.ModelCall {
	return predicate.ModelCall(sql.FieldNEQ(FieldInputTokens, v))
}

// InputTokensIn applies the In predicate on the "input_tokens" field.
func InputTokensIn(vs ...int64) predicate.ModelCall {
	return predicate.ModelCall(sql.FieldIn(FieldInputTokens, vs...))
}

// InputTokensNotIn applies the NotIn predicate on the "input_tokens" field.
func InputTokensNotIn(vs ...int64) predicate.ModelCall {
	return predicate.ModelCall(sql.FieldNotIn(FieldInputTokens, vs...))
}

// InputTokensGT applies the GT predicate on the "input_tokens" field.
func InputTokensGT(v int64) predicate.ModelCall {
	return predicate.ModelCall(sql.FieldGT(FieldInputTokens, v))
}

// InputTokensGTE applies the GTE predicate on the "input_tokens" field.
func InputTokensGTE(v int64) predicate.ModelCall {
	return predicate.ModelCall(sql.FieldGTE(FieldInputTokens, v))
}

// InputTokensLT applies the LT predicate on the "input_tokens" field.
func InputTokensLT(v int64) predicate.ModelCall {
	return predicate.ModelCall(sql.FieldLT(FieldInputTokens, v))
}

// InputTokensLTE applies the LTE predicate on the "input_tokens" field.
func InputTokensLTE(v int64) predicate.ModelCall {
	return predicate.ModelCall(sql.FieldLTE(FieldInputTokens, v))
}

// InputTokensIsNil applies the IsNil predicate on the "input_tokens" field.
func InputTokensIsNil() predicate.ModelCall {
	return predicate.ModelCall(sql.FieldIsNull(FieldInputTokens))
}

// InputTokensNotNil applies the NotNil predicate on the "input_tokens" field.
func InputTokensNotNil() predicate.ModelCall {
	return predicate.ModelCall(sql.FieldNotNull(FieldInputTokens))
}

// OutputTokensEQ applies the EQ predicate on the "output_tokens" field.
func OutputTokensEQ(v int64) predicate.ModelCall {
	return predicate.ModelCall(sql.FieldEQ(FieldOutputTokens, v))
}

// OutputTokensNEQ applies the NEQ predicate on the "output_tokens" field.
func OutputTokensNEQ(v int64) predicate.ModelCall {
	return predicate.ModelCall(sql.FieldNEQ(FieldOutputTokens, v))
}

// OutputTokensIn applies the In predicate on the "output_tokens" field.
func OutputTokensIn(vs ...int64) predicate.ModelCall {
	return predicate.ModelCall(sql.FieldIn(FieldOutputTokens, vs...))
}

// OutputTokensNotIn applies the NotIn predicate on the "output_tokens" field.
func OutputTokensNotIn(vs ...int64) predicate.ModelCall {
	return predicate.ModelCall(sql.FieldNotIn(FieldOutputTokens, vs...))
}

// OutputTokensGT applies the GT predicate on the "output_tokens" field.
func OutputTokensGT(v int64) predicate.ModelCall {
	return predicate.ModelCall(sql.FieldGT(FieldOutputTokens, v))
}

// OutputTokensGTE applies the GTE predicate on the "output_tokens" field.
func OutputTokensGTE(v int64) predicate.ModelCall {
	return predicate.ModelCall(sql.FieldGTE(FieldOutputTokens, v))
}

// OutputTokensLT applies the LT predicate on the "output_tokens" field.
func OutputTokensLT(v int64) predicate.ModelCall {
	return predicate.ModelCall(sql.FieldLT(FieldOutputTokens, v))
}

// OutputTokensLTE applies the LTE predicate on the "output_tokens" field.
func OutputTokensLTE(v int64) predicate.ModelCall {
	return predicate.ModelCall(sql.FieldLTE(FieldOutputTokens, v))
}

// OutputTokensIsNil applies the IsNil predicate on the "output_tokens" field.
func OutputTokensIsNil() predicate.ModelCall {
	return predicate.ModelCall(sql.FieldIsNull(FieldOutputTokens))
}

// OutputTokensNotNil applies the NotNil predicate on the "output_tokens" field.
func OutputTokensNotNil() predicate.ModelCall {
	return predicate.ModelCall(sql.FieldNotNull(FieldOutputTokens))
}

// TotalTokensEQ applies the EQ predicate on the "total_tokens" field.
func TotalTokensEQ(v int64) predicate.ModelCall {
	return predicate.ModelCall(sql.FieldEQ(FieldTotalTokens, v))
}

// TotalTokensNEQ applies the NEQ predicate on the "total_tokens" field.
func TotalTokensNEQ(v int64) predicate.ModelCall {
	return predicate.ModelCall(sql.FieldNEQ(FieldTotalTokens, v))
}

// TotalTokensIn applies the In predicate on the "total_tokens" field.
func TotalTokensIn(vs ...int64) predicate.ModelCall {
	return predicate.ModelCall(sql.FieldIn(FieldTotalTokens, vs...))
}

// TotalTokensNotIn applies the NotIn predicate on the "total_tokens" field.
func TotalTokensNotIn(vs ...int64) predicate.ModelCall {
	return predicate.ModelCall(sql.FieldNotIn(FieldTotalTokens, vs...))
}

// TotalTokensGT applies the GT predicate on the "total_tokens" field.
func TotalTokensGT(v int64) predicate.ModelCall {
	return predicate.ModelCall(sql.FieldGT(FieldTotalTokens, v))
}

// TotalTokensGTE applies the GTE predicate on the "total_tokens" field.
func TotalTokensGTE(v int64) predicate.ModelCall {
	return predicate.ModelCall(sql.FieldGTE(FieldTotalTokens, v))
}

// TotalTokensLT applies the LT predicate on the "total_tokens" field.
func TotalTokensLT(v int64) predicate.ModelCall {
	return predicate.ModelCall(sql.FieldLT(FieldTotalTokens, v))
}

// TotalTokensLTE applies the LTE predicate on the "total_tokens" field.
func TotalTokensLTE(v int64) predicate.ModelCall {
	return predicate.ModelCall(sql.FieldLTE(FieldTotalTokens, v))
}

// TotalTokensIsNil applies the IsNil predicate on the "total_tokens" field.
func TotalTokensIsNil() predicate.ModelCall {
	return predicate.ModelCall(sql.FieldIsNull(FieldTotalTokens))
}

// TotalTokensNotNil applies the NotNil predicate on the "total_tokens" field.
func TotalTokensNotNil() predicate.ModelCall {
	return predicate.ModelCall(sql.FieldNotNull(FieldTotalTokens))
}

// CachedTokensEQ applies the EQ predicate on the "cached_tokens" field.
func CachedTokensEQ(v int64) predicate.ModelCall {
	return predicate.ModelCall(sql.FieldEQ(FieldCachedTokens, v))
}

// CachedTokensNEQ applies the NEQ predicate on the "cached_tokens" field.
func CachedTokensNEQ(v int64) predicate.ModelCall {
	return predicate.ModelCall(sql.FieldNEQ(FieldCachedTokens, v))
}

// CachedTokensIn applies the In predicate on the "cached_tokens" field.
func CachedTokensIn(vs ...int64) predicate.ModelCall {
	return predicate.ModelCall(sql.FieldIn(FieldCachedTokens, vs...))
}

// CachedTokensNotIn applies the NotIn predicate on the "cached_tokens" field.
func CachedTokensNotIn(vs ...int64) predicate.ModelCall {
	return predicate.ModelCall(sql.FieldNotIn(FieldCachedTokens, vs...))
}

// CachedTokensGT applies the GT predicate on the "cached_tokens" field.
func CachedTokensGT(v int64) predicate.ModelCall {
	return predicate.ModelCall(sql.FieldGT(FieldCachedTokens, v))
}

// CachedTokensGTE applies the GTE predicate on the "cached_tokens" field.
func CachedTokensGTE(v int64) predicate.ModelCall {
	return predicate.ModelCall(sql.FieldGTE(FieldCachedTokens, v))
}

// CachedTokensLT applies the LT predicate on the "cached_tokens" field.
func CachedTokensLT(v int64) predicate.ModelCall {
	return predicate.ModelCall(sql.FieldLT(FieldCachedTokens, v))
}

// CachedTokensLTE applies the LTE predicate on the "cached_tokens" field.
func CachedTokensLTE(v int64) predicate.ModelCall {
	return predicate.ModelCall(sql.FieldLTE(FieldCachedTokens, v))
}

// CachedTokensIsNil applies the IsNil predicate on the "cached_tokens" field.
func CachedTokensIsNil() predicate.ModelCall {
	return predicate.ModelCall(sql.FieldIsNull(FieldCachedTokens))
}

// CachedTokensNotNil applies the NotNil predicate on the "cached_tokens" field.
func CachedTokensNotNil() predicate.ModelCall {
	return predicate.ModelCall(sql.FieldNotNull(FieldCachedTokens))
}

// ReasoningTokensEQ applies the EQ predicate on the "reasoning_tokens" field.
func ReasoningTokensEQ(v int64) predicate.ModelCall {
	return predicate.ModelCall(sql.FieldEQ(FieldReasoningTokens, v))
}

// ReasoningTokensNEQ applies the NEQ predicate on the "reasoning_tokens" field.
func ReasoningTokensNEQ(v int64) predicate.ModelCall {
	return predicate.ModelCall(sql.FieldNEQ(FieldReasoningTokens, v))
}

// ReasoningTokensIn applies the In predicate on the "reasoning_tokens" field.
func ReasoningTokensIn(vs ...int64) predicate.ModelCall {
	return predicate.ModelCall(sql.FieldIn(FieldReasoningTokens, vs...))
}

// ReasoningTokensNotIn applies the NotIn predicate on the "reasoning_tokens" field.
func ReasoningTokensNotIn(vs ...int64) predicate.ModelCall {
	return predicate.ModelCall(sql.FieldNotIn(FieldReasoningTokens, vs...))
}

// ReasoningTokensGT applies the GT predicate on the "reasoning_tokens" field.
func ReasoningTokensGT(v int64) predicate.ModelCall {
	return predicate.ModelCall(sql.FieldGT(FieldReasoningTokens, v))
}

// ReasoningTokensGTE applies the GTE predicate on the "reasoning_tokens" field.
func ReasoningTokensGTE(v int64) predicate.ModelCall {
	return predicate.ModelCall(sql.FieldGTE(FieldReasoningTokens, v))
}

// ReasoningTokensLT applies the LT predicate on the "reasoning_tokens" field.
func ReasoningTokensLT(v int64) predicate.ModelCall {
	return predicate.ModelCall(sql.FieldLT(FieldReasoningTokens, v))
}

// ReasoningTokensLTE applies the LTE predicate on the "reasoning_tokens" field.
func ReasoningTokensLTE(v int64) predicate.ModelCall {
	return predicate.ModelCall(sql.FieldLTE(FieldReasoningTokens, v))
}

// ReasoningTokensIsNil applies the IsNil predicate on the "reasoning_tokens" field.
func ReasoningTokensIsNil() predicate.ModelCall {
	return predicate.ModelCall(sql.FieldIsNull(FieldReasoningTokens))
}

// ReasoningTokensNotNil applies the NotNil predicate on the "reasoning_tokens" field.
func ReasoningTokensNotNil() predicate.ModelCall {
	return predicate.ModelCall(sql.FieldNotNull(FieldReasoningTokens))
}

// ImageCountEQ applies the EQ predicate on the "image_count" field.
func ImageCountEQ(v int) predicate.ModelCall {
	return predicate.ModelCall(sql.FieldEQ(FieldImageCount, v))
}

// ImageCountNEQ applies the NEQ predicate on the "image_count" field.
func ImageCountNEQ(v int) predicate.ModelCall {
	return predicate.ModelCall(sql.FieldNEQ(FieldImageCount, v))
}

// ImageCountIn applies the In predicate on the "image_count" field.
func ImageCountIn(vs ...int) predicate.ModelCall {
	return predicate.ModelCall(sql.FieldIn(FieldImageCount, vs...))
}

// ImageCountNotIn applies the NotIn predicate on the "image_count" field.
func ImageCountNotIn(vs ...int) predicate.ModelCall {
	return predicate.ModelCall(sql.FieldNotIn(FieldImageCount, vs...))
}

// ImageCountGT applies the GT predicate on the "image_count" field.
func ImageCountGT(v int) predicate.ModelCall {
	return predicate.ModelCall(sql.FieldGT(FieldImageCount, v))
}

// ImageCountGTE applies the GTE predicate on the "image_count" field.
func ImageCountGTE(v int) predicate.ModelCall {
	return predicate.ModelCall(sql.FieldGTE(FieldImageCount, v))
}

// ImageCountLT applies the LT predicate on the "image_count" field.
func ImageCountLT(v int) predicate.ModelCall {
	return predicate.ModelCall(sql.FieldLT(FieldImageCount, v))
}

// ImageCountLTE applies the LTE predicate on the "image_count" field.
func ImageCountLTE(v int) predicate.ModelCall {
	return predicate.ModelCall(sql.FieldLTE(FieldImageCount, v))
}

// ImageCountIsNil applies the IsNil predicate on the "image_count" field.
func ImageCountIsNil() predicate.ModelCall {
	return predicate.ModelCall(sql.FieldIsNull(FieldImageCount))
}

// ImageCountNotNil applies the NotNil predicate on the "image_count" field.
func ImageCountNotNil() predicate.ModelCall {
	return predicate.ModelCall(sql.FieldNotNull(FieldImageCount))
}

// ImageSizeEQ applies the EQ predicate on the "image_size" field.
func ImageSizeEQ(v string) predicate.ModelCall {
	return predicate.ModelCall(sql.FieldEQ(FieldImageSize, v))
}

// ImageSizeNEQ applies the NEQ predicate on the "image_size" field.
func ImageSizeNEQ(v string) predicate.ModelCall {
	return predicate.ModelCall(sql.FieldNEQ(FieldImageSize, v))
}

// ImageSizeIn applies the In predicate on the "image_size" field.
func ImageSizeIn(vs ...string) predicate.ModelCall {
	return predicate.ModelCall(sql.FieldIn(FieldImageSize, vs...))
}

// ImageSizeNotIn applies the NotIn predicate on the "image_size" field.
func ImageSizeNotIn(vs ...string) predicate.ModelCall {
	return predicate.ModelCall(sql.FieldNotIn(FieldImageSize, vs...))
}

// ImageSizeGT applies the GT predicate on the "image_size" field.
func ImageSizeGT(v string) predicate.ModelCall {
	return predicate.ModelCall(sql.FieldGT(FieldImageSize, v))
}

// ImageSizeGTE applies the GTE predicate on the "image_size" field.
func ImageSizeGTE(v string) predicate.ModelCall {
	return predicate.ModelCall(sql.FieldGTE(FieldImageSize, v))
}

// ImageSizeLT applies the LT predicate on the "image_size" field.
func ImageSizeLT(v string) predicate.ModelCall {
	return predicate.ModelCall(sql.FieldLT(FieldImageSize, v))
}

// ImageSizeLTE applies the LTE predicate on the "image_size" field.
func ImageSizeLTE(v string) predicate.ModelCall {
	return predicate.ModelCall(sql.FieldLTE(FieldImageSize, v))
}

// ImageSizeContains applies the Contains predicate on the "image_size" field.
func ImageSizeContains(v string) predicate.ModelCall {
	return predicate.ModelCall(sql.FieldContains(FieldImageSize, v))
}

// ImageSizeHasPrefix applies the HasPrefix predicate on the "image_size" field.
func ImageSizeHasPrefix(v string) predicate.ModelCall {
	return predicate.ModelCall(sql.FieldHasPrefix(FieldImageSize, v))
}

// ImageSizeHasSuffix applies the HasSuffix predicate on the "image_size" field.
func ImageSizeHasSuffix(v string) predicate.ModelCall {
	return predicate.ModelCall(sql.FieldHasSuffix(FieldImageSize, v))
}

// ImageSizeEqualFold applies the EqualFold predicate on the "image_size" field.
func ImageSizeEqualFold(v string) predicate.ModelCall {
	return predicate.ModelCall(sql.FieldEqualFold(FieldImageSize, v))
}

// ImageSizeContainsFold applies the ContainsFold predicate on the "image_size" field.
func ImageSizeContainsFold(v string) predicate.ModelCall {
	return predicate.ModelCall(sql.FieldContainsFold(FieldImageSize, v))
}

// ImageAspectRatioEQ applies the EQ predicate on the "image_aspect_ratio" field.
func ImageAspectRatioEQ(v string) predicate.ModelCall {
	return predicate.ModelCall(sql.FieldEQ(FieldImageAspectRatio, v))
}

// ImageAspectRatioNEQ applies the NEQ predicate on the "image_aspect_ratio" field.
func ImageAspectRatioNEQ(v string) predicate.ModelCall {
	return predicate.ModelCall(sql.FieldNEQ(FieldImageAspectRatio, v))
}

// ImageAspectRatioIn applies the In predicate on the "image_aspect_ratio" field.
func ImageAspectRatioIn(vs ...string) predicate.ModelCall {
	return predicate.ModelCall(sql.FieldIn(FieldImageAspectRatio, vs...))
}

// ImageAspectRatioNotIn applies the NotIn predicate on the "image_aspect_ratio" field.
func ImageAspectRatioNotIn(vs ...string) predicate.ModelCall {
	return predicate.ModelCall(sql.FieldNotIn(FieldImageAspectRatio, vs...))
}

// ImageAspectRatioGT applies the GT predicate on the "image_aspect_ratio" field.
func ImageAspectRatioGT(v string) predicate.ModelCall {
	return predicate.ModelCall(sql.FieldGT(FieldImageAspectRatio, v))
}

// ImageAspectRatioGTE applies the GTE predicate on the "image_aspect_ratio" field.
func ImageAspectRatioGTE(v string) predicate.ModelCall {
	return predicate.ModelCall(sql.FieldGTE(FieldImageAspectRatio, v))
}

// ImageAspectRatioLT applies the LT predicate on the "image_aspect_ratio" field.
func ImageAspectRatioLT(v string) predicate.ModelCall {
	return predicate.ModelCall(sql.FieldLT(FieldImageAspectRatio, v))
}

// ImageAspectRatioLTE applies the LTE predicate on the "image_aspect_ratio" field.
func ImageAspectRatioLTE(v string) predicate.ModelCall {
	return predicate.ModelCall(sql.FieldLTE(FieldImageAspectRatio, v))
}

// ImageAspectRatioContains applies the Contains predicate on the "image_aspect_ratio" field.
func ImageAspectRatioContains(v string) predicate.ModelCall {
	return predicate.ModelCall(sql.FieldContains(FieldImageAspectRatio, v))
}

// ImageAspectRatioHasPrefix applies the HasPrefix predicate on the "image_aspect_ratio" field.
func ImageAspectRatioHasPrefix(v string) predicate.ModelCall {
	return predicate.ModelCall(sql.FieldHasPrefix(FieldImageAspectRatio, v))
}

// ImageAspectRatioHasSuffix applies the HasSuffix predicate on the "image_aspect_ratio" field.
func ImageAspectRatioHasSuffix(v string) predicate.ModelCall {
	return predicate.ModelCall(sql.FieldHasSuffix(FieldImageAspectRatio, v))
}

// ImageAspectRatioEqualFold applies the EqualFold predicate on the "image_aspect_ratio" field.
func ImageAspectRatioEqualFold(v string) predicate.ModelCall {
	return predicate.ModelCall(sql.FieldEqualFold(FieldImageAspectRatio, v))
}

// ImageAspectRatioContainsFold applies the ContainsFold predicate on the "image_aspect_ratio" field.
func ImageAspectRatioContainsFold(v string) predicate.ModelCall {
	return predicate.ModelCall(sql.FieldContainsFold(FieldImageAspectRatio, v))
}

// VideoCountEQ applies the EQ predicate on the "video_count" field.
func VideoCountEQ(v int) predicate.ModelCall {
	return predicate.ModelCall(sql.FieldEQ(FieldVideoCount, v))
}

// VideoCountNEQ applies the NEQ predicate on the "video_count" field.
func VideoCountNEQ(v int) predicate.ModelCall {
	return predicate.ModelCall(sql.FieldNEQ(FieldVideoCount, v))
}

// VideoCountIn applies the In predicate on the "video_count" field.
func VideoCountIn(vs ...int) predicate.ModelCall {
	return predicate.ModelCall(sql.FieldIn(FieldVideoCount, vs...))
}

// VideoCountNotIn applies the NotIn predicate on the "video_count" field.
func VideoCountNotIn(vs ...int) predicate.ModelCall {
	return predicate.ModelCall(sql.FieldNotIn(FieldVideoCount, vs...))
}

// VideoCountGT applies the GT predicate on the "video_count" field.
func VideoCountGT(v int) predicate.ModelCall {
	return predicate.ModelCall(sql.FieldGT(FieldVideoCount, v))
}

// VideoCountGTE applies the GTE predicate on the "video_count" field.
func VideoCountGTE(v int) predicate.ModelCall {
	return predicate.ModelCall(sql.FieldGTE(FieldVideoCount, v))
}

// VideoCountLT applies the LT predicate on the "video_count" field.
func VideoCountLT(v int) predicate.ModelCall {
	return predicate.ModelCall(sql.FieldLT(FieldVideoCount, v))
}

// VideoCountLTE applies the LTE predicate on the "video_count" field.
func VideoCountLTE(v int) predicate.ModelCall {
	return predicate.ModelCall(sql.FieldLTE(FieldVideoCount, v))
}

// VideoCountIsNil applies the IsNil predicate on the "video_count" field.
func VideoCountIsNil() predicate.ModelCall {
	return predicate.ModelCall(sql.FieldIsNull(FieldVideoCount))
}

// VideoCountNotNil applies the NotNil predicate on the "video_count" field.
func VideoCountNotNil() predicate.ModelCall {
	return predicate.ModelCall(sql.FieldNotNull(FieldVideoCount))
}

// VideoResolutionEQ applies the EQ predicate on the "video_resolution" field.
func VideoResolutionEQ(v string) predicate.ModelCall {
	return predicate.ModelCall(sql.FieldEQ(FieldVideoResolution, v))
}

// VideoResolutionNEQ applies the NEQ predicate on the "video_resolution" field.
func VideoResolutionNEQ(v string) predicate.ModelCall {
	return predicate.ModelCall(sql.FieldNEQ(FieldVideoResolution, v))
}

// VideoResolutionIn applies the In predicate on the "video_resolution" field.
func VideoResolutionIn(vs ...string) predicate.ModelCall {
	return predicate.ModelCall(sql.FieldIn(FieldVideoResolution, vs...))
}

// VideoResolutionNotIn applies the NotIn predicate on the "video_resolution" field.
func VideoResolutionNotIn(vs ...string) predicate.ModelCall {
	return predicate.ModelCall(sql.FieldNotIn(FieldVideoResolution, vs...))
}

// VideoResolutionGT applies the GT predicate on the "video_resolution" field.
func VideoResolutionGT(v string) predicate.ModelCall {
	return predicate.ModelCall(sql.FieldGT(FieldVideoResolution, v))
}

// VideoResolutionGTE applies the GTE predicate on the "video_resolution" field.
func VideoResolutionGTE(v string) predicate.ModelCall {
	return predicate.ModelCall(sql.FieldGTE(FieldVideoResolution, v))
}

// VideoResolutionLT applies the LT predicate on the "video_resolution" field.
func VideoResolutionLT(v string) predicate.ModelCall {
	return predicate.ModelCall(sql.FieldLT(FieldVideoResolution, v))
}

// VideoResolutionLTE applies the LTE predicate on the "video_resolution" field.
func VideoResolutionLTE(v string) predicate.ModelCall {
	return predicate.ModelCall(sql.FieldLTE(FieldVideoResolution, v))
}

// VideoResolutionContains applies the Contains predicate on the "video_resolution" field.
func VideoResolutionContains(v string) predicate.ModelCall {
	return predicate.ModelCall(sql.FieldContains(FieldVideoResolution, v))
}

// VideoResolutionHasPrefix applies the HasPrefix predicate on the "video_resolution" field.
func VideoResolutionHasPrefix(v string) predicate.ModelCall {
	return predicate.ModelCall(sql.FieldHasPrefix(FieldVideoResolution, v))
}

// VideoResolutionHasSuffix applies the HasSuffix predicate on the "video_resolution" field.
func VideoResolutionHasSuffix(v string) predicate.ModelCall {
	return predicate.ModelCall(sql.FieldHasSuffix(FieldVideoResolution, v))
}

// VideoResolutionEqualFold applies the EqualFold predicate on the "video_resolution" field.
func VideoResolutionEqualFold(v string) predicate.ModelCall {
	return predicate.ModelCall(sql.FieldEqualFold(FieldVideoResolution, v))
}

// VideoResolutionContainsFold applies the ContainsFold predicate on the "video_resolution" field.
func VideoResolutionContainsFold(v string) predicate.ModelCall {
	return predicate.ModelCall(sql.FieldContainsFold(FieldVideoResolution, v))
}

// VideoDurationSecondsEQ applies the EQ predicate on the "video_duration_seconds" field.
func VideoDurationSecondsEQ(v int) predicate.ModelCall {
	return predicate.ModelCall(sql.FieldEQ(FieldVideoDurationSeconds, v))
}

// VideoDurationSecondsNEQ applies the NEQ predicate on the "video_duration_seconds" field.
func VideoDurationSecondsNEQ(v int) predicate.ModelCall {
	return predicate.ModelCall(sql.FieldNEQ(FieldVideoDurationSeconds, v))
}

// VideoDurationSecondsIn applies the In predicate on the "video_duration_seconds" field.
func VideoDurationSecondsIn(vs ...int) predicate.ModelCall {
	return predicate.ModelCall(sql.FieldIn(FieldVideoDurationSeconds, vs...))
}

// VideoDurationSecondsNotIn applies the NotIn predicate on the "video_duration_seconds" field.
func VideoDurationSecondsNotIn(vs ...int) predicate.ModelCall {
	return predicate.ModelCall(sql.FieldNotIn(FieldVideoDurationSeconds, vs...))
}

// VideoDurationSecondsGT applies the GT predicate on the "video_duration_seconds" field.
func VideoDurationSecondsGT(v int) predicate.ModelCall {
	return predicate.ModelCall(sql.FieldGT(FieldVideoDurationSeconds, v))
}

// VideoDurationSecondsGTE applies the GTE predicate on the "video_duration_seconds" field.
func VideoDurationSecondsGTE(v int) predicate.ModelCall {
	return predicate.ModelCall(sql.FieldGTE(FieldVideoDurationSeconds, v))
}

// VideoDurationSecondsLT applies the LT predicate on the "video_duration_seconds" field.
func VideoDurationSecondsLT(v int) predicate.ModelCall {
	return predicate.ModelCall(sql.FieldLT(FieldVideoDurationSeconds, v))
}

// VideoDurationSecondsLTE applies the LTE predicate on the "video_duration_seconds" field.
func VideoDurationSecondsLTE(v int) predicate.ModelCall {
	return predicate.ModelCall(sql.FieldLTE(FieldVideoDurationSeconds, v))
}

// VideoDurationSecondsIsNil applies the IsNil predicate on the "video_duration_seconds" field.
func VideoDurationSecondsIsNil() predicate.ModelCall {
	return predicate.ModelCall(sql.FieldIsNull(FieldVideoDurationSeconds))
}

// VideoDurationSecondsNotNil applies the NotNil predicate on the "video_duration_seconds" field.
func VideoDurationSecondsNotNil() predicate.ModelCall {
	return predicate.ModelCall(sql.FieldNotNull(FieldVideoDurationSeconds))
}

// VideoAspectRatioEQ applies the EQ predicate on the "video_aspect_ratio" field.
func VideoAspectRatioEQ(v string) predicate.ModelCall {
	return predicate.ModelCall(sql.FieldEQ(FieldVideoAspectRatio, v))
}

// VideoAspectRatioNEQ applies the NEQ predicate on the "video_aspect_ratio" field.
func VideoAspectRatioNEQ(v string) predicate.ModelCall {
	return predicate.ModelCall(sql.FieldNEQ(FieldVideoAspectRatio, v))
}

// VideoAspectRatioIn applies the In predicate on the "video_aspect_ratio" field.
func VideoAspectRatioIn(vs ...string) predicate.ModelCall {
	return predicate.ModelCall(sql.FieldIn(FieldVideoAspectRatio, vs...))
}

// VideoAspectRatioNotIn applies the NotIn predicate on the "video_aspect_ratio" field.
func VideoAspectRatioNotIn(vs ...string) predicate.ModelCall {
	return predicate.ModelCall(sql.FieldNotIn(FieldVideoAspectRatio, vs...))
}

// VideoAspectRatioGT applies the GT predicate on the "video_aspect_ratio" field.
func VideoAspectRatioGT(v string) predicate.ModelCall {
	return predicate.ModelCall(sql.FieldGT(FieldVideoAspectRatio, v))
}

// VideoAspectRatioGTE applies the GTE predicate on the "video_aspect_ratio" field.
func VideoAspectRatioGTE(v string) predicate.ModelCall {
	return predicate.ModelCall(sql.FieldGTE(FieldVideoAspectRatio, v))
}

// VideoAspectRatioLT applies the LT predicate on the "video_aspect_ratio" field.
func VideoAspectRatioLT(v string) predicate.ModelCall {
	return predicate.ModelCall(sql.FieldLT(FieldVideoAspectRatio, v))
}

// VideoAspectRatioLTE applies the LTE predicate on the "video_aspect_ratio" field.
func VideoAspectRatioLTE(v string) predicate.ModelCall {
	return predicate.ModelCall(sql.FieldLTE(FieldVideoAspectRatio, v))
}

// VideoAspectRatioContains applies the Contains predicate on the "video_aspect_ratio" field.
func VideoAspectRatioContains(v string) predicate.ModelCall {
	return predicate.ModelCall(sql.FieldContains(FieldVideoAspectRatio, v))
}

// VideoAspectRatioHasPrefix applies the HasPrefix predicate on the "video_aspect_ratio" field.
func VideoAspectRatioHasPrefix(v string) predicate.ModelCall {
	return predicate.ModelCall(sql.FieldHasPrefix(FieldVideoAspectRatio, v))
}

// VideoAspectRatioHasSuffix applies the HasSuffix predicate on the "video_aspect_ratio" field.
func VideoAspectRatioHasSuffix(v string) predicate.ModelCall {
	return predicate.ModelCall(sql.FieldHasSuffix(FieldVideoAspectRatio, v))
}

// VideoAspectRatioEqualFold applies the EqualFold predicate on the "video_aspect_ratio" field.
func VideoAspectRatioEqualFold(v string) predicate.ModelCall {
	return predicate.ModelCall(sql.FieldEqualFold(FieldVideoAspectRatio, v))
}

// VideoAspectRatioContainsFold applies the ContainsFold predicate on the "video_aspect_ratio" field.
func VideoAspectRatioContainsFold(v string) predicate.ModelCall {
	return predicate.ModelCall(sql.FieldContainsFold(FieldVideoAspectRatio, v))
}

// LatencyMsEQ applies the EQ predicate on the "latency_ms" field.
func LatencyMsEQ(v int64) predicate.ModelCall {
	return predicate.ModelCall(sql.FieldEQ(FieldLatencyMs, v))
}

// LatencyMsNEQ applies the NEQ predicate on the "latency_ms" field.
func LatencyMsNEQ(v int64) predicate.ModelCall {
	return predicate.ModelCall(sql.FieldNEQ(FieldLatencyMs, v))
}

// LatencyMsIn applies the In predicate on the "latency_ms" field.
func LatencyMsIn(vs ...int64) predicate.ModelCall {
	return predicate.ModelCall(sql.FieldIn(FieldLatencyMs, vs...))
}

// LatencyMsNotIn applies the NotIn predicate on the "latency_ms" field.
func LatencyMsNotIn(vs ...int64) predicate.ModelCall {
	return predicate.ModelCall(sql.FieldNotIn(FieldLatencyMs, vs...))
}

// LatencyMsGT applies the GT predicate on the "latency_ms" field.
func LatencyMsGT(v int64) predicate.ModelCall {
	return predicate.ModelCall(sql.FieldGT(FieldLatencyMs, v))
}

// LatencyMsGTE applies the GTE predicate on the "latency_ms" field.
func LatencyMsGTE(v int64) predicate.ModelCall {
	return predicate.ModelCall(sql.FieldGTE(FieldLatencyMs, v))
}

// LatencyMsLT applies the LT predicate on the "latency_ms" field.
func LatencyMsLT(v int64) predicate.ModelCall {
	return predicate.ModelCall(sql.FieldLT(FieldLatencyMs, v))
}

// LatencyMsLTE applies the LTE predicate on the "latency_ms" field.
func LatencyMsLTE(v int64) predicate.ModelCall {
	return predicate.ModelCall(sql.FieldLTE(FieldLatencyMs, v))
}

// StartedAtEQ applies the EQ predicate on the "started_at" field.
func StartedAtEQ(v time.Time) predicate.ModelCall {
	return predicate.ModelCall(sql.FieldEQ(FieldStartedAt, v))
}

// StartedAtNEQ applies the NEQ predicate on the "started_at" field.
func StartedAtNEQ(v time.Time) predicate.ModelCall {
	return predicate.ModelCall(sql.FieldNEQ(FieldStartedAt, v))
}

// StartedAtIn applies the In predicate on the "started_at" field.
func StartedAtIn(vs ...time.Time) predicate.ModelCall {
	return predicate.ModelCall(sql.FieldIn(FieldStartedAt, vs...))
}

// StartedAtNotIn applies the NotIn predicate on the "started_at" field.
func StartedAtNotIn(vs ...time.Time) predicate.ModelCall {
	return predicate.ModelCall(sql.FieldNotIn(FieldStartedAt, vs...))
}

// StartedAtGT applies the GT predicate on the "started_at" field.
func StartedAtGT(v time.Time) predicate.ModelCall {
	return predicate.ModelCall(sql.FieldGT(FieldStartedAt, v))
}

// StartedAtGTE applies the GTE predicate on the "started_at" field.
func StartedAtGTE(v time.Time) predicate.ModelCall {
	return predicate.ModelCall(sql.FieldGTE(FieldStartedAt, v))
}

// StartedAtLT applies the LT predicate on the "started_at" field.
func StartedAtLT(v time.Time) predicate.ModelCall {
	return predicate.ModelCall(sql.FieldLT(FieldStartedAt, v))
}

// StartedAtLTE applies the LTE predicate on the "started_at" field.
func StartedAtLTE(v time.Time) predicate.ModelCall {
	return predicate.ModelCall(sql.FieldLTE(FieldStartedAt, v))
}

// FinishedAtEQ applies the EQ predicate on the "finished_at" field.
func FinishedAtEQ(v time.Time) predicate.ModelCall {
	return predicate.ModelCall(sql.FieldEQ(FieldFinishedAt, v))
}

// FinishedAtNEQ applies the NEQ predicate on the "finished_at" field.
func FinishedAtNEQ(v time.Time) predicate.ModelCall {
	return predicate.ModelCall(sql.FieldNEQ(FieldFinishedAt, v))
}

// FinishedAtIn applies the In predicate on the "finished_at" field.
func FinishedAtIn(vs ...time.Time) predicate.ModelCall {
	return predicate.ModelCall(sql.FieldIn(FieldFinishedAt, vs...))
}

// FinishedAtNotIn applies the NotIn predicate on the "finished_at" field.
func FinishedAtNotIn(vs ...time.Time) predicate.ModelCall {
	return predicate.ModelCall(sql.FieldNotIn(FieldFinishedAt, vs...))
}

// FinishedAtGT applies the GT predicate on the "finished_at" field.
func FinishedAtGT(v time.Time) predicate.ModelCall {
	return predicate.ModelCall(sql.FieldGT(FieldFinishedAt, v))
}

// FinishedAtGTE applies the GTE predicate on the "finished_at" field.
func FinishedAtGTE(v time.Time) predicate.ModelCall {
	return predicate.ModelCall(sql.FieldGTE(FieldFinishedAt, v))
}

// FinishedAtLT applies the LT predicate on the "finished_at" field.
func FinishedAtLT(v time.Time) predicate.ModelCall {
	return predicate.ModelCall(sql.FieldLT(FieldFinishedAt, v))
}

// FinishedAtLTE applies the LTE predicate on the "finished_at" field.
func FinishedAtLTE(v time.Time) predicate.ModelCall {
	return predicate.ModelCall(sql.FieldLTE(FieldFinishedAt, v))
}

// FinishedAtIsNil applies the IsNil predicate on the "finished_at" field.
func FinishedAtIsNil() predicate.ModelCall {
	return predicate.ModelCall(sql.FieldIsNull(FieldFinishedAt))
}

// FinishedAtNotNil applies the NotNil predicate on the "finished_at" field.
func FinishedAtNotNil() predicate.ModelCall {
	return predicate.ModelCall(sql.FieldNotNull(FieldFinishedAt))
}

// CreatedAtEQ applies the EQ predicate on the "created_at" field.
func CreatedAtEQ(v time.Time) predicate.ModelCall {
	return predicate.ModelCall(sql.FieldEQ(FieldCreatedAt, v))
}

// CreatedAtNEQ applies the NEQ predicate on the "created_at" field.
func CreatedAtNEQ(v time.Time) predicate.ModelCall {
	return predicate.ModelCall(sql.FieldNEQ(FieldCreatedAt, v))
}

// CreatedAtIn applies the In predicate on the "created_at" field.
func CreatedAtIn(vs ...time.Time) predicate.ModelCall {
	return predicate.ModelCall(sql.FieldIn(FieldCreatedAt, vs...))
}

// CreatedAtNotIn applies the NotIn predicate on the "created_at" field.
func CreatedAtNotIn(vs ...time.Time) predicate.ModelCall {
	return predicate.ModelCall(sql.FieldNotIn(FieldCreatedAt, vs...))
}

// CreatedAtGT applies the GT predicate on the "created_at" field.
func CreatedAtGT(v time.Time) predicate.ModelCall {
	return predicate.ModelCall(sql.FieldGT(FieldCreatedAt, v))
}

// CreatedAtGTE applies the GTE predicate on the "created_at" field.
func CreatedAtGTE(v time.Time) predicate.ModelCall {
	return predicate.ModelCall(sql.FieldGTE(FieldCreatedAt, v))
}

// CreatedAtLT applies the LT predicate on the "created_at" field.
func CreatedAtLT(v time.Time) predicate.ModelCall {
	return predicate.ModelCall(sql.FieldLT(FieldCreatedAt, v))
}

// CreatedAtLTE applies the LTE predicate on the "created_at" field.
func CreatedAtLTE(v time.Time) predicate.ModelCall {
	return predicate.ModelCall(sql.FieldLTE(FieldCreatedAt, v))
}

// UpdatedAtEQ applies the EQ predicate on the "updated_at" field.
func UpdatedAtEQ(v time.Time) predicate.ModelCall {
	return predicate.ModelCall(sql.FieldEQ(FieldUpdatedAt, v))
}

// UpdatedAtNEQ applies the NEQ predicate on the "updated_at" field.
func UpdatedAtNEQ(v time.Time) predicate.ModelCall {
	return predicate.ModelCall(sql.FieldNEQ(FieldUpdatedAt, v))
}

// UpdatedAtIn applies the In predicate on the "updated_at" field.
func UpdatedAtIn(vs ...time.Time) predicate.ModelCall {
	return predicate.ModelCall(sql.FieldIn(FieldUpdatedAt, vs...))
}

// UpdatedAtNotIn applies the NotIn predicate on the "updated_at" field.
func UpdatedAtNotIn(vs ...time.Time) predicate.ModelCall {
	return predicate.ModelCall(sql.FieldNotIn(FieldUpdatedAt, vs...))
}

// UpdatedAtGT applies the GT predicate on the "updated_at" field.
func UpdatedAtGT(v time.Time) predicate.ModelCall {
	return predicate.ModelCall(sql.FieldGT(FieldUpdatedAt, v))
}

// UpdatedAtGTE applies the GTE predicate on the "updated_at" field.
func UpdatedAtGTE(v time.Time) predicate.ModelCall {
	return predicate.ModelCall(sql.FieldGTE(FieldUpdatedAt, v))
}

// UpdatedAtLT applies the LT predicate on the "updated_at" field.
func UpdatedAtLT(v time.Time) predicate.ModelCall {
	return predicate.ModelCall(sql.FieldLT(FieldUpdatedAt, v))
}

// UpdatedAtLTE applies the LTE predicate on the "updated_at" field.
func UpdatedAtLTE(v time.Time) predicate.ModelCall {
	return predicate.ModelCall(sql.FieldLTE(FieldUpdatedAt, v))
}

// And groups predicates with the AND operator between them.
func And(predicates ...predicate.ModelCall) predicate.ModelCall {
	return predicate.ModelCall(sql.AndPredicates(predicates...))
}

// Or groups predicates with the OR operator between them.
func Or(predicates ...predicate.ModelCall) predicate.ModelCall {
	return predicate.ModelCall(sql.OrPredicates(predicates...))
}

// Not applies the not operator on the given predicate.
func Not(p predicate.ModelCall) predicate.ModelCall {
	return predicate.ModelCall(sql.NotPredicates(p))
}
