// Code generated by ent, DO NOT EDIT.

package modelhubapikey

import (
	"time"

	"entgo.io/ent/dialect/sql"
	"github.com/wgdl666/wgModelHub/ent/predicate"
)

// ID filters vertices based on their ID field.
func ID(id string) predicate.ModelhubAPIKey {
	return predicate.ModelhubAPIKey(sql.FieldEQ(FieldID, id))
}

// IDEQ applies the EQ predicate on the ID field.
func IDEQ(id string) predicate.ModelhubAPIKey {
	return predicate.ModelhubAPIKey(sql.FieldEQ(FieldID, id))
}

// IDNEQ applies the NEQ predicate on the ID field.
func IDNEQ(id string) predicate.ModelhubAPIKey {
	return predicate.ModelhubAPIKey(sql.FieldNEQ(FieldID, id))
}

// IDIn applies the In predicate on the ID field.
func IDIn(ids ...string) predicate.ModelhubAPIKey {
	return predicate.ModelhubAPIKey(sql.FieldIn(FieldID, ids...))
}

// IDNotIn applies the NotIn predicate on the ID field.
func IDNotIn(ids ...string) predicate.ModelhubAPIKey {
	return predicate.ModelhubAPIKey(sql.FieldNotIn(FieldID, ids...))
}

// IDGT applies the GT predicate on the ID field.
func IDGT(id string) predicate.ModelhubAPIKey {
	return predicate.ModelhubAPIKey(sql.FieldGT(FieldID, id))
}

// IDGTE applies the GTE predicate on the ID field.
func IDGTE(id string) predicate.ModelhubAPIKey {
	return predicate.ModelhubAPIKey(sql.FieldGTE(FieldID, id))
}

// IDLT applies the LT predicate on the ID field.
func IDLT(id string) predicate.ModelhubAPIKey {
	return predicate.ModelhubAPIKey(sql.FieldLT(FieldID, id))
}

// IDLTE applies the LTE predicate on the ID field.
func IDLTE(id string) predicate.ModelhubAPIKey {
	return predicate.ModelhubAPIKey(sql.FieldLTE(FieldID, id))
}

// IDEqualFold applies the EqualFold predicate on the ID field.
func IDEqualFold(id string) predicate.ModelhubAPIKey {
	return predicate.ModelhubAPIKey(sql.FieldEqualFold(FieldID, id))
}

// IDContainsFold applies the ContainsFold predicate on the ID field.
func IDContainsFold(id string) predicate.ModelhubAPIKey {
	return predicate.ModelhubAPIKey(sql.FieldContainsFold(FieldID, id))
}

// PrincipalID applies equality check predicate on the "principal_id" field. It's identical to PrincipalIDEQ.
func PrincipalID(v string) predicate.ModelhubAPIKey {
	return predicate.ModelhubAPIKey(sql.FieldEQ(FieldPrincipalID, v))
}

// KeyID applies equality check predicate on the "key_id" field. It's identical to KeyIDEQ.
func KeyID(v string) predicate.ModelhubAPIKey {
	return predicate.ModelhubAPIKey(sql.FieldEQ(FieldKeyID, v))
}

// SecretSha256 applies equality check predicate on the "secret_sha256" field. It's identical to SecretSha256EQ.
func SecretSha256(v string) predicate.ModelhubAPIKey {
	return predicate.ModelhubAPIKey(sql.FieldEQ(FieldSecretSha256, v))
}

// Name applies equality check predicate on the "name" field. It's identical to NameEQ.
func Name(v string) predicate.ModelhubAPIKey {
	return predicate.ModelhubAPIKey(sql.FieldEQ(FieldName, v))
}

// CreatedBy applies equality check predicate on the "created_by" field. It's identical to CreatedByEQ.
func CreatedBy(v string) predicate.ModelhubAPIKey {
	return predicate.ModelhubAPIKey(sql.FieldEQ(FieldCreatedBy, v))
}

// CreatedAt applies equality check predicate on the "created_at" field. It's identical to CreatedAtEQ.
func CreatedAt(v time.Time) predicate.ModelhubAPIKey {
	return predicate.ModelhubAPIKey(sql.FieldEQ(FieldCreatedAt, v))
}

// ExpiresAt applies equality check predicate on the "expires_at" field. It's identical to ExpiresAtEQ.
func ExpiresAt(v time.Time) predicate.ModelhubAPIKey {
	return predicate.ModelhubAPIKey(sql.FieldEQ(FieldExpiresAt, v))
}

// RevokedAt applies equality check predicate on the "revoked_at" field. It's identical to RevokedAtEQ.
func RevokedAt(v time.Time) predicate.ModelhubAPIKey {
	return predicate.ModelhubAPIKey(sql.FieldEQ(FieldRevokedAt, v))
}

// PrincipalIDEQ applies the EQ predicate on the "principal_id" field.
func PrincipalIDEQ(v string) predicate.ModelhubAPIKey {
	return predicate.ModelhubAPIKey(sql.FieldEQ(FieldPrincipalID, v))
}

// PrincipalIDNEQ applies the NEQ predicate on the "principal_id" field.
func PrincipalIDNEQ(v string) predicate.ModelhubAPIKey {
	return predicate.ModelhubAPIKey(sql.FieldNEQ(FieldPrincipalID, v))
}

// PrincipalIDIn applies the In predicate on the "principal_id" field.
func PrincipalIDIn(vs ...string) predicate.ModelhubAPIKey {
	return predicate.ModelhubAPIKey(sql.FieldIn(FieldPrincipalID, vs...))
}

// PrincipalIDNotIn applies the NotIn predicate on the "principal_id" field.
func PrincipalIDNotIn(vs ...string) predicate.ModelhubAPIKey {
	return predicate.ModelhubAPIKey(sql.FieldNotIn(FieldPrincipalID, vs...))
}

// PrincipalIDGT applies the GT predicate on the "principal_id" field.
func PrincipalIDGT(v string) predicate.ModelhubAPIKey {
	return predicate.ModelhubAPIKey(sql.FieldGT(FieldPrincipalID, v))
}

// PrincipalIDGTE applies the GTE predicate on the "principal_id" field.
func PrincipalIDGTE(v string) predicate.ModelhubAPIKey {
	return predicate.ModelhubAPIKey(sql.FieldGTE(FieldPrincipalID, v))
}

// PrincipalIDLT applies the LT predicate on the "principal_id" field.
func PrincipalIDLT(v string) predicate.ModelhubAPIKey {
	return predicate.ModelhubAPIKey(sql.FieldLT(FieldPrincipalID, v))
}

// PrincipalIDLTE applies the LTE predicate on the "principal_id" field.
func PrincipalIDLTE(v string) predicate.ModelhubAPIKey {
	return predicate.ModelhubAPIKey(sql.FieldLTE(FieldPrincipalID, v))
}

// PrincipalIDContains applies the Contains predicate on the "principal_id" field.
func PrincipalIDContains(v string) predicate.ModelhubAPIKey {
	return predicate.ModelhubAPIKey(sql.FieldContains(FieldPrincipalID, v))
}

// PrincipalIDHasPrefix applies the HasPrefix predicate on the "principal_id" field.
func PrincipalIDHasPrefix(v string) predicate.ModelhubAPIKey {
	return predicate.ModelhubAPIKey(sql.FieldHasPrefix(FieldPrincipalID, v))
}

// PrincipalIDHasSuffix applies the HasSuffix predicate on the "principal_id" field.
func PrincipalIDHasSuffix(v string) predicate.ModelhubAPIKey {
	return predicate.ModelhubAPIKey(sql.FieldHasSuffix(FieldPrincipalID, v))
}

// PrincipalIDEqualFold applies the EqualFold predicate on the "principal_id" field.
func PrincipalIDEqualFold(v string) predicate.ModelhubAPIKey {
	return predicate.ModelhubAPIKey(sql.FieldEqualFold(FieldPrincipalID, v))
}

// PrincipalIDContainsFold applies the ContainsFold predicate on the "principal_id" field.
func PrincipalIDContainsFold(v string) predicate.ModelhubAPIKey {
	return predicate.ModelhubAPIKey(sql.FieldContainsFold(FieldPrincipalID, v))
}

// KeyIDEQ applies the EQ predicate on the "key_id" field.
func KeyIDEQ(v string) predicate.ModelhubAPIKey {
	return predicate.ModelhubAPIKey(sql.FieldEQ(FieldKeyID, v))
}

// KeyIDNEQ applies the NEQ predicate on the "key_id" field.
func KeyIDNEQ(v string) predicate.ModelhubAPIKey {
	return predicate.ModelhubAPIKey(sql.FieldNEQ(FieldKeyID, v))
}

// KeyIDIn applies the In predicate on the "key_id" field.
func KeyIDIn(vs ...string) predicate.ModelhubAPIKey {
	return predicate.ModelhubAPIKey(sql.FieldIn(FieldKeyID, vs...))
}

// KeyIDNotIn applies the NotIn predicate on the "key_id" field.
func KeyIDNotIn(vs ...string) predicate.ModelhubAPIKey {
	return predicate.ModelhubAPIKey(sql.FieldNotIn(FieldKeyID, vs...))
}

// KeyIDGT applies the GT predicate on the "key_id" field.
func KeyIDGT(v string) predicate.ModelhubAPIKey {
	return predicate.ModelhubAPIKey(sql.FieldGT(FieldKeyID, v))
}

// KeyIDGTE applies the GTE predicate on the "key_id" field.
func KeyIDGTE(v string) predicate.ModelhubAPIKey {
	return predicate.ModelhubAPIKey(sql.FieldGTE(FieldKeyID, v))
}

// KeyIDLT applies the LT predicate on the "key_id" field.
func KeyIDLT(v string) predicate.ModelhubAPIKey {
	return predicate.ModelhubAPIKey(sql.FieldLT(FieldKeyID, v))
}

// KeyIDLTE applies the LTE predicate on the "key_id" field.
func KeyIDLTE(v string) predicate.ModelhubAPIKey {
	return predicate.ModelhubAPIKey(sql.FieldLTE(FieldKeyID, v))
}

// KeyIDContains applies the Contains predicate on the "key_id" field.
func KeyIDContains(v string) predicate.ModelhubAPIKey {
	return predicate.ModelhubAPIKey(sql.FieldContains(FieldKeyID, v))
}

// KeyIDHasPrefix applies the HasPrefix predicate on the "key_id" field.
func KeyIDHasPrefix(v string) predicate.ModelhubAPIKey {
	return predicate.ModelhubAPIKey(sql.FieldHasPrefix(FieldKeyID, v))
}

// KeyIDHasSuffix applies the HasSuffix predicate on the "key_id" field.
func KeyIDHasSuffix(v string) predicate.ModelhubAPIKey {
	return predicate.ModelhubAPIKey(sql.FieldHasSuffix(FieldKeyID, v))
}

// KeyIDEqualFold applies the EqualFold predicate on the "key_id" field.
func KeyIDEqualFold(v string) predicate.ModelhubAPIKey {
	return predicate.ModelhubAPIKey(sql.FieldEqualFold(FieldKeyID, v))
}

// KeyIDContainsFold applies the ContainsFold predicate on the "key_id" field.
func KeyIDContainsFold(v string) predicate.ModelhubAPIKey {
	return predicate.ModelhubAPIKey(sql.FieldContainsFold(FieldKeyID, v))
}

// SecretSha256EQ applies the EQ predicate on the "secret_sha256" field.
func SecretSha256EQ(v string) predicate.ModelhubAPIKey {
	return predicate.ModelhubAPIKey(sql.FieldEQ(FieldSecretSha256, v))
}

// SecretSha256NEQ applies the NEQ predicate on the "secret_sha256" field.
func SecretSha256NEQ(v string) predicate.ModelhubAPIKey {
	return predicate.ModelhubAPIKey(sql.FieldNEQ(FieldSecretSha256, v))
}

// SecretSha256In applies the In predicate on the "secret_sha256" field.
func SecretSha256In(vs ...string) predicate.ModelhubAPIKey {
	return predicate.ModelhubAPIKey(sql.FieldIn(FieldSecretSha256, vs...))
}

// SecretSha256NotIn applies the NotIn predicate on the "secret_sha256" field.
func SecretSha256NotIn(vs ...string) predicate.ModelhubAPIKey {
	return predicate.ModelhubAPIKey(sql.FieldNotIn(FieldSecretSha256, vs...))
}

// SecretSha256GT applies the GT predicate on the "secret_sha256" field.
func SecretSha256GT(v string) predicate.ModelhubAPIKey {
	return predicate.ModelhubAPIKey(sql.FieldGT(FieldSecretSha256, v))
}

// SecretSha256GTE applies the GTE predicate on the "secret_sha256" field.
func SecretSha256GTE(v string) predicate.ModelhubAPIKey {
	return predicate.ModelhubAPIKey(sql.FieldGTE(FieldSecretSha256, v))
}

// SecretSha256LT applies the LT predicate on the "secret_sha256" field.
func SecretSha256LT(v string) predicate.ModelhubAPIKey {
	return predicate.ModelhubAPIKey(sql.FieldLT(FieldSecretSha256, v))
}

// SecretSha256LTE applies the LTE predicate on the "secret_sha256" field.
func SecretSha256LTE(v string) predicate.ModelhubAPIKey {
	return predicate.ModelhubAPIKey(sql.FieldLTE(FieldSecretSha256, v))
}

// SecretSha256Contains applies the Contains predicate on the "secret_sha256" field.
func SecretSha256Contains(v string) predicate.ModelhubAPIKey {
	return predicate.ModelhubAPIKey(sql.FieldContains(FieldSecretSha256, v))
}

// SecretSha256HasPrefix applies the HasPrefix predicate on the "secret_sha256" field.
func SecretSha256HasPrefix(v string) predicate.ModelhubAPIKey {
	return predicate.ModelhubAPIKey(sql.FieldHasPrefix(FieldSecretSha256, v))
}

// SecretSha256HasSuffix applies the HasSuffix predicate on the "secret_sha256" field.
func SecretSha256HasSuffix(v string) predicate.ModelhubAPIKey {
	return predicate.ModelhubAPIKey(sql.FieldHasSuffix(FieldSecretSha256, v))
}

// SecretSha256EqualFold applies the EqualFold predicate on the "secret_sha256" field.
func SecretSha256EqualFold(v string) predicate.ModelhubAPIKey {
	return predicate.ModelhubAPIKey(sql.FieldEqualFold(FieldSecretSha256, v))
}

// SecretSha256ContainsFold applies the ContainsFold predicate on the "secret_sha256" field.
func SecretSha256ContainsFold(v string) predicate.ModelhubAPIKey {
	return predicate.ModelhubAPIKey(sql.FieldContainsFold(FieldSecretSha256, v))
}

// NameEQ applies the EQ predicate on the "name" field.
func NameEQ(v string) predicate.ModelhubAPIKey {
	return predicate.ModelhubAPIKey(sql.FieldEQ(FieldName, v))
}

// NameNEQ applies the NEQ predicate on the "name" field.
func NameNEQ(v string) predicate.ModelhubAPIKey {
	return predicate.ModelhubAPIKey(sql.FieldNEQ(FieldName, v))
}

// NameIn applies the In predicate on the "name" field.
func NameIn(vs ...string) predicate.ModelhubAPIKey {
	return predicate.ModelhubAPIKey(sql.FieldIn(FieldName, vs...))
}

// NameNotIn applies the NotIn predicate on the "name" field.
func NameNotIn(vs ...string) predicate.ModelhubAPIKey {
	return predicate.ModelhubAPIKey(sql.FieldNotIn(FieldName, vs...))
}

// NameGT applies the GT predicate on the "name" field.
func NameGT(v string) predicate.ModelhubAPIKey {
	return predicate.ModelhubAPIKey(sql.FieldGT(FieldName, v))
}

// NameGTE applies the GTE predicate on the "name" field.
func NameGTE(v string) predicate.ModelhubAPIKey {
	return predicate.ModelhubAPIKey(sql.FieldGTE(FieldName, v))
}

// NameLT applies the LT predicate on the "name" field.
func NameLT(v string) predicate.ModelhubAPIKey {
	return predicate.ModelhubAPIKey(sql.FieldLT(FieldName, v))
}

// NameLTE applies the LTE predicate on the "name" field.
func NameLTE(v string) predicate.ModelhubAPIKey {
	return predicate.ModelhubAPIKey(sql.FieldLTE(FieldName, v))
}

// NameContains applies the Contains predicate on the "name" field.
func NameContains(v string) predicate.ModelhubAPIKey {
	return predicate.ModelhubAPIKey(sql.FieldContains(FieldName, v))
}

// NameHasPrefix applies the HasPrefix predicate on the "name" field.
func NameHasPrefix(v string) predicate.ModelhubAPIKey {
	return predicate.ModelhubAPIKey(sql.FieldHasPrefix(FieldName, v))
}

// NameHasSuffix applies the HasSuffix predicate on the "name" field.
func NameHasSuffix(v string) predicate.ModelhubAPIKey {
	return predicate.ModelhubAPIKey(sql.FieldHasSuffix(FieldName, v))
}

// NameEqualFold applies the EqualFold predicate on the "name" field.
func NameEqualFold(v string) predicate.ModelhubAPIKey {
	return predicate.ModelhubAPIKey(sql.FieldEqualFold(FieldName, v))
}

// NameContainsFold applies the ContainsFold predicate on the "name" field.
func NameContainsFold(v string) predicate.ModelhubAPIKey {
	return predicate.ModelhubAPIKey(sql.FieldContainsFold(FieldName, v))
}

// CreatedByEQ applies the EQ predicate on the "created_by" field.
func CreatedByEQ(v string) predicate.ModelhubAPIKey {
	return predicate.ModelhubAPIKey(sql.FieldEQ(FieldCreatedBy, v))
}

// CreatedByNEQ applies the NEQ predicate on the "created_by" field.
func CreatedByNEQ(v string) predicate.ModelhubAPIKey {
	return predicate.ModelhubAPIKey(sql.FieldNEQ(FieldCreatedBy, v))
}

// CreatedByIn applies the In predicate on the "created_by" field.
func CreatedByIn(vs ...string) predicate.ModelhubAPIKey {
	return predicate.ModelhubAPIKey(sql.FieldIn(FieldCreatedBy, vs...))
}

// CreatedByNotIn applies the NotIn predicate on the "created_by" field.
func CreatedByNotIn(vs ...string) predicate.ModelhubAPIKey {
	return predicate.ModelhubAPIKey(sql.FieldNotIn(FieldCreatedBy, vs...))
}

// CreatedByGT applies the GT predicate on the "created_by" field.
func CreatedByGT(v string) predicate.ModelhubAPIKey {
	return predicate.ModelhubAPIKey(sql.FieldGT(FieldCreatedBy, v))
}

// CreatedByGTE applies the GTE predicate on the "created_by" field.
func CreatedByGTE(v string) predicate.ModelhubAPIKey {
	return predicate.ModelhubAPIKey(sql.FieldGTE(FieldCreatedBy, v))
}

// CreatedByLT applies the LT predicate on the "created_by" field.
func CreatedByLT(v string) predicate.ModelhubAPIKey {
	return predicate.ModelhubAPIKey(sql.FieldLT(FieldCreatedBy, v))
}

// CreatedByLTE applies the LTE predicate on the "created_by" field.
func CreatedByLTE(v string) predicate.ModelhubAPIKey {
	return predicate.ModelhubAPIKey(sql.FieldLTE(FieldCreatedBy, v))
}

// CreatedByContains applies the Contains predicate on the "created_by" field.
func CreatedByContains(v string) predicate.ModelhubAPIKey {
	return predicate.ModelhubAPIKey(sql.FieldContains(FieldCreatedBy, v))
}

// CreatedByHasPrefix applies the HasPrefix predicate on the "created_by" field.
func CreatedByHasPrefix(v string) predicate.ModelhubAPIKey {
	return predicate.ModelhubAPIKey(sql.FieldHasPrefix(FieldCreatedBy, v))
}

// CreatedByHasSuffix applies the HasSuffix predicate on the "created_by" field.
func CreatedByHasSuffix(v string) predicate.ModelhubAPIKey {
	return predicate.ModelhubAPIKey(sql.FieldHasSuffix(FieldCreatedBy, v))
}

// CreatedByEqualFold applies the EqualFold predicate on the "created_by" field.
func CreatedByEqualFold(v string) predicate.ModelhubAPIKey {
	return predicate.ModelhubAPIKey(sql.FieldEqualFold(FieldCreatedBy, v))
}

// CreatedByContainsFold applies the ContainsFold predicate on the "created_by" field.
func CreatedByContainsFold(v string) predicate.ModelhubAPIKey {
	return predicate.ModelhubAPIKey(sql.FieldContainsFold(FieldCreatedBy, v))
}

// CreatedAtEQ applies the EQ predicate on the "created_at" field.
func CreatedAtEQ(v time.Time) predicate.ModelhubAPIKey {
	return predicate.ModelhubAPIKey(sql.FieldEQ(FieldCreatedAt, v))
}

// CreatedAtNEQ applies the NEQ predicate on the "created_at" field.
func CreatedAtNEQ(v time.Time) predicate.ModelhubAPIKey {
	return predicate.ModelhubAPIKey(sql.FieldNEQ(FieldCreatedAt, v))
}

// CreatedAtIn applies the In predicate on the "created_at" field.
func CreatedAtIn(vs ...time.Time) predicate.ModelhubAPIKey {
	return predicate.ModelhubAPIKey(sql.FieldIn(FieldCreatedAt, vs...))
}

// CreatedAtNotIn applies the NotIn predicate on the "created_at" field.
func CreatedAtNotIn(vs ...time.Time) predicate.ModelhubAPIKey {
	return predicate.ModelhubAPIKey(sql.FieldNotIn(FieldCreatedAt, vs...))
}

// CreatedAtGT applies the GT predicate on the "created_at" field.
func CreatedAtGT(v time.Time) predicate.ModelhubAPIKey {
	return predicate.ModelhubAPIKey(sql.FieldGT(FieldCreatedAt, v))
}

// CreatedAtGTE applies the GTE predicate on the "created_at" field.
func CreatedAtGTE(v time.Time) predicate.ModelhubAPIKey {
	return predicate.ModelhubAPIKey(sql.FieldGTE(FieldCreatedAt, v))
}

// CreatedAtLT applies the LT predicate on the "created_at" field.
func CreatedAtLT(v time.Time) predicate.ModelhubAPIKey {
	return predicate.ModelhubAPIKey(sql.FieldLT(FieldCreatedAt, v))
}

// CreatedAtLTE applies the LTE predicate on the "created_at" field.
func CreatedAtLTE(v time.Time) predicate.ModelhubAPIKey {
	return predicate.ModelhubAPIKey(sql.FieldLTE(FieldCreatedAt, v))
}

// ExpiresAtEQ applies the EQ predicate on the "expires_at" field.
func ExpiresAtEQ(v time.Time) predicate.ModelhubAPIKey {
	return predicate.ModelhubAPIKey(sql.FieldEQ(FieldExpiresAt, v))
}

// ExpiresAtNEQ applies the NEQ predicate on the "expires_at" field.
func ExpiresAtNEQ(v time.Time) predicate.ModelhubAPIKey {
	return predicate.ModelhubAPIKey(sql.FieldNEQ(FieldExpiresAt, v))
}

// ExpiresAtIn applies the In predicate on the "expires_at" field.
func ExpiresAtIn(vs ...time.Time) predicate.ModelhubAPIKey {
	return predicate.ModelhubAPIKey(sql.FieldIn(FieldExpiresAt, vs...))
}

// ExpiresAtNotIn applies the NotIn predicate on the "expires_at" field.
func ExpiresAtNotIn(vs ...time.Time) predicate.ModelhubAPIKey {
	return predicate.ModelhubAPIKey(sql.FieldNotIn(FieldExpiresAt, vs...))
}

// ExpiresAtGT applies the GT predicate on the "expires_at" field.
func ExpiresAtGT(v time.Time) predicate.ModelhubAPIKey {
	return predicate.ModelhubAPIKey(sql.FieldGT(FieldExpiresAt, v))
}

// ExpiresAtGTE applies the GTE predicate on the "expires_at" field.
func ExpiresAtGTE(v time.Time) predicate.ModelhubAPIKey {
	return predicate.ModelhubAPIKey(sql.FieldGTE(FieldExpiresAt, v))
}

// ExpiresAtLT applies the LT predicate on the "expires_at" field.
func ExpiresAtLT(v time.Time) predicate.ModelhubAPIKey {
	return predicate.ModelhubAPIKey(sql.FieldLT(FieldExpiresAt, v))
}

// ExpiresAtLTE applies the LTE predicate on the "expires_at" field.
func ExpiresAtLTE(v time.Time) predicate.ModelhubAPIKey {
	return predicate.ModelhubAPIKey(sql.FieldLTE(FieldExpiresAt, v))
}

// RevokedAtEQ applies the EQ predicate on the "revoked_at" field.
func RevokedAtEQ(v time.Time) predicate.ModelhubAPIKey {
	return predicate.ModelhubAPIKey(sql.FieldEQ(FieldRevokedAt, v))
}

// RevokedAtNEQ applies the NEQ predicate on the "revoked_at" field.
func RevokedAtNEQ(v time.Time) predicate.ModelhubAPIKey {
	return predicate.ModelhubAPIKey(sql.FieldNEQ(FieldRevokedAt, v))
}

// RevokedAtIn applies the In predicate on the "revoked_at" field.
func RevokedAtIn(vs ...time.Time) predicate.ModelhubAPIKey {
	return predicate.ModelhubAPIKey(sql.FieldIn(FieldRevokedAt, vs...))
}

// RevokedAtNotIn applies the NotIn predicate on the "revoked_at" field.
func RevokedAtNotIn(vs ...time.Time) predicate.ModelhubAPIKey {
	return predicate.ModelhubAPIKey(sql.FieldNotIn(FieldRevokedAt, vs...))
}

// RevokedAtGT applies the GT predicate on the "revoked_at" field.
func RevokedAtGT(v time.Time) predicate.ModelhubAPIKey {
	return predicate.ModelhubAPIKey(sql.FieldGT(FieldRevokedAt, v))
}

// RevokedAtGTE applies the GTE predicate on the "revoked_at" field.
func RevokedAtGTE(v time.Time) predicate.ModelhubAPIKey {
	return predicate.ModelhubAPIKey(sql.FieldGTE(FieldRevokedAt, v))
}

// RevokedAtLT applies the LT predicate on the "revoked_at" field.
func RevokedAtLT(v time.Time) predicate.ModelhubAPIKey {
	return predicate.ModelhubAPIKey(sql.FieldLT(FieldRevokedAt, v))
}

// RevokedAtLTE applies the LTE predicate on the "revoked_at" field.
func RevokedAtLTE(v time.Time) predicate.ModelhubAPIKey {
	return predicate.ModelhubAPIKey(sql.FieldLTE(FieldRevokedAt, v))
}

// RevokedAtIsNil applies the IsNil predicate on the "revoked_at" field.
func RevokedAtIsNil() predicate.ModelhubAPIKey {
	return predicate.ModelhubAPIKey(sql.FieldIsNull(FieldRevokedAt))
}

// RevokedAtNotNil applies the NotNil predicate on the "revoked_at" field.
func RevokedAtNotNil() predicate.ModelhubAPIKey {
	return predicate.ModelhubAPIKey(sql.FieldNotNull(FieldRevokedAt))
}

// And groups predicates with the AND operator between them.
func And(predicates ...predicate.ModelhubAPIKey) predicate.ModelhubAPIKey {
	return predicate.ModelhubAPIKey(sql.AndPredicates(predicates...))
}

// Or groups predicates with the OR operator between them.
func Or(predicates ...predicate.ModelhubAPIKey) predicate.ModelhubAPIKey {
	return predicate.ModelhubAPIKey(sql.OrPredicates(predicates...))
}

// Not applies the not operator on the given predicate.
func Not(p predicate.ModelhubAPIKey) predicate.ModelhubAPIKey {
	return predicate.ModelhubAPIKey(sql.NotPredicates(p))
}
