// Code generated by ent, DO NOT EDIT.

package generationtask

import (
	"time"

	"entgo.io/ent/dialect/sql"
	"github.com/wgdl666/wgModelHub/ent/predicate"
)

// ID filters vertices based on their ID field.
func ID(id string) predicate.GenerationTask {
	return predicate.GenerationTask(sql.FieldEQ(FieldID, id))
}

// IDEQ applies the EQ predicate on the ID field.
func IDEQ(id string) predicate.GenerationTask {
	return predicate.GenerationTask(sql.FieldEQ(FieldID, id))
}

// IDNEQ applies the NEQ predicate on the ID field.
func IDNEQ(id string) predicate.GenerationTask {
	return predicate.GenerationTask(sql.FieldNEQ(FieldID, id))
}

// IDIn applies the In predicate on the ID field.
func IDIn(ids ...string) predicate.GenerationTask {
	return predicate.GenerationTask(sql.FieldIn(FieldID, ids...))
}

// IDNotIn applies the NotIn predicate on the ID field.
func IDNotIn(ids ...string) predicate.GenerationTask {
	return predicate.GenerationTask(sql.FieldNotIn(FieldID, ids...))
}

// IDGT applies the GT predicate on the ID field.
func IDGT(id string) predicate.GenerationTask {
	return predicate.GenerationTask(sql.FieldGT(FieldID, id))
}

// IDGTE applies the GTE predicate on the ID field.
func IDGTE(id string) predicate.GenerationTask {
	return predicate.GenerationTask(sql.FieldGTE(FieldID, id))
}

// IDLT applies the LT predicate on the ID field.
func IDLT(id string) predicate.GenerationTask {
	return predicate.GenerationTask(sql.FieldLT(FieldID, id))
}

// IDLTE applies the LTE predicate on the ID field.
func IDLTE(id string) predicate.GenerationTask {
	return predicate.GenerationTask(sql.FieldLTE(FieldID, id))
}

// IDEqualFold applies the EqualFold predicate on the ID field.
func IDEqualFold(id string) predicate.GenerationTask {
	return predicate.GenerationTask(sql.FieldEqualFold(FieldID, id))
}

// IDContainsFold applies the ContainsFold predicate on the ID field.
func IDContainsFold(id string) predicate.GenerationTask {
	return predicate.GenerationTask(sql.FieldContainsFold(FieldID, id))
}

// Caller applies equality check predicate on the "caller" field. It's identical to CallerEQ.
func Caller(v string) predicate.GenerationTask {
	return predicate.GenerationTask(sql.FieldEQ(FieldCaller, v))
}

// RequestID applies equality check predicate on the "request_id" field. It's identical to RequestIDEQ.
func RequestID(v string) predicate.GenerationTask {
	return predicate.GenerationTask(sql.FieldEQ(FieldRequestID, v))
}

// RequestHash applies equality check predicate on the "request_hash" field. It's identical to RequestHashEQ.
func RequestHash(v string) predicate.GenerationTask {
	return predicate.GenerationTask(sql.FieldEQ(FieldRequestHash, v))
}

// Model applies equality check predicate on the "model" field. It's identical to ModelEQ.
func Model(v string) predicate.GenerationTask {
	return predicate.GenerationTask(sql.FieldEQ(FieldModel, v))
}

// Provider applies equality check predicate on the "provider" field. It's identical to ProviderEQ.
func Provider(v string) predicate.GenerationTask {
	return predicate.GenerationTask(sql.FieldEQ(FieldProvider, v))
}

// ProviderTaskID applies equality check predicate on the "provider_task_id" field. It's identical to ProviderTaskIDEQ.
func ProviderTaskID(v string) predicate.GenerationTask {
	return predicate.GenerationTask(sql.FieldEQ(FieldProviderTaskID, v))
}

// State applies equality check predicate on the "state" field. It's identical to StateEQ.
func State(v string) predicate.GenerationTask {
	return predicate.GenerationTask(sql.FieldEQ(FieldState, v))
}

// ErrorCode applies equality check predicate on the "error_code" field. It's identical to ErrorCodeEQ.
func ErrorCode(v int32) predicate.GenerationTask {
	return predicate.GenerationTask(sql.FieldEQ(FieldErrorCode, v))
}

// ErrorMessage applies equality check predicate on the "error_message" field. It's identical to ErrorMessageEQ.
func ErrorMessage(v string) predicate.GenerationTask {
	return predicate.GenerationTask(sql.FieldEQ(FieldErrorMessage, v))
}

// ErrorReason applies equality check predicate on the "error_reason" field. It's identical to ErrorReasonEQ.
func ErrorReason(v string) predicate.GenerationTask {
	return predicate.GenerationTask(sql.FieldEQ(FieldErrorReason, v))
}

// CreatedAt applies equality check predicate on the "created_at" field. It's identical to CreatedAtEQ.
func CreatedAt(v time.Time) predicate.GenerationTask {
	return predicate.GenerationTask(sql.FieldEQ(FieldCreatedAt, v))
}

// UpdatedAt applies equality check predicate on the "updated_at" field. It's identical to UpdatedAtEQ.
func UpdatedAt(v time.Time) predicate.GenerationTask {
	return predicate.GenerationTask(sql.FieldEQ(FieldUpdatedAt, v))
}

// CallerEQ applies the EQ predicate on the "caller" field.
func CallerEQ(v string) predicate.GenerationTask {
	return predicate.GenerationTask(sql.FieldEQ(FieldCaller, v))
}

// CallerNEQ applies the NEQ predicate on the "caller" field.
func CallerNEQ(v string) predicate.GenerationTask {
	return predicate.GenerationTask(sql.FieldNEQ(FieldCaller, v))
}

// CallerIn applies the In predicate on the "caller" field.
func CallerIn(vs ...string) predicate.GenerationTask {
	return predicate.GenerationTask(sql.FieldIn(FieldCaller, vs...))
}

// CallerNotIn applies the NotIn predicate on the "caller" field.
func CallerNotIn(vs ...string) predicate.GenerationTask {
	return predicate.GenerationTask(sql.FieldNotIn(FieldCaller, vs...))
}

// CallerGT applies the GT predicate on the "caller" field.
func CallerGT(v string) predicate.GenerationTask {
	return predicate.GenerationTask(sql.FieldGT(FieldCaller, v))
}

// CallerGTE applies the GTE predicate on the "caller" field.
func CallerGTE(v string) predicate.GenerationTask {
	return predicate.GenerationTask(sql.FieldGTE(FieldCaller, v))
}

// CallerLT applies the LT predicate on the "caller" field.
func CallerLT(v string) predicate.GenerationTask {
	return predicate.GenerationTask(sql.FieldLT(FieldCaller, v))
}

// CallerLTE applies the LTE predicate on the "caller" field.
func CallerLTE(v string) predicate.GenerationTask {
	return predicate.GenerationTask(sql.FieldLTE(FieldCaller, v))
}

// CallerContains applies the Contains predicate on the "caller" field.
func CallerContains(v string) predicate.GenerationTask {
	return predicate.GenerationTask(sql.FieldContains(FieldCaller, v))
}

// CallerHasPrefix applies the HasPrefix predicate on the "caller" field.
func CallerHasPrefix(v string) predicate.GenerationTask {
	return predicate.GenerationTask(sql.FieldHasPrefix(FieldCaller, v))
}

// CallerHasSuffix applies the HasSuffix predicate on the "caller" field.
func CallerHasSuffix(v string) predicate.GenerationTask {
	return predicate.GenerationTask(sql.FieldHasSuffix(FieldCaller, v))
}

// CallerEqualFold applies the EqualFold predicate on the "caller" field.
func CallerEqualFold(v string) predicate.GenerationTask {
	return predicate.GenerationTask(sql.FieldEqualFold(FieldCaller, v))
}

// CallerContainsFold applies the ContainsFold predicate on the "caller" field.
func CallerContainsFold(v string) predicate.GenerationTask {
	return predicate.GenerationTask(sql.FieldContainsFold(FieldCaller, v))
}

// RequestIDEQ applies the EQ predicate on the "request_id" field.
func RequestIDEQ(v string) predicate.GenerationTask {
	return predicate.GenerationTask(sql.FieldEQ(FieldRequestID, v))
}

// RequestIDNEQ applies the NEQ predicate on the "request_id" field.
func RequestIDNEQ(v string) predicate.GenerationTask {
	return predicate.GenerationTask(sql.FieldNEQ(FieldRequestID, v))
}

// RequestIDIn applies the In predicate on the "request_id" field.
func RequestIDIn(vs ...string) predicate.GenerationTask {
	return predicate.GenerationTask(sql.FieldIn(FieldRequestID, vs...))
}

// RequestIDNotIn applies the NotIn predicate on the "request_id" field.
func RequestIDNotIn(vs ...string) predicate.GenerationTask {
	return predicate.GenerationTask(sql.FieldNotIn(FieldRequestID, vs...))
}

// RequestIDGT applies the GT predicate on the "request_id" field.
func RequestIDGT(v string) predicate.GenerationTask {
	return predicate.GenerationTask(sql.FieldGT(FieldRequestID, v))
}

// RequestIDGTE applies the GTE predicate on the "request_id" field.
func RequestIDGTE(v string) predicate.GenerationTask {
	return predicate.GenerationTask(sql.FieldGTE(FieldRequestID, v))
}

// RequestIDLT applies the LT predicate on the "request_id" field.
func RequestIDLT(v string) predicate.GenerationTask {
	return predicate.GenerationTask(sql.FieldLT(FieldRequestID, v))
}

// RequestIDLTE applies the LTE predicate on the "request_id" field.
func RequestIDLTE(v string) predicate.GenerationTask {
	return predicate.GenerationTask(sql.FieldLTE(FieldRequestID, v))
}

// RequestIDContains applies the Contains predicate on the "request_id" field.
func RequestIDContains(v string) predicate.GenerationTask {
	return predicate.GenerationTask(sql.FieldContains(FieldRequestID, v))
}

// RequestIDHasPrefix applies the HasPrefix predicate on the "request_id" field.
func RequestIDHasPrefix(v string) predicate.GenerationTask {
	return predicate.GenerationTask(sql.FieldHasPrefix(FieldRequestID, v))
}

// RequestIDHasSuffix applies the HasSuffix predicate on the "request_id" field.
func RequestIDHasSuffix(v string) predicate.GenerationTask {
	return predicate.GenerationTask(sql.FieldHasSuffix(FieldRequestID, v))
}

// RequestIDEqualFold applies the EqualFold predicate on the "request_id" field.
func RequestIDEqualFold(v string) predicate.GenerationTask {
	return predicate.GenerationTask(sql.FieldEqualFold(FieldRequestID, v))
}

// RequestIDContainsFold applies the ContainsFold predicate on the "request_id" field.
func RequestIDContainsFold(v string) predicate.GenerationTask {
	return predicate.GenerationTask(sql.FieldContainsFold(FieldRequestID, v))
}

// RequestHashEQ applies the EQ predicate on the "request_hash" field.
func RequestHashEQ(v string) predicate.GenerationTask {
	return predicate.GenerationTask(sql.FieldEQ(FieldRequestHash, v))
}

// RequestHashNEQ applies the NEQ predicate on the "request_hash" field.
func RequestHashNEQ(v string) predicate.GenerationTask {
	return predicate.GenerationTask(sql.FieldNEQ(FieldRequestHash, v))
}

// RequestHashIn applies the In predicate on the "request_hash" field.
func RequestHashIn(vs ...string) predicate.GenerationTask {
	return predicate.GenerationTask(sql.FieldIn(FieldRequestHash, vs...))
}

// RequestHashNotIn applies the NotIn predicate on the "request_hash" field.
func RequestHashNotIn(vs ...string) predicate.GenerationTask {
	return predicate.GenerationTask(sql.FieldNotIn(FieldRequestHash, vs...))
}

// RequestHashGT applies the GT predicate on the "request_hash" field.
func RequestHashGT(v string) predicate.GenerationTask {
	return predicate.GenerationTask(sql.FieldGT(FieldRequestHash, v))
}

// RequestHashGTE applies the GTE predicate on the "request_hash" field.
func RequestHashGTE(v string) predicate.GenerationTask {
	return predicate.GenerationTask(sql.FieldGTE(FieldRequestHash, v))
}

// RequestHashLT applies the LT predicate on the "request_hash" field.
func RequestHashLT(v string) predicate.GenerationTask {
	return predicate.GenerationTask(sql.FieldLT(FieldRequestHash, v))
}

// RequestHashLTE applies the LTE predicate on the "request_hash" field.
func RequestHashLTE(v string) predicate.GenerationTask {
	return predicate.GenerationTask(sql.FieldLTE(FieldRequestHash, v))
}

// RequestHashContains applies the Contains predicate on the "request_hash" field.
func RequestHashContains(v string) predicate.GenerationTask {
	return predicate.GenerationTask(sql.FieldContains(FieldRequestHash, v))
}

// RequestHashHasPrefix applies the HasPrefix predicate on the "request_hash" field.
func RequestHashHasPrefix(v string) predicate.GenerationTask {
	return predicate.GenerationTask(sql.FieldHasPrefix(FieldRequestHash, v))
}

// RequestHashHasSuffix applies the HasSuffix predicate on the "request_hash" field.
func RequestHashHasSuffix(v string) predicate.GenerationTask {
	return predicate.GenerationTask(sql.FieldHasSuffix(FieldRequestHash, v))
}

// RequestHashEqualFold applies the EqualFold predicate on the "request_hash" field.
func RequestHashEqualFold(v string) predicate.GenerationTask {
	return predicate.GenerationTask(sql.FieldEqualFold(FieldRequestHash, v))
}

// RequestHashContainsFold applies the ContainsFold predicate on the "request_hash" field.
func RequestHashContainsFold(v string) predicate.GenerationTask {
	return predicate.GenerationTask(sql.FieldContainsFold(FieldRequestHash, v))
}

// ModelEQ applies the EQ predicate on the "model" field.
func ModelEQ(v string) predicate.GenerationTask {
	return predicate.GenerationTask(sql.FieldEQ(FieldModel, v))
}

// ModelNEQ applies the NEQ predicate on the "model" field.
func ModelNEQ(v string) predicate.GenerationTask {
	return predicate.GenerationTask(sql.FieldNEQ(FieldModel, v))
}

// ModelIn applies the In predicate on the "model" field.
func ModelIn(vs ...string) predicate.GenerationTask {
	return predicate.GenerationTask(sql.FieldIn(FieldModel, vs...))
}

// ModelNotIn applies the NotIn predicate on the "model" field.
func ModelNotIn(vs ...string) predicate.GenerationTask {
	return predicate.GenerationTask(sql.FieldNotIn(FieldModel, vs...))
}

// ModelGT applies the GT predicate on the "model" field.
func ModelGT(v string) predicate.GenerationTask {
	return predicate.GenerationTask(sql.FieldGT(FieldModel, v))
}

// ModelGTE applies the GTE predicate on the "model" field.
func ModelGTE(v string) predicate.GenerationTask {
	return predicate.GenerationTask(sql.FieldGTE(FieldModel, v))
}

// ModelLT applies the LT predicate on the "model" field.
func ModelLT(v string) predicate.GenerationTask {
	return predicate.GenerationTask(sql.FieldLT(FieldModel, v))
}

// ModelLTE applies the LTE predicate on the "model" field.
func ModelLTE(v string) predicate.GenerationTask {
	return predicate.GenerationTask(sql.FieldLTE(FieldModel, v))
}

// ModelContains applies the Contains predicate on the "model" field.
func ModelContains(v string) predicate.GenerationTask {
	return predicate.GenerationTask(sql.FieldContains(FieldModel, v))
}

// ModelHasPrefix applies the HasPrefix predicate on the "model" field.
func ModelHasPrefix(v string) predicate.GenerationTask {
	return predicate.GenerationTask(sql.FieldHasPrefix(FieldModel, v))
}

// ModelHasSuffix applies the HasSuffix predicate on the "model" field.
func ModelHasSuffix(v string) predicate.GenerationTask {
	return predicate.GenerationTask(sql.FieldHasSuffix(FieldModel, v))
}

// ModelEqualFold applies the EqualFold predicate on the "model" field.
func ModelEqualFold(v string) predicate.GenerationTask {
	return predicate.GenerationTask(sql.FieldEqualFold(FieldModel, v))
}

// ModelContainsFold applies the ContainsFold predicate on the "model" field.
func ModelContainsFold(v string) predicate.GenerationTask {
	return predicate.GenerationTask(sql.FieldContainsFold(FieldModel, v))
}

// ProviderEQ applies the EQ predicate on the "provider" field.
func ProviderEQ(v string) predicate.GenerationTask {
	return predicate.GenerationTask(sql.FieldEQ(FieldProvider, v))
}

// ProviderNEQ applies the NEQ predicate on the "provider" field.
func ProviderNEQ(v string) predicate.GenerationTask {
	return predicate.GenerationTask(sql.FieldNEQ(FieldProvider, v))
}

// ProviderIn applies the In predicate on the "provider" field.
func ProviderIn(vs ...string) predicate.GenerationTask {
	return predicate.GenerationTask(sql.FieldIn(FieldProvider, vs...))
}

// ProviderNotIn applies the NotIn predicate on the "provider" field.
func ProviderNotIn(vs ...string) predicate.GenerationTask {
	return predicate.GenerationTask(sql.FieldNotIn(FieldProvider, vs...))
}

// ProviderGT applies the GT predicate on the "provider" field.
func ProviderGT(v string) predicate.GenerationTask {
	return predicate.GenerationTask(sql.FieldGT(FieldProvider, v))
}

// ProviderGTE applies the GTE predicate on the "provider" field.
func ProviderGTE(v string) predicate.GenerationTask {
	return predicate.GenerationTask(sql.FieldGTE(FieldProvider, v))
}

// ProviderLT applies the LT predicate on the "provider" field.
func ProviderLT(v string) predicate.GenerationTask {
	return predicate.GenerationTask(sql.FieldLT(FieldProvider, v))
}

// ProviderLTE applies the LTE predicate on the "provider" field.
func ProviderLTE(v string) predicate.GenerationTask {
	return predicate.GenerationTask(sql.FieldLTE(FieldProvider, v))
}

// ProviderContains applies the Contains predicate on the "provider" field.
func ProviderContains(v string) predicate.GenerationTask {
	return predicate.GenerationTask(sql.FieldContains(FieldProvider, v))
}

// ProviderHasPrefix applies the HasPrefix predicate on the "provider" field.
func ProviderHasPrefix(v string) predicate.GenerationTask {
	return predicate.GenerationTask(sql.FieldHasPrefix(FieldProvider, v))
}

// ProviderHasSuffix applies the HasSuffix predicate on the "provider" field.
func ProviderHasSuffix(v string) predicate.GenerationTask {
	return predicate.GenerationTask(sql.FieldHasSuffix(FieldProvider, v))
}

// ProviderEqualFold applies the EqualFold predicate on the "provider" field.
func ProviderEqualFold(v string) predicate.GenerationTask {
	return predicate.GenerationTask(sql.FieldEqualFold(FieldProvider, v))
}

// ProviderContainsFold applies the ContainsFold predicate on the "provider" field.
func ProviderContainsFold(v string) predicate.GenerationTask {
	return predicate.GenerationTask(sql.FieldContainsFold(FieldProvider, v))
}

// ProviderTaskIDEQ applies the EQ predicate on the "provider_task_id" field.
func ProviderTaskIDEQ(v string) predicate.GenerationTask {
	return predicate.GenerationTask(sql.FieldEQ(FieldProviderTaskID, v))
}

// ProviderTaskIDNEQ applies the NEQ predicate on the "provider_task_id" field.
func ProviderTaskIDNEQ(v string) predicate.GenerationTask {
	return predicate.GenerationTask(sql.FieldNEQ(FieldProviderTaskID, v))
}

// ProviderTaskIDIn applies the In predicate on the "provider_task_id" field.
func ProviderTaskIDIn(vs ...string) predicate.GenerationTask {
	return predicate.GenerationTask(sql.FieldIn(FieldProviderTaskID, vs...))
}

// ProviderTaskIDNotIn applies the NotIn predicate on the "provider_task_id" field.
func ProviderTaskIDNotIn(vs ...string) predicate.GenerationTask {
	return predicate.GenerationTask(sql.FieldNotIn(FieldProviderTaskID, vs...))
}

// ProviderTaskIDGT applies the GT predicate on the "provider_task_id" field.
func ProviderTaskIDGT(v string) predicate.GenerationTask {
	return predicate.GenerationTask(sql.FieldGT(FieldProviderTaskID, v))
}

// ProviderTaskIDGTE applies the GTE predicate on the "provider_task_id" field.
func ProviderTaskIDGTE(v string) predicate.GenerationTask {
	return predicate.GenerationTask(sql.FieldGTE(FieldProviderTaskID, v))
}

// ProviderTaskIDLT applies the LT predicate on the "provider_task_id" field.
func ProviderTaskIDLT(v string) predicate.GenerationTask {
	return predicate.GenerationTask(sql.FieldLT(FieldProviderTaskID, v))
}

// ProviderTaskIDLTE applies the LTE predicate on the "provider_task_id" field.
func ProviderTaskIDLTE(v string) predicate.GenerationTask {
	return predicate.GenerationTask(sql.FieldLTE(FieldProviderTaskID, v))
}

// ProviderTaskIDContains applies the Contains predicate on the "provider_task_id" field.
func ProviderTaskIDContains(v string) predicate.GenerationTask {
	return predicate.GenerationTask(sql.FieldContains(FieldProviderTaskID, v))
}

// ProviderTaskIDHasPrefix applies the HasPrefix predicate on the "provider_task_id" field.
func ProviderTaskIDHasPrefix(v string) predicate.GenerationTask {
	return predicate.GenerationTask(sql.FieldHasPrefix(FieldProviderTaskID, v))
}

// ProviderTaskIDHasSuffix applies the HasSuffix predicate on the "provider_task_id" field.
func ProviderTaskIDHasSuffix(v string) predicate.GenerationTask {
	return predicate.GenerationTask(sql.FieldHasSuffix(FieldProviderTaskID, v))
}

// ProviderTaskIDEqualFold applies the EqualFold predicate on the "provider_task_id" field.
func ProviderTaskIDEqualFold(v string) predicate.GenerationTask {
	return predicate.GenerationTask(sql.FieldEqualFold(FieldProviderTaskID, v))
}

// ProviderTaskIDContainsFold applies the ContainsFold predicate on the "provider_task_id" field.
func ProviderTaskIDContainsFold(v string) predicate.GenerationTask {
	return predicate.GenerationTask(sql.FieldContainsFold(FieldProviderTaskID, v))
}

// StateEQ applies the EQ predicate on the "state" field.
func StateEQ(v string) predicate.GenerationTask {
	return predicate.GenerationTask(sql.FieldEQ(FieldState, v))
}

// StateNEQ applies the NEQ predicate on the "state" field.
func StateNEQ(v string) predicate.GenerationTask {
	return predicate.GenerationTask(sql.FieldNEQ(FieldState, v))
}

// StateIn applies the In predicate on the "state" field.
func StateIn(vs ...string) predicate.GenerationTask {
	return predicate.GenerationTask(sql.FieldIn(FieldState, vs...))
}

// StateNotIn applies the NotIn predicate on the "state" field.
func StateNotIn(vs ...string) predicate.GenerationTask {
	return predicate.GenerationTask(sql.FieldNotIn(FieldState, vs...))
}

// StateGT applies the GT predicate on the "state" field.
func StateGT(v string) predicate.GenerationTask {
	return predicate.GenerationTask(sql.FieldGT(FieldState, v))
}

// StateGTE applies the GTE predicate on the "state" field.
func StateGTE(v string) predicate.GenerationTask {
	return predicate.GenerationTask(sql.FieldGTE(FieldState, v))
}

// StateLT applies the LT predicate on the "state" field.
func StateLT(v string) predicate.GenerationTask {
	return predicate.GenerationTask(sql.FieldLT(FieldState, v))
}

// StateLTE applies the LTE predicate on the "state" field.
func StateLTE(v string) predicate.GenerationTask {
	return predicate.GenerationTask(sql.FieldLTE(FieldState, v))
}

// StateContains applies the Contains predicate on the "state" field.
func StateContains(v string) predicate.GenerationTask {
	return predicate.GenerationTask(sql.FieldContains(FieldState, v))
}

// StateHasPrefix applies the HasPrefix predicate on the "state" field.
func StateHasPrefix(v string) predicate.GenerationTask {
	return predicate.GenerationTask(sql.FieldHasPrefix(FieldState, v))
}

// StateHasSuffix applies the HasSuffix predicate on the "state" field.
func StateHasSuffix(v string) predicate.GenerationTask {
	return predicate.GenerationTask(sql.FieldHasSuffix(FieldState, v))
}

// StateEqualFold applies the EqualFold predicate on the "state" field.
func StateEqualFold(v string) predicate.GenerationTask {
	return predicate.GenerationTask(sql.FieldEqualFold(FieldState, v))
}

// StateContainsFold applies the ContainsFold predicate on the "state" field.
func StateContainsFold(v string) predicate.GenerationTask {
	return predicate.GenerationTask(sql.FieldContainsFold(FieldState, v))
}

// ErrorCodeEQ applies the EQ predicate on the "error_code" field.
func ErrorCodeEQ(v int32) predicate.GenerationTask {
	return predicate.GenerationTask(sql.FieldEQ(FieldErrorCode, v))
}

// ErrorCodeNEQ applies the NEQ predicate on the "error_code" field.
func ErrorCodeNEQ(v int32) predicate.GenerationTask {
	return predicate.GenerationTask(sql.FieldNEQ(FieldErrorCode, v))
}

// ErrorCodeIn applies the In predicate on the "error_code" field.
func ErrorCodeIn(vs ...int32) predicate.GenerationTask {
	return predicate.GenerationTask(sql.FieldIn(FieldErrorCode, vs...))
}

// ErrorCodeNotIn applies the NotIn predicate on the "error_code" field.
func ErrorCodeNotIn(vs ...int32) predicate.GenerationTask {
	return predicate.GenerationTask(sql.FieldNotIn(FieldErrorCode, vs...))
}

// ErrorCodeGT applies the GT predicate on the "error_code" field.
func ErrorCodeGT(v int32) predicate.GenerationTask {
	return predicate.GenerationTask(sql.FieldGT(FieldErrorCode, v))
}

// ErrorCodeGTE applies the GTE predicate on the "error_code" field.
func ErrorCodeGTE(v int32) predicate.GenerationTask {
	return predicate.GenerationTask(sql.FieldGTE(FieldErrorCode, v))
}

// ErrorCodeLT applies the LT predicate on the "error_code" field.
func ErrorCodeLT(v int32) predicate.GenerationTask {
	return predicate.GenerationTask(sql.FieldLT(FieldErrorCode, v))
}

// ErrorCodeLTE applies the LTE predicate on the "error_code" field.
func ErrorCodeLTE(v int32) predicate.GenerationTask {
	return predicate.GenerationTask(sql.FieldLTE(FieldErrorCode, v))
}

// ErrorMessageEQ applies the EQ predicate on the "error_message" field.
func ErrorMessageEQ(v string) predicate.GenerationTask {
	return predicate.GenerationTask(sql.FieldEQ(FieldErrorMessage, v))
}

// ErrorMessageNEQ applies the NEQ predicate on the "error_message" field.
func ErrorMessageNEQ(v string) predicate.GenerationTask {
	return predicate.GenerationTask(sql.FieldNEQ(FieldErrorMessage, v))
}

// ErrorMessageIn applies the In predicate on the "error_message" field.
func ErrorMessageIn(vs ...string) predicate.GenerationTask {
	return predicate.GenerationTask(sql.FieldIn(FieldErrorMessage, vs...))
}

// ErrorMessageNotIn applies the NotIn predicate on the "error_message" field.
func ErrorMessageNotIn(vs ...string) predicate.GenerationTask {
	return predicate.GenerationTask(sql.FieldNotIn(FieldErrorMessage, vs...))
}

// ErrorMessageGT applies the GT predicate on the "error_message" field.
func ErrorMessageGT(v string) predicate.GenerationTask {
	return predicate.GenerationTask(sql.FieldGT(FieldErrorMessage, v))
}

// ErrorMessageGTE applies the GTE predicate on the "error_message" field.
func ErrorMessageGTE(v string) predicate.GenerationTask {
	return predicate.GenerationTask(sql.FieldGTE(FieldErrorMessage, v))
}

// ErrorMessageLT applies the LT predicate on the "error_message" field.
func ErrorMessageLT(v string) predicate.GenerationTask {
	return predicate.GenerationTask(sql.FieldLT(FieldErrorMessage, v))
}

// ErrorMessageLTE applies the LTE predicate on the "error_message" field.
func ErrorMessageLTE(v string) predicate.GenerationTask {
	return predicate.GenerationTask(sql.FieldLTE(FieldErrorMessage, v))
}

// ErrorMessageContains applies the Contains predicate on the "error_message" field.
func ErrorMessageContains(v string) predicate.GenerationTask {
	return predicate.GenerationTask(sql.FieldContains(FieldErrorMessage, v))
}

// ErrorMessageHasPrefix applies the HasPrefix predicate on the "error_message" field.
func ErrorMessageHasPrefix(v string) predicate.GenerationTask {
	return predicate.GenerationTask(sql.FieldHasPrefix(FieldErrorMessage, v))
}

// ErrorMessageHasSuffix applies the HasSuffix predicate on the "error_message" field.
func ErrorMessageHasSuffix(v string) predicate.GenerationTask {
	return predicate.GenerationTask(sql.FieldHasSuffix(FieldErrorMessage, v))
}

// ErrorMessageEqualFold applies the EqualFold predicate on the "error_message" field.
func ErrorMessageEqualFold(v string) predicate.GenerationTask {
	return predicate.GenerationTask(sql.FieldEqualFold(FieldErrorMessage, v))
}

// ErrorMessageContainsFold applies the ContainsFold predicate on the "error_message" field.
func ErrorMessageContainsFold(v string) predicate.GenerationTask {
	return predicate.GenerationTask(sql.FieldContainsFold(FieldErrorMessage, v))
}

// ErrorReasonEQ applies the EQ predicate on the "error_reason" field.
func ErrorReasonEQ(v string) predicate.GenerationTask {
	return predicate.GenerationTask(sql.FieldEQ(FieldErrorReason, v))
}

// ErrorReasonNEQ applies the NEQ predicate on the "error_reason" field.
func ErrorReasonNEQ(v string) predicate.GenerationTask {
	return predicate.GenerationTask(sql.FieldNEQ(FieldErrorReason, v))
}

// ErrorReasonIn applies the In predicate on the "error_reason" field.
func ErrorReasonIn(vs ...string) predicate.GenerationTask {
	return predicate.GenerationTask(sql.FieldIn(FieldErrorReason, vs...))
}

// ErrorReasonNotIn applies the NotIn predicate on the "error_reason" field.
func ErrorReasonNotIn(vs ...string) predicate.GenerationTask {
	return predicate.GenerationTask(sql.FieldNotIn(FieldErrorReason, vs...))
}

// ErrorReasonGT applies the GT predicate on the "error_reason" field.
func ErrorReasonGT(v string) predicate.GenerationTask {
	return predicate.GenerationTask(sql.FieldGT(FieldErrorReason, v))
}

// ErrorReasonGTE applies the GTE predicate on the "error_reason" field.
func ErrorReasonGTE(v string) predicate.GenerationTask {
	return predicate.GenerationTask(sql.FieldGTE(FieldErrorReason, v))
}

// ErrorReasonLT applies the LT predicate on the "error_reason" field.
func ErrorReasonLT(v string) predicate.GenerationTask {
	return predicate.GenerationTask(sql.FieldLT(FieldErrorReason, v))
}

// ErrorReasonLTE applies the LTE predicate on the "error_reason" field.
func ErrorReasonLTE(v string) predicate.GenerationTask {
	return predicate.GenerationTask(sql.FieldLTE(FieldErrorReason, v))
}

// ErrorReasonContains applies the Contains predicate on the "error_reason" field.
func ErrorReasonContains(v string) predicate.GenerationTask {
	return predicate.GenerationTask(sql.FieldContains(FieldErrorReason, v))
}

// ErrorReasonHasPrefix applies the HasPrefix predicate on the "error_reason" field.
func ErrorReasonHasPrefix(v string) predicate.GenerationTask {
	return predicate.GenerationTask(sql.FieldHasPrefix(FieldErrorReason, v))
}

// ErrorReasonHasSuffix applies the HasSuffix predicate on the "error_reason" field.
func ErrorReasonHasSuffix(v string) predicate.GenerationTask {
	return predicate.GenerationTask(sql.FieldHasSuffix(FieldErrorReason, v))
}

// ErrorReasonEqualFold applies the EqualFold predicate on the "error_reason" field.
func ErrorReasonEqualFold(v string) predicate.GenerationTask {
	return predicate.GenerationTask(sql.FieldEqualFold(FieldErrorReason, v))
}

// ErrorReasonContainsFold applies the ContainsFold predicate on the "error_reason" field.
func ErrorReasonContainsFold(v string) predicate.GenerationTask {
	return predicate.GenerationTask(sql.FieldContainsFold(FieldErrorReason, v))
}

// CreatedAtEQ applies the EQ predicate on the "created_at" field.
func CreatedAtEQ(v time.Time) predicate.GenerationTask {
	return predicate.GenerationTask(sql.FieldEQ(FieldCreatedAt, v))
}

// CreatedAtNEQ applies the NEQ predicate on the "created_at" field.
func CreatedAtNEQ(v time.Time) predicate.GenerationTask {
	return predicate.GenerationTask(sql.FieldNEQ(FieldCreatedAt, v))
}

// CreatedAtIn applies the In predicate on the "created_at" field.
func CreatedAtIn(vs ...time.Time) predicate.GenerationTask {
	return predicate.GenerationTask(sql.FieldIn(FieldCreatedAt, vs...))
}

// CreatedAtNotIn applies the NotIn predicate on the "created_at" field.
func CreatedAtNotIn(vs ...time.Time) predicate.GenerationTask {
	return predicate.GenerationTask(sql.FieldNotIn(FieldCreatedAt, vs...))
}

// CreatedAtGT applies the GT predicate on the "created_at" field.
func CreatedAtGT(v time.Time) predicate.GenerationTask {
	return predicate.GenerationTask(sql.FieldGT(FieldCreatedAt, v))
}

// CreatedAtGTE applies the GTE predicate on the "created_at" field.
func CreatedAtGTE(v time.Time) predicate.GenerationTask {
	return predicate.GenerationTask(sql.FieldGTE(FieldCreatedAt, v))
}

// CreatedAtLT applies the LT predicate on the "created_at" field.
func CreatedAtLT(v time.Time) predicate.GenerationTask {
	return predicate.GenerationTask(sql.FieldLT(FieldCreatedAt, v))
}

// CreatedAtLTE applies the LTE predicate on the "created_at" field.
func CreatedAtLTE(v time.Time) predicate.GenerationTask {
	return predicate.GenerationTask(sql.FieldLTE(FieldCreatedAt, v))
}

// UpdatedAtEQ applies the EQ predicate on the "updated_at" field.
func UpdatedAtEQ(v time.Time) predicate.GenerationTask {
	return predicate.GenerationTask(sql.FieldEQ(FieldUpdatedAt, v))
}

// UpdatedAtNEQ applies the NEQ predicate on the "updated_at" field.
func UpdatedAtNEQ(v time.Time) predicate.GenerationTask {
	return predicate.GenerationTask(sql.FieldNEQ(FieldUpdatedAt, v))
}

// UpdatedAtIn applies the In predicate on the "updated_at" field.
func UpdatedAtIn(vs ...time.Time) predicate.GenerationTask {
	return predicate.GenerationTask(sql.FieldIn(FieldUpdatedAt, vs...))
}

// UpdatedAtNotIn applies the NotIn predicate on the "updated_at" field.
func UpdatedAtNotIn(vs ...time.Time) predicate.GenerationTask {
	return predicate.GenerationTask(sql.FieldNotIn(FieldUpdatedAt, vs...))
}

// UpdatedAtGT applies the GT predicate on the "updated_at" field.
func UpdatedAtGT(v time.Time) predicate.GenerationTask {
	return predicate.GenerationTask(sql.FieldGT(FieldUpdatedAt, v))
}

// UpdatedAtGTE applies the GTE predicate on the "updated_at" field.
func UpdatedAtGTE(v time.Time) predicate.GenerationTask {
	return predicate.GenerationTask(sql.FieldGTE(FieldUpdatedAt, v))
}

// UpdatedAtLT applies the LT predicate on the "updated_at" field.
func UpdatedAtLT(v time.Time) predicate.GenerationTask {
	return predicate.GenerationTask(sql.FieldLT(FieldUpdatedAt, v))
}

// UpdatedAtLTE applies the LTE predicate on the "updated_at" field.
func UpdatedAtLTE(v time.Time) predicate.GenerationTask {
	return predicate.GenerationTask(sql.FieldLTE(FieldUpdatedAt, v))
}

// And groups predicates with the AND operator between them.
func And(predicates ...predicate.GenerationTask) predicate.GenerationTask {
	return predicate.GenerationTask(sql.AndPredicates(predicates...))
}

// Or groups predicates with the OR operator between them.
func Or(predicates ...predicate.GenerationTask) predicate.GenerationTask {
	return predicate.GenerationTask(sql.OrPredicates(predicates...))
}

// Not applies the not operator on the given predicate.
func Not(p predicate.GenerationTask) predicate.GenerationTask {
	return predicate.GenerationTask(sql.NotPredicates(p))
}
