// Code generated by ent, DO NOT EDIT.

package migrate

import (
	"entgo.io/ent/dialect/entsql"
	"entgo.io/ent/dialect/sql/schema"
	"entgo.io/ent/schema/field"
)

var (
	// GenerationTaskColumns holds the columns for the "generation_task" table.
	GenerationTaskColumns = []*schema.Column{
		{Name: "task_id", Type: field.TypeString},
		{Name: "caller", Type: field.TypeString},
		{Name: "request_id", Type: field.TypeString},
		{Name: "request_hash", Type: field.TypeString},
		{Name: "model", Type: field.TypeString},
		{Name: "provider", Type: field.TypeString},
		{Name: "provider_task_id", Type: field.TypeString, Default: ""},
		{Name: "state", Type: field.TypeString},
		{Name: "error_code", Type: field.TypeInt32, Default: 0},
		{Name: "error_message", Type: field.TypeString, Default: ""},
		{Name: "error_reason", Type: field.TypeString, Default: ""},
		{Name: "created_at", Type: field.TypeTime, SchemaType: map[string]string{"postgres": "timestamptz"}},
		{Name: "updated_at", Type: field.TypeTime, SchemaType: map[string]string{"postgres": "timestamptz"}},
	}
	// GenerationTaskTable holds the schema information for the "generation_task" table.
	GenerationTaskTable = &schema.Table{
		Name:       "generation_task",
		Columns:    GenerationTaskColumns,
		PrimaryKey: []*schema.Column{GenerationTaskColumns[0]},
		Indexes: []*schema.Index{
			{
				Name:    "generationtask_caller_request_id",
				Unique:  true,
				Columns: []*schema.Column{GenerationTaskColumns[1], GenerationTaskColumns[2]},
			},
		},
	}
	// Tables holds all the tables in the schema.
	Tables = []*schema.Table{
		GenerationTaskTable,
	}
)

func init() {
	GenerationTaskTable.Annotation = &entsql.Annotation{
		Table: "generation_task",
	}
}
