// Code generated by ent, DO NOT EDIT.

package migrate

import (
	"entgo.io/ent/dialect/entsql"
	"entgo.io/ent/dialect/sql/schema"
	"entgo.io/ent/schema/field"
)

var (
	// GenerationTaskColumns holds the columns for the "generation_task" table.
	GenerationTaskColumns = []*schema.Column{
		{Name: "task_id", Type: field.TypeString},
		{Name: "caller", Type: field.TypeString},
		{Name: "request_id", Type: field.TypeString},
		{Name: "request_hash", Type: field.TypeString},
		{Name: "model", Type: field.TypeString},
		{Name: "provider", Type: field.TypeString},
		{Name: "provider_task_id", Type: field.TypeString, Default: ""},
		{Name: "state", Type: field.TypeString},
		{Name: "error_code", Type: field.TypeInt32, Default: 0},
		{Name: "error_message", Type: field.TypeString, Default: ""},
		{Name: "error_reason", Type: field.TypeString, Default: ""},
		{Name: "created_at", Type: field.TypeTime, SchemaType: map[string]string{"postgres": "timestamptz"}},
		{Name: "updated_at", Type: field.TypeTime, SchemaType: map[string]string{"postgres": "timestamptz"}},
	}
	// GenerationTaskTable holds the schema information for the "generation_task" table.
	GenerationTaskTable = &schema.Table{
		Name:       "generation_task",
		Columns:    GenerationTaskColumns,
		PrimaryKey: []*schema.Column{GenerationTaskColumns[0]},
		Indexes: []*schema.Index{
			{
				Name:    "generationtask_caller_request_id",
				Unique:  true,
				Columns: []*schema.Column{GenerationTaskColumns[1], GenerationTaskColumns[2]},
			},
		},
	}
	// ModelhubAPIKeyColumns holds the columns for the "modelhub_api_key" table.
	ModelhubAPIKeyColumns = []*schema.Column{
		{Name: "id", Type: field.TypeString},
		{Name: "principal_id", Type: field.TypeString},
		{Name: "key_id", Type: field.TypeString, Unique: true},
		{Name: "secret_sha256", Type: field.TypeString},
		{Name: "name", Type: field.TypeString, Default: ""},
		{Name: "created_by", Type: field.TypeString},
		{Name: "created_at", Type: field.TypeTime, SchemaType: map[string]string{"postgres": "timestamptz"}},
		{Name: "expires_at", Type: field.TypeTime, SchemaType: map[string]string{"postgres": "timestamptz"}},
		{Name: "revoked_at", Type: field.TypeTime, Nullable: true, SchemaType: map[string]string{"postgres": "timestamptz"}},
	}
	// ModelhubAPIKeyTable holds the schema information for the "modelhub_api_key" table.
	ModelhubAPIKeyTable = &schema.Table{
		Name:       "modelhub_api_key",
		Columns:    ModelhubAPIKeyColumns,
		PrimaryKey: []*schema.Column{ModelhubAPIKeyColumns[0]},
		Indexes: []*schema.Index{
			{
				Name:    "modelhubapikey_created_by",
				Unique:  false,
				Columns: []*schema.Column{ModelhubAPIKeyColumns[5]},
			},
			{
				Name:    "modelhubapikey_principal_id",
				Unique:  false,
				Columns: []*schema.Column{ModelhubAPIKeyColumns[1]},
			},
		},
	}
	// Tables holds all the tables in the schema.
	Tables = []*schema.Table{
		GenerationTaskTable,
		ModelhubAPIKeyTable,
	}
)

func init() {
	GenerationTaskTable.Annotation = &entsql.Annotation{
		Table: "generation_task",
	}
	ModelhubAPIKeyTable.Annotation = &entsql.Annotation{
		Table: "modelhub_api_key",
	}
}
