// Code generated by ent, DO NOT EDIT.

package migrate

import (
	"entgo.io/ent/dialect/entsql"
	"entgo.io/ent/dialect/sql/schema"
	"entgo.io/ent/schema/field"
)

var (
	// GenerationTaskColumns holds the columns for the "generation_task" table.
	GenerationTaskColumns = []*schema.Column{
		{Name: "task_id", Type: field.TypeString},
		{Name: "caller", Type: field.TypeString},
		{Name: "request_id", Type: field.TypeString},
		{Name: "request_hash", Type: field.TypeString},
		{Name: "model", Type: field.TypeString},
		{Name: "provider", Type: field.TypeString},
		{Name: "provider_task_id", Type: field.TypeString, Default: ""},
		{Name: "state", Type: field.TypeString},
		{Name: "error_code", Type: field.TypeInt32, Default: 0},
		{Name: "error_message", Type: field.TypeString, Default: ""},
		{Name: "error_reason", Type: field.TypeString, Default: ""},
		{Name: "created_at", Type: field.TypeTime, SchemaType: map[string]string{"postgres": "timestamptz"}},
		{Name: "updated_at", Type: field.TypeTime, SchemaType: map[string]string{"postgres": "timestamptz"}},
	}
	// GenerationTaskTable holds the schema information for the "generation_task" table.
	GenerationTaskTable = &schema.Table{
		Name:       "generation_task",
		Columns:    GenerationTaskColumns,
		PrimaryKey: []*schema.Column{GenerationTaskColumns[0]},
		Indexes: []*schema.Index{
			{
				Name:    "generationtask_caller_request_id",
				Unique:  true,
				Columns: []*schema.Column{GenerationTaskColumns[1], GenerationTaskColumns[2]},
			},
		},
	}
	// ModelCallColumns holds the columns for the "model_call" table.
	ModelCallColumns = []*schema.Column{
		{Name: "call_id", Type: field.TypeString},
		{Name: "generation_task_id", Type: field.TypeString, Unique: true, Nullable: true},
		{Name: "caller_service", Type: field.TypeString, Default: "unknown"},
		{Name: "business_scene", Type: field.TypeString, Default: "unknown"},
		{Name: "operation", Type: field.TypeString},
		{Name: "capability", Type: field.TypeString},
		{Name: "model", Type: field.TypeString},
		{Name: "provider", Type: field.TypeString},
		{Name: "status", Type: field.TypeString},
		{Name: "delivery_status", Type: field.TypeString, Default: "ok"},
		{Name: "error_category", Type: field.TypeString, Default: ""},
		{Name: "error_code", Type: field.TypeString, Default: ""},
		{Name: "error_reason", Type: field.TypeString, Default: ""},
		{Name: "error_message", Type: field.TypeString, Default: ""},
		{Name: "input_tokens", Type: field.TypeInt64, Nullable: true},
		{Name: "output_tokens", Type: field.TypeInt64, Nullable: true},
		{Name: "total_tokens", Type: field.TypeInt64, Nullable: true},
		{Name: "cached_tokens", Type: field.TypeInt64, Nullable: true},
		{Name: "reasoning_tokens", Type: field.TypeInt64, Nullable: true},
		{Name: "image_count", Type: field.TypeInt, Nullable: true},
		{Name: "image_size", Type: field.TypeString, Default: ""},
		{Name: "image_aspect_ratio", Type: field.TypeString, Default: ""},
		{Name: "video_count", Type: field.TypeInt, Nullable: true},
		{Name: "video_resolution", Type: field.TypeString, Default: ""},
		{Name: "video_duration_seconds", Type: field.TypeInt, Nullable: true},
		{Name: "video_aspect_ratio", Type: field.TypeString, Default: ""},
		{Name: "latency_ms", Type: field.TypeInt64, Default: 0},
		{Name: "started_at", Type: field.TypeTime, SchemaType: map[string]string{"postgres": "timestamptz"}},
		{Name: "finished_at", Type: field.TypeTime, Nullable: true, SchemaType: map[string]string{"postgres": "timestamptz"}},
		{Name: "input_payload", Type: field.TypeJSON, SchemaType: map[string]string{"postgres": "jsonb"}},
		{Name: "output_payload", Type: field.TypeJSON, SchemaType: map[string]string{"postgres": "jsonb"}},
		{Name: "usage_detail", Type: field.TypeJSON, SchemaType: map[string]string{"postgres": "jsonb"}},
		{Name: "created_at", Type: field.TypeTime, SchemaType: map[string]string{"postgres": "timestamptz"}},
		{Name: "updated_at", Type: field.TypeTime, SchemaType: map[string]string{"postgres": "timestamptz"}},
	}
	// ModelCallTable holds the schema information for the "model_call" table.
	ModelCallTable = &schema.Table{
		Name:       "model_call",
		Columns:    ModelCallColumns,
		PrimaryKey: []*schema.Column{ModelCallColumns[0]},
		Indexes: []*schema.Index{
			{
				Name:    "modelcall_started_at",
				Unique:  false,
				Columns: []*schema.Column{ModelCallColumns[27]},
			},
			{
				Name:    "modelcall_caller_service_started_at",
				Unique:  false,
				Columns: []*schema.Column{ModelCallColumns[2], ModelCallColumns[27]},
			},
			{
				Name:    "modelcall_business_scene_started_at",
				Unique:  false,
				Columns: []*schema.Column{ModelCallColumns[3], ModelCallColumns[27]},
			},
			{
				Name:    "modelcall_model_started_at",
				Unique:  false,
				Columns: []*schema.Column{ModelCallColumns[6], ModelCallColumns[27]},
			},
			{
				Name:    "modelcall_status_started_at",
				Unique:  false,
				Columns: []*schema.Column{ModelCallColumns[8], ModelCallColumns[27]},
			},
		},
	}
	// ModelhubAPIKeyColumns holds the columns for the "modelhub_api_key" table.
	ModelhubAPIKeyColumns = []*schema.Column{
		{Name: "id", Type: field.TypeString},
		{Name: "principal_id", Type: field.TypeString},
		{Name: "key_id", Type: field.TypeString, Unique: true},
		{Name: "secret_sha256", Type: field.TypeString},
		{Name: "name", Type: field.TypeString, Default: ""},
		{Name: "created_by", Type: field.TypeString},
		{Name: "created_at", Type: field.TypeTime, SchemaType: map[string]string{"postgres": "timestamptz"}},
		{Name: "expires_at", Type: field.TypeTime, Nullable: true, SchemaType: map[string]string{"postgres": "timestamptz"}},
		{Name: "revoked_at", Type: field.TypeTime, Nullable: true, SchemaType: map[string]string{"postgres": "timestamptz"}},
	}
	// ModelhubAPIKeyTable holds the schema information for the "modelhub_api_key" table.
	ModelhubAPIKeyTable = &schema.Table{
		Name:       "modelhub_api_key",
		Columns:    ModelhubAPIKeyColumns,
		PrimaryKey: []*schema.Column{ModelhubAPIKeyColumns[0]},
		Indexes: []*schema.Index{
			{
				Name:    "modelhubapikey_created_by",
				Unique:  false,
				Columns: []*schema.Column{ModelhubAPIKeyColumns[5]},
			},
			{
				Name:    "modelhubapikey_principal_id",
				Unique:  false,
				Columns: []*schema.Column{ModelhubAPIKeyColumns[1]},
			},
		},
	}
	// Tables holds all the tables in the schema.
	Tables = []*schema.Table{
		GenerationTaskTable,
		ModelCallTable,
		ModelhubAPIKeyTable,
	}
)

func init() {
	GenerationTaskTable.Annotation = &entsql.Annotation{
		Table: "generation_task",
	}
	ModelCallTable.Annotation = &entsql.Annotation{
		Table: "model_call",
	}
	ModelhubAPIKeyTable.Annotation = &entsql.Annotation{
		Table: "modelhub_api_key",
	}
}
