// Code generated by ent, DO NOT EDIT.

package ent

import (
	"context"
	"errors"
	"fmt"
	"time"

	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/schema/field"
	"github.com/wgdl666/wgModelHub/ent/generationtask"
	"github.com/wgdl666/wgModelHub/ent/predicate"
)

// GenerationTaskUpdate is the builder for updating GenerationTask entities.
type GenerationTaskUpdate struct {
	config
	hooks    []Hook
	mutation *GenerationTaskMutation
}

// Where appends a list predicates to the GenerationTaskUpdate builder.
func (_u *GenerationTaskUpdate) Where(ps ...predicate.GenerationTask) *GenerationTaskUpdate {
	_u.mutation.Where(ps...)
	return _u
}

// SetCaller sets the "caller" field.
func (_u *GenerationTaskUpdate) SetCaller(v string) *GenerationTaskUpdate {
	_u.mutation.SetCaller(v)
	return _u
}

// SetNillableCaller sets the "caller" field if the given value is not nil.
func (_u *GenerationTaskUpdate) SetNillableCaller(v *string) *GenerationTaskUpdate {
	if v != nil {
		_u.SetCaller(*v)
	}
	return _u
}

// SetRequestID sets the "request_id" field.
func (_u *GenerationTaskUpdate) SetRequestID(v string) *GenerationTaskUpdate {
	_u.mutation.SetRequestID(v)
	return _u
}

// SetNillableRequestID sets the "request_id" field if the given value is not nil.
func (_u *GenerationTaskUpdate) SetNillableRequestID(v *string) *GenerationTaskUpdate {
	if v != nil {
		_u.SetRequestID(*v)
	}
	return _u
}

// SetRequestHash sets the "request_hash" field.
func (_u *GenerationTaskUpdate) SetRequestHash(v string) *GenerationTaskUpdate {
	_u.mutation.SetRequestHash(v)
	return _u
}

// SetNillableRequestHash sets the "request_hash" field if the given value is not nil.
func (_u *GenerationTaskUpdate) SetNillableRequestHash(v *string) *GenerationTaskUpdate {
	if v != nil {
		_u.SetRequestHash(*v)
	}
	return _u
}

// SetModel sets the "model" field.
func (_u *GenerationTaskUpdate) SetModel(v string) *GenerationTaskUpdate {
	_u.mutation.SetModel(v)
	return _u
}

// SetNillableModel sets the "model" field if the given value is not nil.
func (_u *GenerationTaskUpdate) SetNillableModel(v *string) *GenerationTaskUpdate {
	if v != nil {
		_u.SetModel(*v)
	}
	return _u
}

// SetProvider sets the "provider" field.
func (_u *GenerationTaskUpdate) SetProvider(v string) *GenerationTaskUpdate {
	_u.mutation.SetProvider(v)
	return _u
}

// SetNillableProvider sets the "provider" field if the given value is not nil.
func (_u *GenerationTaskUpdate) SetNillableProvider(v *string) *GenerationTaskUpdate {
	if v != nil {
		_u.SetProvider(*v)
	}
	return _u
}

// SetProviderTaskID sets the "provider_task_id" field.
func (_u *GenerationTaskUpdate) SetProviderTaskID(v string) *GenerationTaskUpdate {
	_u.mutation.SetProviderTaskID(v)
	return _u
}

// SetNillableProviderTaskID sets the "provider_task_id" field if the given value is not nil.
func (_u *GenerationTaskUpdate) SetNillableProviderTaskID(v *string) *GenerationTaskUpdate {
	if v != nil {
		_u.SetProviderTaskID(*v)
	}
	return _u
}

// SetState sets the "state" field.
func (_u *GenerationTaskUpdate) SetState(v string) *GenerationTaskUpdate {
	_u.mutation.SetState(v)
	return _u
}

// SetNillableState sets the "state" field if the given value is not nil.
func (_u *GenerationTaskUpdate) SetNillableState(v *string) *GenerationTaskUpdate {
	if v != nil {
		_u.SetState(*v)
	}
	return _u
}

// SetErrorCode sets the "error_code" field.
func (_u *GenerationTaskUpdate) SetErrorCode(v int32) *GenerationTaskUpdate {
	_u.mutation.ResetErrorCode()
	_u.mutation.SetErrorCode(v)
	return _u
}

// SetNillableErrorCode sets the "error_code" field if the given value is not nil.
func (_u *GenerationTaskUpdate) SetNillableErrorCode(v *int32) *GenerationTaskUpdate {
	if v != nil {
		_u.SetErrorCode(*v)
	}
	return _u
}

// AddErrorCode adds value to the "error_code" field.
func (_u *GenerationTaskUpdate) AddErrorCode(v int32) *GenerationTaskUpdate {
	_u.mutation.AddErrorCode(v)
	return _u
}

// SetErrorMessage sets the "error_message" field.
func (_u *GenerationTaskUpdate) SetErrorMessage(v string) *GenerationTaskUpdate {
	_u.mutation.SetErrorMessage(v)
	return _u
}

// SetNillableErrorMessage sets the "error_message" field if the given value is not nil.
func (_u *GenerationTaskUpdate) SetNillableErrorMessage(v *string) *GenerationTaskUpdate {
	if v != nil {
		_u.SetErrorMessage(*v)
	}
	return _u
}

// SetErrorReason sets the "error_reason" field.
func (_u *GenerationTaskUpdate) SetErrorReason(v string) *GenerationTaskUpdate {
	_u.mutation.SetErrorReason(v)
	return _u
}

// SetNillableErrorReason sets the "error_reason" field if the given value is not nil.
func (_u *GenerationTaskUpdate) SetNillableErrorReason(v *string) *GenerationTaskUpdate {
	if v != nil {
		_u.SetErrorReason(*v)
	}
	return _u
}

// SetUpdatedAt sets the "updated_at" field.
func (_u *GenerationTaskUpdate) SetUpdatedAt(v time.Time) *GenerationTaskUpdate {
	_u.mutation.SetUpdatedAt(v)
	return _u
}

// Mutation returns the GenerationTaskMutation object of the builder.
func (_u *GenerationTaskUpdate) Mutation() *GenerationTaskMutation {
	return _u.mutation
}

// Save executes the query and returns the number of nodes affected by the update operation.
func (_u *GenerationTaskUpdate) Save(ctx context.Context) (int, error) {
	_u.defaults()
	return withHooks(ctx, _u.sqlSave, _u.mutation, _u.hooks)
}

// SaveX is like Save, but panics if an error occurs.
func (_u *GenerationTaskUpdate) SaveX(ctx context.Context) int {
	affected, err := _u.Save(ctx)
	if err != nil {
		panic(err)
	}
	return affected
}

// Exec executes the query.
func (_u *GenerationTaskUpdate) Exec(ctx context.Context) error {
	_, err := _u.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_u *GenerationTaskUpdate) ExecX(ctx context.Context) {
	if err := _u.Exec(ctx); err != nil {
		panic(err)
	}
}

// defaults sets the default values of the builder before save.
func (_u *GenerationTaskUpdate) defaults() {
	if _, ok := _u.mutation.UpdatedAt(); !ok {
		v := generationtask.UpdateDefaultUpdatedAt()
		_u.mutation.SetUpdatedAt(v)
	}
}

func (_u *GenerationTaskUpdate) sqlSave(ctx context.Context) (_node int, err error) {
	_spec := sqlgraph.NewUpdateSpec(generationtask.Table, generationtask.Columns, sqlgraph.NewFieldSpec(generationtask.FieldID, field.TypeString))
	if ps := _u.mutation.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	if value, ok := _u.mutation.Caller(); ok {
		_spec.SetField(generationtask.FieldCaller, field.TypeString, value)
	}
	if value, ok := _u.mutation.RequestID(); ok {
		_spec.SetField(generationtask.FieldRequestID, field.TypeString, value)
	}
	if value, ok := _u.mutation.RequestHash(); ok {
		_spec.SetField(generationtask.FieldRequestHash, field.TypeString, value)
	}
	if value, ok := _u.mutation.Model(); ok {
		_spec.SetField(generationtask.FieldModel, field.TypeString, value)
	}
	if value, ok := _u.mutation.Provider(); ok {
		_spec.SetField(generationtask.FieldProvider, field.TypeString, value)
	}
	if value, ok := _u.mutation.ProviderTaskID(); ok {
		_spec.SetField(generationtask.FieldProviderTaskID, field.TypeString, value)
	}
	if value, ok := _u.mutation.State(); ok {
		_spec.SetField(generationtask.FieldState, field.TypeString, value)
	}
	if value, ok := _u.mutation.ErrorCode(); ok {
		_spec.SetField(generationtask.FieldErrorCode, field.TypeInt32, value)
	}
	if value, ok := _u.mutation.AddedErrorCode(); ok {
		_spec.AddField(generationtask.FieldErrorCode, field.TypeInt32, value)
	}
	if value, ok := _u.mutation.ErrorMessage(); ok {
		_spec.SetField(generationtask.FieldErrorMessage, field.TypeString, value)
	}
	if value, ok := _u.mutation.ErrorReason(); ok {
		_spec.SetField(generationtask.FieldErrorReason, field.TypeString, value)
	}
	if value, ok := _u.mutation.UpdatedAt(); ok {
		_spec.SetField(generationtask.FieldUpdatedAt, field.TypeTime, value)
	}
	if _node, err = sqlgraph.UpdateNodes(ctx, _u.driver, _spec); err != nil {
		if _, ok := err.(*sqlgraph.NotFoundError); ok {
			err = &NotFoundError{generationtask.Label}
		} else if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return 0, err
	}
	_u.mutation.done = true
	return _node, nil
}

// GenerationTaskUpdateOne is the builder for updating a single GenerationTask entity.
type GenerationTaskUpdateOne struct {
	config
	fields   []string
	hooks    []Hook
	mutation *GenerationTaskMutation
}

// SetCaller sets the "caller" field.
func (_u *GenerationTaskUpdateOne) SetCaller(v string) *GenerationTaskUpdateOne {
	_u.mutation.SetCaller(v)
	return _u
}

// SetNillableCaller sets the "caller" field if the given value is not nil.
func (_u *GenerationTaskUpdateOne) SetNillableCaller(v *string) *GenerationTaskUpdateOne {
	if v != nil {
		_u.SetCaller(*v)
	}
	return _u
}

// SetRequestID sets the "request_id" field.
func (_u *GenerationTaskUpdateOne) SetRequestID(v string) *GenerationTaskUpdateOne {
	_u.mutation.SetRequestID(v)
	return _u
}

// SetNillableRequestID sets the "request_id" field if the given value is not nil.
func (_u *GenerationTaskUpdateOne) SetNillableRequestID(v *string) *GenerationTaskUpdateOne {
	if v != nil {
		_u.SetRequestID(*v)
	}
	return _u
}

// SetRequestHash sets the "request_hash" field.
func (_u *GenerationTaskUpdateOne) SetRequestHash(v string) *GenerationTaskUpdateOne {
	_u.mutation.SetRequestHash(v)
	return _u
}

// SetNillableRequestHash sets the "request_hash" field if the given value is not nil.
func (_u *GenerationTaskUpdateOne) SetNillableRequestHash(v *string) *GenerationTaskUpdateOne {
	if v != nil {
		_u.SetRequestHash(*v)
	}
	return _u
}

// SetModel sets the "model" field.
func (_u *GenerationTaskUpdateOne) SetModel(v string) *GenerationTaskUpdateOne {
	_u.mutation.SetModel(v)
	return _u
}

// SetNillableModel sets the "model" field if the given value is not nil.
func (_u *GenerationTaskUpdateOne) SetNillableModel(v *string) *GenerationTaskUpdateOne {
	if v != nil {
		_u.SetModel(*v)
	}
	return _u
}

// SetProvider sets the "provider" field.
func (_u *GenerationTaskUpdateOne) SetProvider(v string) *GenerationTaskUpdateOne {
	_u.mutation.SetProvider(v)
	return _u
}

// SetNillableProvider sets the "provider" field if the given value is not nil.
func (_u *GenerationTaskUpdateOne) SetNillableProvider(v *string) *GenerationTaskUpdateOne {
	if v != nil {
		_u.SetProvider(*v)
	}
	return _u
}

// SetProviderTaskID sets the "provider_task_id" field.
func (_u *GenerationTaskUpdateOne) SetProviderTaskID(v string) *GenerationTaskUpdateOne {
	_u.mutation.SetProviderTaskID(v)
	return _u
}

// SetNillableProviderTaskID sets the "provider_task_id" field if the given value is not nil.
func (_u *GenerationTaskUpdateOne) SetNillableProviderTaskID(v *string) *GenerationTaskUpdateOne {
	if v != nil {
		_u.SetProviderTaskID(*v)
	}
	return _u
}

// SetState sets the "state" field.
func (_u *GenerationTaskUpdateOne) SetState(v string) *GenerationTaskUpdateOne {
	_u.mutation.SetState(v)
	return _u
}

// SetNillableState sets the "state" field if the given value is not nil.
func (_u *GenerationTaskUpdateOne) SetNillableState(v *string) *GenerationTaskUpdateOne {
	if v != nil {
		_u.SetState(*v)
	}
	return _u
}

// SetErrorCode sets the "error_code" field.
func (_u *GenerationTaskUpdateOne) SetErrorCode(v int32) *GenerationTaskUpdateOne {
	_u.mutation.ResetErrorCode()
	_u.mutation.SetErrorCode(v)
	return _u
}

// SetNillableErrorCode sets the "error_code" field if the given value is not nil.
func (_u *GenerationTaskUpdateOne) SetNillableErrorCode(v *int32) *GenerationTaskUpdateOne {
	if v != nil {
		_u.SetErrorCode(*v)
	}
	return _u
}

// AddErrorCode adds value to the "error_code" field.
func (_u *GenerationTaskUpdateOne) AddErrorCode(v int32) *GenerationTaskUpdateOne {
	_u.mutation.AddErrorCode(v)
	return _u
}

// SetErrorMessage sets the "error_message" field.
func (_u *GenerationTaskUpdateOne) SetErrorMessage(v string) *GenerationTaskUpdateOne {
	_u.mutation.SetErrorMessage(v)
	return _u
}

// SetNillableErrorMessage sets the "error_message" field if the given value is not nil.
func (_u *GenerationTaskUpdateOne) SetNillableErrorMessage(v *string) *GenerationTaskUpdateOne {
	if v != nil {
		_u.SetErrorMessage(*v)
	}
	return _u
}

// SetErrorReason sets the "error_reason" field.
func (_u *GenerationTaskUpdateOne) SetErrorReason(v string) *GenerationTaskUpdateOne {
	_u.mutation.SetErrorReason(v)
	return _u
}

// SetNillableErrorReason sets the "error_reason" field if the given value is not nil.
func (_u *GenerationTaskUpdateOne) SetNillableErrorReason(v *string) *GenerationTaskUpdateOne {
	if v != nil {
		_u.SetErrorReason(*v)
	}
	return _u
}

// SetUpdatedAt sets the "updated_at" field.
func (_u *GenerationTaskUpdateOne) SetUpdatedAt(v time.Time) *GenerationTaskUpdateOne {
	_u.mutation.SetUpdatedAt(v)
	return _u
}

// Mutation returns the GenerationTaskMutation object of the builder.
func (_u *GenerationTaskUpdateOne) Mutation() *GenerationTaskMutation {
	return _u.mutation
}

// Where appends a list predicates to the GenerationTaskUpdate builder.
func (_u *GenerationTaskUpdateOne) Where(ps ...predicate.GenerationTask) *GenerationTaskUpdateOne {
	_u.mutation.Where(ps...)
	return _u
}

// Select allows selecting one or more fields (columns) of the returned entity.
// The default is selecting all fields defined in the entity schema.
func (_u *GenerationTaskUpdateOne) Select(field string, fields ...string) *GenerationTaskUpdateOne {
	_u.fields = append([]string{field}, fields...)
	return _u
}

// Save executes the query and returns the updated GenerationTask entity.
func (_u *GenerationTaskUpdateOne) Save(ctx context.Context) (*GenerationTask, error) {
	_u.defaults()
	return withHooks(ctx, _u.sqlSave, _u.mutation, _u.hooks)
}

// SaveX is like Save, but panics if an error occurs.
func (_u *GenerationTaskUpdateOne) SaveX(ctx context.Context) *GenerationTask {
	node, err := _u.Save(ctx)
	if err != nil {
		panic(err)
	}
	return node
}

// Exec executes the query on the entity.
func (_u *GenerationTaskUpdateOne) Exec(ctx context.Context) error {
	_, err := _u.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_u *GenerationTaskUpdateOne) ExecX(ctx context.Context) {
	if err := _u.Exec(ctx); err != nil {
		panic(err)
	}
}

// defaults sets the default values of the builder before save.
func (_u *GenerationTaskUpdateOne) defaults() {
	if _, ok := _u.mutation.UpdatedAt(); !ok {
		v := generationtask.UpdateDefaultUpdatedAt()
		_u.mutation.SetUpdatedAt(v)
	}
}

func (_u *GenerationTaskUpdateOne) sqlSave(ctx context.Context) (_node *GenerationTask, err error) {
	_spec := sqlgraph.NewUpdateSpec(generationtask.Table, generationtask.Columns, sqlgraph.NewFieldSpec(generationtask.FieldID, field.TypeString))
	id, ok := _u.mutation.ID()
	if !ok {
		return nil, &ValidationError{Name: "id", err: errors.New(`ent: missing "GenerationTask.id" for update`)}
	}
	_spec.Node.ID.Value = id
	if fields := _u.fields; len(fields) > 0 {
		_spec.Node.Columns = make([]string, 0, len(fields))
		_spec.Node.Columns = append(_spec.Node.Columns, generationtask.FieldID)
		for _, f := range fields {
			if !generationtask.ValidColumn(f) {
				return nil, &ValidationError{Name: f, err: fmt.Errorf("ent: invalid field %q for query", f)}
			}
			if f != generationtask.FieldID {
				_spec.Node.Columns = append(_spec.Node.Columns, f)
			}
		}
	}
	if ps := _u.mutation.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	if value, ok := _u.mutation.Caller(); ok {
		_spec.SetField(generationtask.FieldCaller, field.TypeString, value)
	}
	if value, ok := _u.mutation.RequestID(); ok {
		_spec.SetField(generationtask.FieldRequestID, field.TypeString, value)
	}
	if value, ok := _u.mutation.RequestHash(); ok {
		_spec.SetField(generationtask.FieldRequestHash, field.TypeString, value)
	}
	if value, ok := _u.mutation.Model(); ok {
		_spec.SetField(generationtask.FieldModel, field.TypeString, value)
	}
	if value, ok := _u.mutation.Provider(); ok {
		_spec.SetField(generationtask.FieldProvider, field.TypeString, value)
	}
	if value, ok := _u.mutation.ProviderTaskID(); ok {
		_spec.SetField(generationtask.FieldProviderTaskID, field.TypeString, value)
	}
	if value, ok := _u.mutation.State(); ok {
		_spec.SetField(generationtask.FieldState, field.TypeString, value)
	}
	if value, ok := _u.mutation.ErrorCode(); ok {
		_spec.SetField(generationtask.FieldErrorCode, field.TypeInt32, value)
	}
	if value, ok := _u.mutation.AddedErrorCode(); ok {
		_spec.AddField(generationtask.FieldErrorCode, field.TypeInt32, value)
	}
	if value, ok := _u.mutation.ErrorMessage(); ok {
		_spec.SetField(generationtask.FieldErrorMessage, field.TypeString, value)
	}
	if value, ok := _u.mutation.ErrorReason(); ok {
		_spec.SetField(generationtask.FieldErrorReason, field.TypeString, value)
	}
	if value, ok := _u.mutation.UpdatedAt(); ok {
		_spec.SetField(generationtask.FieldUpdatedAt, field.TypeTime, value)
	}
	_node = &GenerationTask{config: _u.config}
	_spec.Assign = _node.assignValues
	_spec.ScanValues = _node.scanValues
	if err = sqlgraph.UpdateNode(ctx, _u.driver, _spec); err != nil {
		if _, ok := err.(*sqlgraph.NotFoundError); ok {
			err = &NotFoundError{generationtask.Label}
		} else if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return nil, err
	}
	_u.mutation.done = true
	return _node, nil
}
