// Code generated by ent, DO NOT EDIT.

package ent

import (
	"fmt"
	"strings"
	"time"

	"entgo.io/ent"
	"entgo.io/ent/dialect/sql"
	"github.com/wgdl666/wgModelHub/ent/generationtask"
)

// GenerationTask is the model entity for the GenerationTask schema.
type GenerationTask struct {
	config `json:"-"`
	// ID of the ent.
	ID string `json:"id,omitempty"`
	// Caller holds the value of the "caller" field.
	Caller string `json:"caller,omitempty"`
	// RequestID holds the value of the "request_id" field.
	RequestID string `json:"request_id,omitempty"`
	// RequestHash holds the value of the "request_hash" field.
	RequestHash string `json:"request_hash,omitempty"`
	// Model holds the value of the "model" field.
	Model string `json:"model,omitempty"`
	// Provider holds the value of the "provider" field.
	Provider string `json:"provider,omitempty"`
	// ProviderTaskID holds the value of the "provider_task_id" field.
	ProviderTaskID string `json:"provider_task_id,omitempty"`
	// State holds the value of the "state" field.
	State string `json:"state,omitempty"`
	// ErrorCode holds the value of the "error_code" field.
	ErrorCode int32 `json:"error_code,omitempty"`
	// ErrorMessage holds the value of the "error_message" field.
	ErrorMessage string `json:"error_message,omitempty"`
	// ErrorReason holds the value of the "error_reason" field.
	ErrorReason string `json:"error_reason,omitempty"`
	// CreatedAt holds the value of the "created_at" field.
	CreatedAt time.Time `json:"created_at,omitempty"`
	// UpdatedAt holds the value of the "updated_at" field.
	UpdatedAt    time.Time `json:"updated_at,omitempty"`
	selectValues sql.SelectValues
}

// scanValues returns the types for scanning values from sql.Rows.
func (*GenerationTask) scanValues(columns []string) ([]any, error) {
	values := make([]any, len(columns))
	for i := range columns {
		switch columns[i] {
		case generationtask.FieldErrorCode:
			values[i] = new(sql.NullInt64)
		case generationtask.FieldID, generationtask.FieldCaller, generationtask.FieldRequestID, generationtask.FieldRequestHash, generationtask.FieldModel, generationtask.FieldProvider, generationtask.FieldProviderTaskID, generationtask.FieldState, generationtask.FieldErrorMessage, generationtask.FieldErrorReason:
			values[i] = new(sql.NullString)
		case generationtask.FieldCreatedAt, generationtask.FieldUpdatedAt:
			values[i] = new(sql.NullTime)
		default:
			values[i] = new(sql.UnknownType)
		}
	}
	return values, nil
}

// assignValues assigns the values that were returned from sql.Rows (after scanning)
// to the GenerationTask fields.
func (_m *GenerationTask) assignValues(columns []string, values []any) error {
	if m, n := len(values), len(columns); m < n {
		return fmt.Errorf("mismatch number of scan values: %d != %d", m, n)
	}
	for i := range columns {
		switch columns[i] {
		case generationtask.FieldID:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field id", values[i])
			} else if value.Valid {
				_m.ID = value.String
			}
		case generationtask.FieldCaller:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field caller", values[i])
			} else if value.Valid {
				_m.Caller = value.String
			}
		case generationtask.FieldRequestID:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field request_id", values[i])
			} else if value.Valid {
				_m.RequestID = value.String
			}
		case generationtask.FieldRequestHash:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field request_hash", values[i])
			} else if value.Valid {
				_m.RequestHash = value.String
			}
		case generationtask.FieldModel:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field model", values[i])
			} else if value.Valid {
				_m.Model = value.String
			}
		case generationtask.FieldProvider:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field provider", values[i])
			} else if value.Valid {
				_m.Provider = value.String
			}
		case generationtask.FieldProviderTaskID:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field provider_task_id", values[i])
			} else if value.Valid {
				_m.ProviderTaskID = value.String
			}
		case generationtask.FieldState:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field state", values[i])
			} else if value.Valid {
				_m.State = value.String
			}
		case generationtask.FieldErrorCode:
			if value, ok := values[i].(*sql.NullInt64); !ok {
				return fmt.Errorf("unexpected type %T for field error_code", values[i])
			} else if value.Valid {
				_m.ErrorCode = int32(value.Int64)
			}
		case generationtask.FieldErrorMessage:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field error_message", values[i])
			} else if value.Valid {
				_m.ErrorMessage = value.String
			}
		case generationtask.FieldErrorReason:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field error_reason", values[i])
			} else if value.Valid {
				_m.ErrorReason = value.String
			}
		case generationtask.FieldCreatedAt:
			if value, ok := values[i].(*sql.NullTime); !ok {
				return fmt.Errorf("unexpected type %T for field created_at", values[i])
			} else if value.Valid {
				_m.CreatedAt = value.Time
			}
		case generationtask.FieldUpdatedAt:
			if value, ok := values[i].(*sql.NullTime); !ok {
				return fmt.Errorf("unexpected type %T for field updated_at", values[i])
			} else if value.Valid {
				_m.UpdatedAt = value.Time
			}
		default:
			_m.selectValues.Set(columns[i], values[i])
		}
	}
	return nil
}

// Value returns the ent.Value that was dynamically selected and assigned to the GenerationTask.
// This includes values selected through modifiers, order, etc.
func (_m *GenerationTask) Value(name string) (ent.Value, error) {
	return _m.selectValues.Get(name)
}

// Update returns a builder for updating this GenerationTask.
// Note that you need to call GenerationTask.Unwrap() before calling this method if this GenerationTask
// was returned from a transaction, and the transaction was committed or rolled back.
func (_m *GenerationTask) Update() *GenerationTaskUpdateOne {
	return NewGenerationTaskClient(_m.config).UpdateOne(_m)
}

// Unwrap unwraps the GenerationTask entity that was returned from a transaction after it was closed,
// so that all future queries will be executed through the driver which created the transaction.
func (_m *GenerationTask) Unwrap() *GenerationTask {
	_tx, ok := _m.config.driver.(*txDriver)
	if !ok {
		panic("ent: GenerationTask is not a transactional entity")
	}
	_m.config.driver = _tx.drv
	return _m
}

// String implements the fmt.Stringer.
func (_m *GenerationTask) String() string {
	var builder strings.Builder
	builder.WriteString("GenerationTask(")
	builder.WriteString(fmt.Sprintf("id=%v, ", _m.ID))
	builder.WriteString("caller=")
	builder.WriteString(_m.Caller)
	builder.WriteString(", ")
	builder.WriteString("request_id=")
	builder.WriteString(_m.RequestID)
	builder.WriteString(", ")
	builder.WriteString("request_hash=")
	builder.WriteString(_m.RequestHash)
	builder.WriteString(", ")
	builder.WriteString("model=")
	builder.WriteString(_m.Model)
	builder.WriteString(", ")
	builder.WriteString("provider=")
	builder.WriteString(_m.Provider)
	builder.WriteString(", ")
	builder.WriteString("provider_task_id=")
	builder.WriteString(_m.ProviderTaskID)
	builder.WriteString(", ")
	builder.WriteString("state=")
	builder.WriteString(_m.State)
	builder.WriteString(", ")
	builder.WriteString("error_code=")
	builder.WriteString(fmt.Sprintf("%v", _m.ErrorCode))
	builder.WriteString(", ")
	builder.WriteString("error_message=")
	builder.WriteString(_m.ErrorMessage)
	builder.WriteString(", ")
	builder.WriteString("error_reason=")
	builder.WriteString(_m.ErrorReason)
	builder.WriteString(", ")
	builder.WriteString("created_at=")
	builder.WriteString(_m.CreatedAt.Format(time.ANSIC))
	builder.WriteString(", ")
	builder.WriteString("updated_at=")
	builder.WriteString(_m.UpdatedAt.Format(time.ANSIC))
	builder.WriteByte(')')
	return builder.String()
}

// GenerationTasks is a parsable slice of GenerationTask.
type GenerationTasks []*GenerationTask
