// Code generated by ent, DO NOT EDIT.

package ent

import (
	"context"
	"errors"
	"fmt"
	"time"

	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/schema/field"
	"github.com/wgdl666/wgModelHub/ent/modelhubapikey"
	"github.com/wgdl666/wgModelHub/ent/predicate"
)

// ModelhubAPIKeyUpdate is the builder for updating ModelhubAPIKey entities.
type ModelhubAPIKeyUpdate struct {
	config
	hooks    []Hook
	mutation *ModelhubAPIKeyMutation
}

// Where appends a list predicates to the ModelhubAPIKeyUpdate builder.
func (_u *ModelhubAPIKeyUpdate) Where(ps ...predicate.ModelhubAPIKey) *ModelhubAPIKeyUpdate {
	_u.mutation.Where(ps...)
	return _u
}

// SetSecretSha256 sets the "secret_sha256" field.
func (_u *ModelhubAPIKeyUpdate) SetSecretSha256(v string) *ModelhubAPIKeyUpdate {
	_u.mutation.SetSecretSha256(v)
	return _u
}

// SetNillableSecretSha256 sets the "secret_sha256" field if the given value is not nil.
func (_u *ModelhubAPIKeyUpdate) SetNillableSecretSha256(v *string) *ModelhubAPIKeyUpdate {
	if v != nil {
		_u.SetSecretSha256(*v)
	}
	return _u
}

// SetName sets the "name" field.
func (_u *ModelhubAPIKeyUpdate) SetName(v string) *ModelhubAPIKeyUpdate {
	_u.mutation.SetName(v)
	return _u
}

// SetNillableName sets the "name" field if the given value is not nil.
func (_u *ModelhubAPIKeyUpdate) SetNillableName(v *string) *ModelhubAPIKeyUpdate {
	if v != nil {
		_u.SetName(*v)
	}
	return _u
}

// SetExpiresAt sets the "expires_at" field.
func (_u *ModelhubAPIKeyUpdate) SetExpiresAt(v time.Time) *ModelhubAPIKeyUpdate {
	_u.mutation.SetExpiresAt(v)
	return _u
}

// SetNillableExpiresAt sets the "expires_at" field if the given value is not nil.
func (_u *ModelhubAPIKeyUpdate) SetNillableExpiresAt(v *time.Time) *ModelhubAPIKeyUpdate {
	if v != nil {
		_u.SetExpiresAt(*v)
	}
	return _u
}

// ClearExpiresAt clears the value of the "expires_at" field.
func (_u *ModelhubAPIKeyUpdate) ClearExpiresAt() *ModelhubAPIKeyUpdate {
	_u.mutation.ClearExpiresAt()
	return _u
}

// SetRevokedAt sets the "revoked_at" field.
func (_u *ModelhubAPIKeyUpdate) SetRevokedAt(v time.Time) *ModelhubAPIKeyUpdate {
	_u.mutation.SetRevokedAt(v)
	return _u
}

// SetNillableRevokedAt sets the "revoked_at" field if the given value is not nil.
func (_u *ModelhubAPIKeyUpdate) SetNillableRevokedAt(v *time.Time) *ModelhubAPIKeyUpdate {
	if v != nil {
		_u.SetRevokedAt(*v)
	}
	return _u
}

// ClearRevokedAt clears the value of the "revoked_at" field.
func (_u *ModelhubAPIKeyUpdate) ClearRevokedAt() *ModelhubAPIKeyUpdate {
	_u.mutation.ClearRevokedAt()
	return _u
}

// Mutation returns the ModelhubAPIKeyMutation object of the builder.
func (_u *ModelhubAPIKeyUpdate) Mutation() *ModelhubAPIKeyMutation {
	return _u.mutation
}

// Save executes the query and returns the number of nodes affected by the update operation.
func (_u *ModelhubAPIKeyUpdate) Save(ctx context.Context) (int, error) {
	return withHooks(ctx, _u.sqlSave, _u.mutation, _u.hooks)
}

// SaveX is like Save, but panics if an error occurs.
func (_u *ModelhubAPIKeyUpdate) SaveX(ctx context.Context) int {
	affected, err := _u.Save(ctx)
	if err != nil {
		panic(err)
	}
	return affected
}

// Exec executes the query.
func (_u *ModelhubAPIKeyUpdate) Exec(ctx context.Context) error {
	_, err := _u.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_u *ModelhubAPIKeyUpdate) ExecX(ctx context.Context) {
	if err := _u.Exec(ctx); err != nil {
		panic(err)
	}
}

func (_u *ModelhubAPIKeyUpdate) sqlSave(ctx context.Context) (_node int, err error) {
	_spec := sqlgraph.NewUpdateSpec(modelhubapikey.Table, modelhubapikey.Columns, sqlgraph.NewFieldSpec(modelhubapikey.FieldID, field.TypeString))
	if ps := _u.mutation.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	if value, ok := _u.mutation.SecretSha256(); ok {
		_spec.SetField(modelhubapikey.FieldSecretSha256, field.TypeString, value)
	}
	if value, ok := _u.mutation.Name(); ok {
		_spec.SetField(modelhubapikey.FieldName, field.TypeString, value)
	}
	if value, ok := _u.mutation.ExpiresAt(); ok {
		_spec.SetField(modelhubapikey.FieldExpiresAt, field.TypeTime, value)
	}
	if _u.mutation.ExpiresAtCleared() {
		_spec.ClearField(modelhubapikey.FieldExpiresAt, field.TypeTime)
	}
	if value, ok := _u.mutation.RevokedAt(); ok {
		_spec.SetField(modelhubapikey.FieldRevokedAt, field.TypeTime, value)
	}
	if _u.mutation.RevokedAtCleared() {
		_spec.ClearField(modelhubapikey.FieldRevokedAt, field.TypeTime)
	}
	if _node, err = sqlgraph.UpdateNodes(ctx, _u.driver, _spec); err != nil {
		if _, ok := err.(*sqlgraph.NotFoundError); ok {
			err = &NotFoundError{modelhubapikey.Label}
		} else if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return 0, err
	}
	_u.mutation.done = true
	return _node, nil
}

// ModelhubAPIKeyUpdateOne is the builder for updating a single ModelhubAPIKey entity.
type ModelhubAPIKeyUpdateOne struct {
	config
	fields   []string
	hooks    []Hook
	mutation *ModelhubAPIKeyMutation
}

// SetSecretSha256 sets the "secret_sha256" field.
func (_u *ModelhubAPIKeyUpdateOne) SetSecretSha256(v string) *ModelhubAPIKeyUpdateOne {
	_u.mutation.SetSecretSha256(v)
	return _u
}

// SetNillableSecretSha256 sets the "secret_sha256" field if the given value is not nil.
func (_u *ModelhubAPIKeyUpdateOne) SetNillableSecretSha256(v *string) *ModelhubAPIKeyUpdateOne {
	if v != nil {
		_u.SetSecretSha256(*v)
	}
	return _u
}

// SetName sets the "name" field.
func (_u *ModelhubAPIKeyUpdateOne) SetName(v string) *ModelhubAPIKeyUpdateOne {
	_u.mutation.SetName(v)
	return _u
}

// SetNillableName sets the "name" field if the given value is not nil.
func (_u *ModelhubAPIKeyUpdateOne) SetNillableName(v *string) *ModelhubAPIKeyUpdateOne {
	if v != nil {
		_u.SetName(*v)
	}
	return _u
}

// SetExpiresAt sets the "expires_at" field.
func (_u *ModelhubAPIKeyUpdateOne) SetExpiresAt(v time.Time) *ModelhubAPIKeyUpdateOne {
	_u.mutation.SetExpiresAt(v)
	return _u
}

// SetNillableExpiresAt sets the "expires_at" field if the given value is not nil.
func (_u *ModelhubAPIKeyUpdateOne) SetNillableExpiresAt(v *time.Time) *ModelhubAPIKeyUpdateOne {
	if v != nil {
		_u.SetExpiresAt(*v)
	}
	return _u
}

// ClearExpiresAt clears the value of the "expires_at" field.
func (_u *ModelhubAPIKeyUpdateOne) ClearExpiresAt() *ModelhubAPIKeyUpdateOne {
	_u.mutation.ClearExpiresAt()
	return _u
}

// SetRevokedAt sets the "revoked_at" field.
func (_u *ModelhubAPIKeyUpdateOne) SetRevokedAt(v time.Time) *ModelhubAPIKeyUpdateOne {
	_u.mutation.SetRevokedAt(v)
	return _u
}

// SetNillableRevokedAt sets the "revoked_at" field if the given value is not nil.
func (_u *ModelhubAPIKeyUpdateOne) SetNillableRevokedAt(v *time.Time) *ModelhubAPIKeyUpdateOne {
	if v != nil {
		_u.SetRevokedAt(*v)
	}
	return _u
}

// ClearRevokedAt clears the value of the "revoked_at" field.
func (_u *ModelhubAPIKeyUpdateOne) ClearRevokedAt() *ModelhubAPIKeyUpdateOne {
	_u.mutation.ClearRevokedAt()
	return _u
}

// Mutation returns the ModelhubAPIKeyMutation object of the builder.
func (_u *ModelhubAPIKeyUpdateOne) Mutation() *ModelhubAPIKeyMutation {
	return _u.mutation
}

// Where appends a list predicates to the ModelhubAPIKeyUpdate builder.
func (_u *ModelhubAPIKeyUpdateOne) Where(ps ...predicate.ModelhubAPIKey) *ModelhubAPIKeyUpdateOne {
	_u.mutation.Where(ps...)
	return _u
}

// Select allows selecting one or more fields (columns) of the returned entity.
// The default is selecting all fields defined in the entity schema.
func (_u *ModelhubAPIKeyUpdateOne) Select(field string, fields ...string) *ModelhubAPIKeyUpdateOne {
	_u.fields = append([]string{field}, fields...)
	return _u
}

// Save executes the query and returns the updated ModelhubAPIKey entity.
func (_u *ModelhubAPIKeyUpdateOne) Save(ctx context.Context) (*ModelhubAPIKey, error) {
	return withHooks(ctx, _u.sqlSave, _u.mutation, _u.hooks)
}

// SaveX is like Save, but panics if an error occurs.
func (_u *ModelhubAPIKeyUpdateOne) SaveX(ctx context.Context) *ModelhubAPIKey {
	node, err := _u.Save(ctx)
	if err != nil {
		panic(err)
	}
	return node
}

// Exec executes the query on the entity.
func (_u *ModelhubAPIKeyUpdateOne) Exec(ctx context.Context) error {
	_, err := _u.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_u *ModelhubAPIKeyUpdateOne) ExecX(ctx context.Context) {
	if err := _u.Exec(ctx); err != nil {
		panic(err)
	}
}

func (_u *ModelhubAPIKeyUpdateOne) sqlSave(ctx context.Context) (_node *ModelhubAPIKey, err error) {
	_spec := sqlgraph.NewUpdateSpec(modelhubapikey.Table, modelhubapikey.Columns, sqlgraph.NewFieldSpec(modelhubapikey.FieldID, field.TypeString))
	id, ok := _u.mutation.ID()
	if !ok {
		return nil, &ValidationError{Name: "id", err: errors.New(`ent: missing "ModelhubAPIKey.id" for update`)}
	}
	_spec.Node.ID.Value = id
	if fields := _u.fields; len(fields) > 0 {
		_spec.Node.Columns = make([]string, 0, len(fields))
		_spec.Node.Columns = append(_spec.Node.Columns, modelhubapikey.FieldID)
		for _, f := range fields {
			if !modelhubapikey.ValidColumn(f) {
				return nil, &ValidationError{Name: f, err: fmt.Errorf("ent: invalid field %q for query", f)}
			}
			if f != modelhubapikey.FieldID {
				_spec.Node.Columns = append(_spec.Node.Columns, f)
			}
		}
	}
	if ps := _u.mutation.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	if value, ok := _u.mutation.SecretSha256(); ok {
		_spec.SetField(modelhubapikey.FieldSecretSha256, field.TypeString, value)
	}
	if value, ok := _u.mutation.Name(); ok {
		_spec.SetField(modelhubapikey.FieldName, field.TypeString, value)
	}
	if value, ok := _u.mutation.ExpiresAt(); ok {
		_spec.SetField(modelhubapikey.FieldExpiresAt, field.TypeTime, value)
	}
	if _u.mutation.ExpiresAtCleared() {
		_spec.ClearField(modelhubapikey.FieldExpiresAt, field.TypeTime)
	}
	if value, ok := _u.mutation.RevokedAt(); ok {
		_spec.SetField(modelhubapikey.FieldRevokedAt, field.TypeTime, value)
	}
	if _u.mutation.RevokedAtCleared() {
		_spec.ClearField(modelhubapikey.FieldRevokedAt, field.TypeTime)
	}
	_node = &ModelhubAPIKey{config: _u.config}
	_spec.Assign = _node.assignValues
	_spec.ScanValues = _node.scanValues
	if err = sqlgraph.UpdateNode(ctx, _u.driver, _spec); err != nil {
		if _, ok := err.(*sqlgraph.NotFoundError); ok {
			err = &NotFoundError{modelhubapikey.Label}
		} else if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return nil, err
	}
	_u.mutation.done = true
	return _node, nil
}
