// Code generated by ent, DO NOT EDIT.

package ent

import (
	"context"
	"errors"
	"fmt"
	"time"

	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/schema/field"
	"github.com/wgdl666/wgModelHub/ent/modelhubapikey"
)

// ModelhubAPIKeyCreate is the builder for creating a ModelhubAPIKey entity.
type ModelhubAPIKeyCreate struct {
	config
	mutation *ModelhubAPIKeyMutation
	hooks    []Hook
}

// SetPrincipalID sets the "principal_id" field.
func (_c *ModelhubAPIKeyCreate) SetPrincipalID(v string) *ModelhubAPIKeyCreate {
	_c.mutation.SetPrincipalID(v)
	return _c
}

// SetKeyID sets the "key_id" field.
func (_c *ModelhubAPIKeyCreate) SetKeyID(v string) *ModelhubAPIKeyCreate {
	_c.mutation.SetKeyID(v)
	return _c
}

// SetSecretSha256 sets the "secret_sha256" field.
func (_c *ModelhubAPIKeyCreate) SetSecretSha256(v string) *ModelhubAPIKeyCreate {
	_c.mutation.SetSecretSha256(v)
	return _c
}

// SetName sets the "name" field.
func (_c *ModelhubAPIKeyCreate) SetName(v string) *ModelhubAPIKeyCreate {
	_c.mutation.SetName(v)
	return _c
}

// SetNillableName sets the "name" field if the given value is not nil.
func (_c *ModelhubAPIKeyCreate) SetNillableName(v *string) *ModelhubAPIKeyCreate {
	if v != nil {
		_c.SetName(*v)
	}
	return _c
}

// SetCreatedBy sets the "created_by" field.
func (_c *ModelhubAPIKeyCreate) SetCreatedBy(v string) *ModelhubAPIKeyCreate {
	_c.mutation.SetCreatedBy(v)
	return _c
}

// SetCreatedAt sets the "created_at" field.
func (_c *ModelhubAPIKeyCreate) SetCreatedAt(v time.Time) *ModelhubAPIKeyCreate {
	_c.mutation.SetCreatedAt(v)
	return _c
}

// SetNillableCreatedAt sets the "created_at" field if the given value is not nil.
func (_c *ModelhubAPIKeyCreate) SetNillableCreatedAt(v *time.Time) *ModelhubAPIKeyCreate {
	if v != nil {
		_c.SetCreatedAt(*v)
	}
	return _c
}

// SetExpiresAt sets the "expires_at" field.
func (_c *ModelhubAPIKeyCreate) SetExpiresAt(v time.Time) *ModelhubAPIKeyCreate {
	_c.mutation.SetExpiresAt(v)
	return _c
}

// SetNillableExpiresAt sets the "expires_at" field if the given value is not nil.
func (_c *ModelhubAPIKeyCreate) SetNillableExpiresAt(v *time.Time) *ModelhubAPIKeyCreate {
	if v != nil {
		_c.SetExpiresAt(*v)
	}
	return _c
}

// SetRevokedAt sets the "revoked_at" field.
func (_c *ModelhubAPIKeyCreate) SetRevokedAt(v time.Time) *ModelhubAPIKeyCreate {
	_c.mutation.SetRevokedAt(v)
	return _c
}

// SetNillableRevokedAt sets the "revoked_at" field if the given value is not nil.
func (_c *ModelhubAPIKeyCreate) SetNillableRevokedAt(v *time.Time) *ModelhubAPIKeyCreate {
	if v != nil {
		_c.SetRevokedAt(*v)
	}
	return _c
}

// SetID sets the "id" field.
func (_c *ModelhubAPIKeyCreate) SetID(v string) *ModelhubAPIKeyCreate {
	_c.mutation.SetID(v)
	return _c
}

// Mutation returns the ModelhubAPIKeyMutation object of the builder.
func (_c *ModelhubAPIKeyCreate) Mutation() *ModelhubAPIKeyMutation {
	return _c.mutation
}

// Save creates the ModelhubAPIKey in the database.
func (_c *ModelhubAPIKeyCreate) Save(ctx context.Context) (*ModelhubAPIKey, error) {
	_c.defaults()
	return withHooks(ctx, _c.sqlSave, _c.mutation, _c.hooks)
}

// SaveX calls Save and panics if Save returns an error.
func (_c *ModelhubAPIKeyCreate) SaveX(ctx context.Context) *ModelhubAPIKey {
	v, err := _c.Save(ctx)
	if err != nil {
		panic(err)
	}
	return v
}

// Exec executes the query.
func (_c *ModelhubAPIKeyCreate) Exec(ctx context.Context) error {
	_, err := _c.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_c *ModelhubAPIKeyCreate) ExecX(ctx context.Context) {
	if err := _c.Exec(ctx); err != nil {
		panic(err)
	}
}

// defaults sets the default values of the builder before save.
func (_c *ModelhubAPIKeyCreate) defaults() {
	if _, ok := _c.mutation.Name(); !ok {
		v := modelhubapikey.DefaultName
		_c.mutation.SetName(v)
	}
	if _, ok := _c.mutation.CreatedAt(); !ok {
		v := modelhubapikey.DefaultCreatedAt()
		_c.mutation.SetCreatedAt(v)
	}
}

// check runs all checks and user-defined validators on the builder.
func (_c *ModelhubAPIKeyCreate) check() error {
	if _, ok := _c.mutation.PrincipalID(); !ok {
		return &ValidationError{Name: "principal_id", err: errors.New(`ent: missing required field "ModelhubAPIKey.principal_id"`)}
	}
	if _, ok := _c.mutation.KeyID(); !ok {
		return &ValidationError{Name: "key_id", err: errors.New(`ent: missing required field "ModelhubAPIKey.key_id"`)}
	}
	if _, ok := _c.mutation.SecretSha256(); !ok {
		return &ValidationError{Name: "secret_sha256", err: errors.New(`ent: missing required field "ModelhubAPIKey.secret_sha256"`)}
	}
	if _, ok := _c.mutation.Name(); !ok {
		return &ValidationError{Name: "name", err: errors.New(`ent: missing required field "ModelhubAPIKey.name"`)}
	}
	if _, ok := _c.mutation.CreatedBy(); !ok {
		return &ValidationError{Name: "created_by", err: errors.New(`ent: missing required field "ModelhubAPIKey.created_by"`)}
	}
	if _, ok := _c.mutation.CreatedAt(); !ok {
		return &ValidationError{Name: "created_at", err: errors.New(`ent: missing required field "ModelhubAPIKey.created_at"`)}
	}
	return nil
}

func (_c *ModelhubAPIKeyCreate) sqlSave(ctx context.Context) (*ModelhubAPIKey, error) {
	if err := _c.check(); err != nil {
		return nil, err
	}
	_node, _spec := _c.createSpec()
	if err := sqlgraph.CreateNode(ctx, _c.driver, _spec); err != nil {
		if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return nil, err
	}
	if _spec.ID.Value != nil {
		if id, ok := _spec.ID.Value.(string); ok {
			_node.ID = id
		} else {
			return nil, fmt.Errorf("unexpected ModelhubAPIKey.ID type: %T", _spec.ID.Value)
		}
	}
	_c.mutation.id = &_node.ID
	_c.mutation.done = true
	return _node, nil
}

func (_c *ModelhubAPIKeyCreate) createSpec() (*ModelhubAPIKey, *sqlgraph.CreateSpec) {
	var (
		_node = &ModelhubAPIKey{config: _c.config}
		_spec = sqlgraph.NewCreateSpec(modelhubapikey.Table, sqlgraph.NewFieldSpec(modelhubapikey.FieldID, field.TypeString))
	)
	if id, ok := _c.mutation.ID(); ok {
		_node.ID = id
		_spec.ID.Value = id
	}
	if value, ok := _c.mutation.PrincipalID(); ok {
		_spec.SetField(modelhubapikey.FieldPrincipalID, field.TypeString, value)
		_node.PrincipalID = value
	}
	if value, ok := _c.mutation.KeyID(); ok {
		_spec.SetField(modelhubapikey.FieldKeyID, field.TypeString, value)
		_node.KeyID = value
	}
	if value, ok := _c.mutation.SecretSha256(); ok {
		_spec.SetField(modelhubapikey.FieldSecretSha256, field.TypeString, value)
		_node.SecretSha256 = value
	}
	if value, ok := _c.mutation.Name(); ok {
		_spec.SetField(modelhubapikey.FieldName, field.TypeString, value)
		_node.Name = value
	}
	if value, ok := _c.mutation.CreatedBy(); ok {
		_spec.SetField(modelhubapikey.FieldCreatedBy, field.TypeString, value)
		_node.CreatedBy = value
	}
	if value, ok := _c.mutation.CreatedAt(); ok {
		_spec.SetField(modelhubapikey.FieldCreatedAt, field.TypeTime, value)
		_node.CreatedAt = value
	}
	if value, ok := _c.mutation.ExpiresAt(); ok {
		_spec.SetField(modelhubapikey.FieldExpiresAt, field.TypeTime, value)
		_node.ExpiresAt = &value
	}
	if value, ok := _c.mutation.RevokedAt(); ok {
		_spec.SetField(modelhubapikey.FieldRevokedAt, field.TypeTime, value)
		_node.RevokedAt = &value
	}
	return _node, _spec
}

// ModelhubAPIKeyCreateBulk is the builder for creating many ModelhubAPIKey entities in bulk.
type ModelhubAPIKeyCreateBulk struct {
	config
	err      error
	builders []*ModelhubAPIKeyCreate
}

// Save creates the ModelhubAPIKey entities in the database.
func (_c *ModelhubAPIKeyCreateBulk) Save(ctx context.Context) ([]*ModelhubAPIKey, error) {
	if _c.err != nil {
		return nil, _c.err
	}
	specs := make([]*sqlgraph.CreateSpec, len(_c.builders))
	nodes := make([]*ModelhubAPIKey, len(_c.builders))
	mutators := make([]Mutator, len(_c.builders))
	for i := range _c.builders {
		func(i int, root context.Context) {
			builder := _c.builders[i]
			builder.defaults()
			var mut Mutator = MutateFunc(func(ctx context.Context, m Mutation) (Value, error) {
				mutation, ok := m.(*ModelhubAPIKeyMutation)
				if !ok {
					return nil, fmt.Errorf("unexpected mutation type %T", m)
				}
				if err := builder.check(); err != nil {
					return nil, err
				}
				builder.mutation = mutation
				var err error
				nodes[i], specs[i] = builder.createSpec()
				if i < len(mutators)-1 {
					_, err = mutators[i+1].Mutate(root, _c.builders[i+1].mutation)
				} else {
					spec := &sqlgraph.BatchCreateSpec{Nodes: specs}
					// Invoke the actual operation on the latest mutation in the chain.
					if err = sqlgraph.BatchCreate(ctx, _c.driver, spec); err != nil {
						if sqlgraph.IsConstraintError(err) {
							err = &ConstraintError{msg: err.Error(), wrap: err}
						}
					}
				}
				if err != nil {
					return nil, err
				}
				mutation.id = &nodes[i].ID
				mutation.done = true
				return nodes[i], nil
			})
			for i := len(builder.hooks) - 1; i >= 0; i-- {
				mut = builder.hooks[i](mut)
			}
			mutators[i] = mut
		}(i, ctx)
	}
	if len(mutators) > 0 {
		if _, err := mutators[0].Mutate(ctx, _c.builders[0].mutation); err != nil {
			return nil, err
		}
	}
	return nodes, nil
}

// SaveX is like Save, but panics if an error occurs.
func (_c *ModelhubAPIKeyCreateBulk) SaveX(ctx context.Context) []*ModelhubAPIKey {
	v, err := _c.Save(ctx)
	if err != nil {
		panic(err)
	}
	return v
}

// Exec executes the query.
func (_c *ModelhubAPIKeyCreateBulk) Exec(ctx context.Context) error {
	_, err := _c.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_c *ModelhubAPIKeyCreateBulk) ExecX(ctx context.Context) {
	if err := _c.Exec(ctx); err != nil {
		panic(err)
	}
}
