// Code generated by ent, DO NOT EDIT.

package ent

import (
	"context"

	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/schema/field"
	"github.com/wgdl666/wgModelHub/ent/internal"
	"github.com/wgdl666/wgModelHub/ent/modelcall"
	"github.com/wgdl666/wgModelHub/ent/predicate"
)

// ModelCallDelete is the builder for deleting a ModelCall entity.
type ModelCallDelete struct {
	config
	hooks    []Hook
	mutation *ModelCallMutation
}

// Where appends a list predicates to the ModelCallDelete builder.
func (_d *ModelCallDelete) Where(ps ...predicate.ModelCall) *ModelCallDelete {
	_d.mutation.Where(ps...)
	return _d
}

// Exec executes the deletion query and returns how many vertices were deleted.
func (_d *ModelCallDelete) Exec(ctx context.Context) (int, error) {
	return withHooks(ctx, _d.sqlExec, _d.mutation, _d.hooks)
}

// ExecX is like Exec, but panics if an error occurs.
func (_d *ModelCallDelete) ExecX(ctx context.Context) int {
	n, err := _d.Exec(ctx)
	if err != nil {
		panic(err)
	}
	return n
}

func (_d *ModelCallDelete) sqlExec(ctx context.Context) (int, error) {
	_spec := sqlgraph.NewDeleteSpec(modelcall.Table, sqlgraph.NewFieldSpec(modelcall.FieldID, field.TypeString))
	_spec.Node.Schema = _d.schemaConfig.ModelCall
	ctx = internal.NewSchemaConfigContext(ctx, _d.schemaConfig)
	if ps := _d.mutation.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	affected, err := sqlgraph.DeleteNodes(ctx, _d.driver, _spec)
	if err != nil && sqlgraph.IsConstraintError(err) {
		err = &ConstraintError{msg: err.Error(), wrap: err}
	}
	_d.mutation.done = true
	return affected, err
}

// ModelCallDeleteOne is the builder for deleting a single ModelCall entity.
type ModelCallDeleteOne struct {
	_d *ModelCallDelete
}

// Where appends a list predicates to the ModelCallDelete builder.
func (_d *ModelCallDeleteOne) Where(ps ...predicate.ModelCall) *ModelCallDeleteOne {
	_d._d.mutation.Where(ps...)
	return _d
}

// Exec executes the deletion query.
func (_d *ModelCallDeleteOne) Exec(ctx context.Context) error {
	n, err := _d._d.Exec(ctx)
	switch {
	case err != nil:
		return err
	case n == 0:
		return &NotFoundError{modelcall.Label}
	default:
		return nil
	}
}

// ExecX is like Exec, but panics if an error occurs.
func (_d *ModelCallDeleteOne) ExecX(ctx context.Context) {
	if err := _d.Exec(ctx); err != nil {
		panic(err)
	}
}
