// Code generated by ent, DO NOT EDIT.

package ent

import (
	"context"
	"errors"
	"fmt"
	"time"

	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/schema/field"
	"github.com/wgdl666/wgModelHub/ent/internal"
	"github.com/wgdl666/wgModelHub/ent/modelcall"
	"github.com/wgdl666/wgModelHub/ent/predicate"
)

// ModelCallUpdate is the builder for updating ModelCall entities.
type ModelCallUpdate struct {
	config
	hooks    []Hook
	mutation *ModelCallMutation
}

// Where appends a list predicates to the ModelCallUpdate builder.
func (_u *ModelCallUpdate) Where(ps ...predicate.ModelCall) *ModelCallUpdate {
	_u.mutation.Where(ps...)
	return _u
}

// SetGenerationTaskID sets the "generation_task_id" field.
func (_u *ModelCallUpdate) SetGenerationTaskID(v string) *ModelCallUpdate {
	_u.mutation.SetGenerationTaskID(v)
	return _u
}

// SetNillableGenerationTaskID sets the "generation_task_id" field if the given value is not nil.
func (_u *ModelCallUpdate) SetNillableGenerationTaskID(v *string) *ModelCallUpdate {
	if v != nil {
		_u.SetGenerationTaskID(*v)
	}
	return _u
}

// ClearGenerationTaskID clears the value of the "generation_task_id" field.
func (_u *ModelCallUpdate) ClearGenerationTaskID() *ModelCallUpdate {
	_u.mutation.ClearGenerationTaskID()
	return _u
}

// SetCallerService sets the "caller_service" field.
func (_u *ModelCallUpdate) SetCallerService(v string) *ModelCallUpdate {
	_u.mutation.SetCallerService(v)
	return _u
}

// SetNillableCallerService sets the "caller_service" field if the given value is not nil.
func (_u *ModelCallUpdate) SetNillableCallerService(v *string) *ModelCallUpdate {
	if v != nil {
		_u.SetCallerService(*v)
	}
	return _u
}

// SetBusinessScene sets the "business_scene" field.
func (_u *ModelCallUpdate) SetBusinessScene(v string) *ModelCallUpdate {
	_u.mutation.SetBusinessScene(v)
	return _u
}

// SetNillableBusinessScene sets the "business_scene" field if the given value is not nil.
func (_u *ModelCallUpdate) SetNillableBusinessScene(v *string) *ModelCallUpdate {
	if v != nil {
		_u.SetBusinessScene(*v)
	}
	return _u
}

// SetOperation sets the "operation" field.
func (_u *ModelCallUpdate) SetOperation(v string) *ModelCallUpdate {
	_u.mutation.SetOperation(v)
	return _u
}

// SetNillableOperation sets the "operation" field if the given value is not nil.
func (_u *ModelCallUpdate) SetNillableOperation(v *string) *ModelCallUpdate {
	if v != nil {
		_u.SetOperation(*v)
	}
	return _u
}

// SetCapability sets the "capability" field.
func (_u *ModelCallUpdate) SetCapability(v string) *ModelCallUpdate {
	_u.mutation.SetCapability(v)
	return _u
}

// SetNillableCapability sets the "capability" field if the given value is not nil.
func (_u *ModelCallUpdate) SetNillableCapability(v *string) *ModelCallUpdate {
	if v != nil {
		_u.SetCapability(*v)
	}
	return _u
}

// SetModel sets the "model" field.
func (_u *ModelCallUpdate) SetModel(v string) *ModelCallUpdate {
	_u.mutation.SetModel(v)
	return _u
}

// SetNillableModel sets the "model" field if the given value is not nil.
func (_u *ModelCallUpdate) SetNillableModel(v *string) *ModelCallUpdate {
	if v != nil {
		_u.SetModel(*v)
	}
	return _u
}

// SetProvider sets the "provider" field.
func (_u *ModelCallUpdate) SetProvider(v string) *ModelCallUpdate {
	_u.mutation.SetProvider(v)
	return _u
}

// SetNillableProvider sets the "provider" field if the given value is not nil.
func (_u *ModelCallUpdate) SetNillableProvider(v *string) *ModelCallUpdate {
	if v != nil {
		_u.SetProvider(*v)
	}
	return _u
}

// SetStatus sets the "status" field.
func (_u *ModelCallUpdate) SetStatus(v string) *ModelCallUpdate {
	_u.mutation.SetStatus(v)
	return _u
}

// SetNillableStatus sets the "status" field if the given value is not nil.
func (_u *ModelCallUpdate) SetNillableStatus(v *string) *ModelCallUpdate {
	if v != nil {
		_u.SetStatus(*v)
	}
	return _u
}

// SetDeliveryStatus sets the "delivery_status" field.
func (_u *ModelCallUpdate) SetDeliveryStatus(v string) *ModelCallUpdate {
	_u.mutation.SetDeliveryStatus(v)
	return _u
}

// SetNillableDeliveryStatus sets the "delivery_status" field if the given value is not nil.
func (_u *ModelCallUpdate) SetNillableDeliveryStatus(v *string) *ModelCallUpdate {
	if v != nil {
		_u.SetDeliveryStatus(*v)
	}
	return _u
}

// SetErrorCategory sets the "error_category" field.
func (_u *ModelCallUpdate) SetErrorCategory(v string) *ModelCallUpdate {
	_u.mutation.SetErrorCategory(v)
	return _u
}

// SetNillableErrorCategory sets the "error_category" field if the given value is not nil.
func (_u *ModelCallUpdate) SetNillableErrorCategory(v *string) *ModelCallUpdate {
	if v != nil {
		_u.SetErrorCategory(*v)
	}
	return _u
}

// SetErrorCode sets the "error_code" field.
func (_u *ModelCallUpdate) SetErrorCode(v string) *ModelCallUpdate {
	_u.mutation.SetErrorCode(v)
	return _u
}

// SetNillableErrorCode sets the "error_code" field if the given value is not nil.
func (_u *ModelCallUpdate) SetNillableErrorCode(v *string) *ModelCallUpdate {
	if v != nil {
		_u.SetErrorCode(*v)
	}
	return _u
}

// SetErrorReason sets the "error_reason" field.
func (_u *ModelCallUpdate) SetErrorReason(v string) *ModelCallUpdate {
	_u.mutation.SetErrorReason(v)
	return _u
}

// SetNillableErrorReason sets the "error_reason" field if the given value is not nil.
func (_u *ModelCallUpdate) SetNillableErrorReason(v *string) *ModelCallUpdate {
	if v != nil {
		_u.SetErrorReason(*v)
	}
	return _u
}

// SetErrorMessage sets the "error_message" field.
func (_u *ModelCallUpdate) SetErrorMessage(v string) *ModelCallUpdate {
	_u.mutation.SetErrorMessage(v)
	return _u
}

// SetNillableErrorMessage sets the "error_message" field if the given value is not nil.
func (_u *ModelCallUpdate) SetNillableErrorMessage(v *string) *ModelCallUpdate {
	if v != nil {
		_u.SetErrorMessage(*v)
	}
	return _u
}

// SetInputTokens sets the "input_tokens" field.
func (_u *ModelCallUpdate) SetInputTokens(v int64) *ModelCallUpdate {
	_u.mutation.ResetInputTokens()
	_u.mutation.SetInputTokens(v)
	return _u
}

// SetNillableInputTokens sets the "input_tokens" field if the given value is not nil.
func (_u *ModelCallUpdate) SetNillableInputTokens(v *int64) *ModelCallUpdate {
	if v != nil {
		_u.SetInputTokens(*v)
	}
	return _u
}

// AddInputTokens adds value to the "input_tokens" field.
func (_u *ModelCallUpdate) AddInputTokens(v int64) *ModelCallUpdate {
	_u.mutation.AddInputTokens(v)
	return _u
}

// ClearInputTokens clears the value of the "input_tokens" field.
func (_u *ModelCallUpdate) ClearInputTokens() *ModelCallUpdate {
	_u.mutation.ClearInputTokens()
	return _u
}

// SetOutputTokens sets the "output_tokens" field.
func (_u *ModelCallUpdate) SetOutputTokens(v int64) *ModelCallUpdate {
	_u.mutation.ResetOutputTokens()
	_u.mutation.SetOutputTokens(v)
	return _u
}

// SetNillableOutputTokens sets the "output_tokens" field if the given value is not nil.
func (_u *ModelCallUpdate) SetNillableOutputTokens(v *int64) *ModelCallUpdate {
	if v != nil {
		_u.SetOutputTokens(*v)
	}
	return _u
}

// AddOutputTokens adds value to the "output_tokens" field.
func (_u *ModelCallUpdate) AddOutputTokens(v int64) *ModelCallUpdate {
	_u.mutation.AddOutputTokens(v)
	return _u
}

// ClearOutputTokens clears the value of the "output_tokens" field.
func (_u *ModelCallUpdate) ClearOutputTokens() *ModelCallUpdate {
	_u.mutation.ClearOutputTokens()
	return _u
}

// SetTotalTokens sets the "total_tokens" field.
func (_u *ModelCallUpdate) SetTotalTokens(v int64) *ModelCallUpdate {
	_u.mutation.ResetTotalTokens()
	_u.mutation.SetTotalTokens(v)
	return _u
}

// SetNillableTotalTokens sets the "total_tokens" field if the given value is not nil.
func (_u *ModelCallUpdate) SetNillableTotalTokens(v *int64) *ModelCallUpdate {
	if v != nil {
		_u.SetTotalTokens(*v)
	}
	return _u
}

// AddTotalTokens adds value to the "total_tokens" field.
func (_u *ModelCallUpdate) AddTotalTokens(v int64) *ModelCallUpdate {
	_u.mutation.AddTotalTokens(v)
	return _u
}

// ClearTotalTokens clears the value of the "total_tokens" field.
func (_u *ModelCallUpdate) ClearTotalTokens() *ModelCallUpdate {
	_u.mutation.ClearTotalTokens()
	return _u
}

// SetCachedTokens sets the "cached_tokens" field.
func (_u *ModelCallUpdate) SetCachedTokens(v int64) *ModelCallUpdate {
	_u.mutation.ResetCachedTokens()
	_u.mutation.SetCachedTokens(v)
	return _u
}

// SetNillableCachedTokens sets the "cached_tokens" field if the given value is not nil.
func (_u *ModelCallUpdate) SetNillableCachedTokens(v *int64) *ModelCallUpdate {
	if v != nil {
		_u.SetCachedTokens(*v)
	}
	return _u
}

// AddCachedTokens adds value to the "cached_tokens" field.
func (_u *ModelCallUpdate) AddCachedTokens(v int64) *ModelCallUpdate {
	_u.mutation.AddCachedTokens(v)
	return _u
}

// ClearCachedTokens clears the value of the "cached_tokens" field.
func (_u *ModelCallUpdate) ClearCachedTokens() *ModelCallUpdate {
	_u.mutation.ClearCachedTokens()
	return _u
}

// SetReasoningTokens sets the "reasoning_tokens" field.
func (_u *ModelCallUpdate) SetReasoningTokens(v int64) *ModelCallUpdate {
	_u.mutation.ResetReasoningTokens()
	_u.mutation.SetReasoningTokens(v)
	return _u
}

// SetNillableReasoningTokens sets the "reasoning_tokens" field if the given value is not nil.
func (_u *ModelCallUpdate) SetNillableReasoningTokens(v *int64) *ModelCallUpdate {
	if v != nil {
		_u.SetReasoningTokens(*v)
	}
	return _u
}

// AddReasoningTokens adds value to the "reasoning_tokens" field.
func (_u *ModelCallUpdate) AddReasoningTokens(v int64) *ModelCallUpdate {
	_u.mutation.AddReasoningTokens(v)
	return _u
}

// ClearReasoningTokens clears the value of the "reasoning_tokens" field.
func (_u *ModelCallUpdate) ClearReasoningTokens() *ModelCallUpdate {
	_u.mutation.ClearReasoningTokens()
	return _u
}

// SetImageCount sets the "image_count" field.
func (_u *ModelCallUpdate) SetImageCount(v int) *ModelCallUpdate {
	_u.mutation.ResetImageCount()
	_u.mutation.SetImageCount(v)
	return _u
}

// SetNillableImageCount sets the "image_count" field if the given value is not nil.
func (_u *ModelCallUpdate) SetNillableImageCount(v *int) *ModelCallUpdate {
	if v != nil {
		_u.SetImageCount(*v)
	}
	return _u
}

// AddImageCount adds value to the "image_count" field.
func (_u *ModelCallUpdate) AddImageCount(v int) *ModelCallUpdate {
	_u.mutation.AddImageCount(v)
	return _u
}

// ClearImageCount clears the value of the "image_count" field.
func (_u *ModelCallUpdate) ClearImageCount() *ModelCallUpdate {
	_u.mutation.ClearImageCount()
	return _u
}

// SetImageSize sets the "image_size" field.
func (_u *ModelCallUpdate) SetImageSize(v string) *ModelCallUpdate {
	_u.mutation.SetImageSize(v)
	return _u
}

// SetNillableImageSize sets the "image_size" field if the given value is not nil.
func (_u *ModelCallUpdate) SetNillableImageSize(v *string) *ModelCallUpdate {
	if v != nil {
		_u.SetImageSize(*v)
	}
	return _u
}

// SetImageAspectRatio sets the "image_aspect_ratio" field.
func (_u *ModelCallUpdate) SetImageAspectRatio(v string) *ModelCallUpdate {
	_u.mutation.SetImageAspectRatio(v)
	return _u
}

// SetNillableImageAspectRatio sets the "image_aspect_ratio" field if the given value is not nil.
func (_u *ModelCallUpdate) SetNillableImageAspectRatio(v *string) *ModelCallUpdate {
	if v != nil {
		_u.SetImageAspectRatio(*v)
	}
	return _u
}

// SetVideoCount sets the "video_count" field.
func (_u *ModelCallUpdate) SetVideoCount(v int) *ModelCallUpdate {
	_u.mutation.ResetVideoCount()
	_u.mutation.SetVideoCount(v)
	return _u
}

// SetNillableVideoCount sets the "video_count" field if the given value is not nil.
func (_u *ModelCallUpdate) SetNillableVideoCount(v *int) *ModelCallUpdate {
	if v != nil {
		_u.SetVideoCount(*v)
	}
	return _u
}

// AddVideoCount adds value to the "video_count" field.
func (_u *ModelCallUpdate) AddVideoCount(v int) *ModelCallUpdate {
	_u.mutation.AddVideoCount(v)
	return _u
}

// ClearVideoCount clears the value of the "video_count" field.
func (_u *ModelCallUpdate) ClearVideoCount() *ModelCallUpdate {
	_u.mutation.ClearVideoCount()
	return _u
}

// SetVideoResolution sets the "video_resolution" field.
func (_u *ModelCallUpdate) SetVideoResolution(v string) *ModelCallUpdate {
	_u.mutation.SetVideoResolution(v)
	return _u
}

// SetNillableVideoResolution sets the "video_resolution" field if the given value is not nil.
func (_u *ModelCallUpdate) SetNillableVideoResolution(v *string) *ModelCallUpdate {
	if v != nil {
		_u.SetVideoResolution(*v)
	}
	return _u
}

// SetVideoDurationSeconds sets the "video_duration_seconds" field.
func (_u *ModelCallUpdate) SetVideoDurationSeconds(v int) *ModelCallUpdate {
	_u.mutation.ResetVideoDurationSeconds()
	_u.mutation.SetVideoDurationSeconds(v)
	return _u
}

// SetNillableVideoDurationSeconds sets the "video_duration_seconds" field if the given value is not nil.
func (_u *ModelCallUpdate) SetNillableVideoDurationSeconds(v *int) *ModelCallUpdate {
	if v != nil {
		_u.SetVideoDurationSeconds(*v)
	}
	return _u
}

// AddVideoDurationSeconds adds value to the "video_duration_seconds" field.
func (_u *ModelCallUpdate) AddVideoDurationSeconds(v int) *ModelCallUpdate {
	_u.mutation.AddVideoDurationSeconds(v)
	return _u
}

// ClearVideoDurationSeconds clears the value of the "video_duration_seconds" field.
func (_u *ModelCallUpdate) ClearVideoDurationSeconds() *ModelCallUpdate {
	_u.mutation.ClearVideoDurationSeconds()
	return _u
}

// SetVideoAspectRatio sets the "video_aspect_ratio" field.
func (_u *ModelCallUpdate) SetVideoAspectRatio(v string) *ModelCallUpdate {
	_u.mutation.SetVideoAspectRatio(v)
	return _u
}

// SetNillableVideoAspectRatio sets the "video_aspect_ratio" field if the given value is not nil.
func (_u *ModelCallUpdate) SetNillableVideoAspectRatio(v *string) *ModelCallUpdate {
	if v != nil {
		_u.SetVideoAspectRatio(*v)
	}
	return _u
}

// SetLatencyMs sets the "latency_ms" field.
func (_u *ModelCallUpdate) SetLatencyMs(v int64) *ModelCallUpdate {
	_u.mutation.ResetLatencyMs()
	_u.mutation.SetLatencyMs(v)
	return _u
}

// SetNillableLatencyMs sets the "latency_ms" field if the given value is not nil.
func (_u *ModelCallUpdate) SetNillableLatencyMs(v *int64) *ModelCallUpdate {
	if v != nil {
		_u.SetLatencyMs(*v)
	}
	return _u
}

// AddLatencyMs adds value to the "latency_ms" field.
func (_u *ModelCallUpdate) AddLatencyMs(v int64) *ModelCallUpdate {
	_u.mutation.AddLatencyMs(v)
	return _u
}

// SetFinishedAt sets the "finished_at" field.
func (_u *ModelCallUpdate) SetFinishedAt(v time.Time) *ModelCallUpdate {
	_u.mutation.SetFinishedAt(v)
	return _u
}

// SetNillableFinishedAt sets the "finished_at" field if the given value is not nil.
func (_u *ModelCallUpdate) SetNillableFinishedAt(v *time.Time) *ModelCallUpdate {
	if v != nil {
		_u.SetFinishedAt(*v)
	}
	return _u
}

// ClearFinishedAt clears the value of the "finished_at" field.
func (_u *ModelCallUpdate) ClearFinishedAt() *ModelCallUpdate {
	_u.mutation.ClearFinishedAt()
	return _u
}

// SetInputPayload sets the "input_payload" field.
func (_u *ModelCallUpdate) SetInputPayload(v map[string]interface{}) *ModelCallUpdate {
	_u.mutation.SetInputPayload(v)
	return _u
}

// SetOutputPayload sets the "output_payload" field.
func (_u *ModelCallUpdate) SetOutputPayload(v map[string]interface{}) *ModelCallUpdate {
	_u.mutation.SetOutputPayload(v)
	return _u
}

// SetUsageDetail sets the "usage_detail" field.
func (_u *ModelCallUpdate) SetUsageDetail(v map[string]interface{}) *ModelCallUpdate {
	_u.mutation.SetUsageDetail(v)
	return _u
}

// SetUpdatedAt sets the "updated_at" field.
func (_u *ModelCallUpdate) SetUpdatedAt(v time.Time) *ModelCallUpdate {
	_u.mutation.SetUpdatedAt(v)
	return _u
}

// Mutation returns the ModelCallMutation object of the builder.
func (_u *ModelCallUpdate) Mutation() *ModelCallMutation {
	return _u.mutation
}

// Save executes the query and returns the number of nodes affected by the update operation.
func (_u *ModelCallUpdate) Save(ctx context.Context) (int, error) {
	_u.defaults()
	return withHooks(ctx, _u.sqlSave, _u.mutation, _u.hooks)
}

// SaveX is like Save, but panics if an error occurs.
func (_u *ModelCallUpdate) SaveX(ctx context.Context) int {
	affected, err := _u.Save(ctx)
	if err != nil {
		panic(err)
	}
	return affected
}

// Exec executes the query.
func (_u *ModelCallUpdate) Exec(ctx context.Context) error {
	_, err := _u.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_u *ModelCallUpdate) ExecX(ctx context.Context) {
	if err := _u.Exec(ctx); err != nil {
		panic(err)
	}
}

// defaults sets the default values of the builder before save.
func (_u *ModelCallUpdate) defaults() {
	if _, ok := _u.mutation.UpdatedAt(); !ok {
		v := modelcall.UpdateDefaultUpdatedAt()
		_u.mutation.SetUpdatedAt(v)
	}
}

func (_u *ModelCallUpdate) sqlSave(ctx context.Context) (_node int, err error) {
	_spec := sqlgraph.NewUpdateSpec(modelcall.Table, modelcall.Columns, sqlgraph.NewFieldSpec(modelcall.FieldID, field.TypeString))
	if ps := _u.mutation.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	if value, ok := _u.mutation.GenerationTaskID(); ok {
		_spec.SetField(modelcall.FieldGenerationTaskID, field.TypeString, value)
	}
	if _u.mutation.GenerationTaskIDCleared() {
		_spec.ClearField(modelcall.FieldGenerationTaskID, field.TypeString)
	}
	if value, ok := _u.mutation.CallerService(); ok {
		_spec.SetField(modelcall.FieldCallerService, field.TypeString, value)
	}
	if value, ok := _u.mutation.BusinessScene(); ok {
		_spec.SetField(modelcall.FieldBusinessScene, field.TypeString, value)
	}
	if value, ok := _u.mutation.Operation(); ok {
		_spec.SetField(modelcall.FieldOperation, field.TypeString, value)
	}
	if value, ok := _u.mutation.Capability(); ok {
		_spec.SetField(modelcall.FieldCapability, field.TypeString, value)
	}
	if value, ok := _u.mutation.Model(); ok {
		_spec.SetField(modelcall.FieldModel, field.TypeString, value)
	}
	if value, ok := _u.mutation.Provider(); ok {
		_spec.SetField(modelcall.FieldProvider, field.TypeString, value)
	}
	if value, ok := _u.mutation.Status(); ok {
		_spec.SetField(modelcall.FieldStatus, field.TypeString, value)
	}
	if value, ok := _u.mutation.DeliveryStatus(); ok {
		_spec.SetField(modelcall.FieldDeliveryStatus, field.TypeString, value)
	}
	if value, ok := _u.mutation.ErrorCategory(); ok {
		_spec.SetField(modelcall.FieldErrorCategory, field.TypeString, value)
	}
	if value, ok := _u.mutation.ErrorCode(); ok {
		_spec.SetField(modelcall.FieldErrorCode, field.TypeString, value)
	}
	if value, ok := _u.mutation.ErrorReason(); ok {
		_spec.SetField(modelcall.FieldErrorReason, field.TypeString, value)
	}
	if value, ok := _u.mutation.ErrorMessage(); ok {
		_spec.SetField(modelcall.FieldErrorMessage, field.TypeString, value)
	}
	if value, ok := _u.mutation.InputTokens(); ok {
		_spec.SetField(modelcall.FieldInputTokens, field.TypeInt64, value)
	}
	if value, ok := _u.mutation.AddedInputTokens(); ok {
		_spec.AddField(modelcall.FieldInputTokens, field.TypeInt64, value)
	}
	if _u.mutation.InputTokensCleared() {
		_spec.ClearField(modelcall.FieldInputTokens, field.TypeInt64)
	}
	if value, ok := _u.mutation.OutputTokens(); ok {
		_spec.SetField(modelcall.FieldOutputTokens, field.TypeInt64, value)
	}
	if value, ok := _u.mutation.AddedOutputTokens(); ok {
		_spec.AddField(modelcall.FieldOutputTokens, field.TypeInt64, value)
	}
	if _u.mutation.OutputTokensCleared() {
		_spec.ClearField(modelcall.FieldOutputTokens, field.TypeInt64)
	}
	if value, ok := _u.mutation.TotalTokens(); ok {
		_spec.SetField(modelcall.FieldTotalTokens, field.TypeInt64, value)
	}
	if value, ok := _u.mutation.AddedTotalTokens(); ok {
		_spec.AddField(modelcall.FieldTotalTokens, field.TypeInt64, value)
	}
	if _u.mutation.TotalTokensCleared() {
		_spec.ClearField(modelcall.FieldTotalTokens, field.TypeInt64)
	}
	if value, ok := _u.mutation.CachedTokens(); ok {
		_spec.SetField(modelcall.FieldCachedTokens, field.TypeInt64, value)
	}
	if value, ok := _u.mutation.AddedCachedTokens(); ok {
		_spec.AddField(modelcall.FieldCachedTokens, field.TypeInt64, value)
	}
	if _u.mutation.CachedTokensCleared() {
		_spec.ClearField(modelcall.FieldCachedTokens, field.TypeInt64)
	}
	if value, ok := _u.mutation.ReasoningTokens(); ok {
		_spec.SetField(modelcall.FieldReasoningTokens, field.TypeInt64, value)
	}
	if value, ok := _u.mutation.AddedReasoningTokens(); ok {
		_spec.AddField(modelcall.FieldReasoningTokens, field.TypeInt64, value)
	}
	if _u.mutation.ReasoningTokensCleared() {
		_spec.ClearField(modelcall.FieldReasoningTokens, field.TypeInt64)
	}
	if value, ok := _u.mutation.ImageCount(); ok {
		_spec.SetField(modelcall.FieldImageCount, field.TypeInt, value)
	}
	if value, ok := _u.mutation.AddedImageCount(); ok {
		_spec.AddField(modelcall.FieldImageCount, field.TypeInt, value)
	}
	if _u.mutation.ImageCountCleared() {
		_spec.ClearField(modelcall.FieldImageCount, field.TypeInt)
	}
	if value, ok := _u.mutation.ImageSize(); ok {
		_spec.SetField(modelcall.FieldImageSize, field.TypeString, value)
	}
	if value, ok := _u.mutation.ImageAspectRatio(); ok {
		_spec.SetField(modelcall.FieldImageAspectRatio, field.TypeString, value)
	}
	if value, ok := _u.mutation.VideoCount(); ok {
		_spec.SetField(modelcall.FieldVideoCount, field.TypeInt, value)
	}
	if value, ok := _u.mutation.AddedVideoCount(); ok {
		_spec.AddField(modelcall.FieldVideoCount, field.TypeInt, value)
	}
	if _u.mutation.VideoCountCleared() {
		_spec.ClearField(modelcall.FieldVideoCount, field.TypeInt)
	}
	if value, ok := _u.mutation.VideoResolution(); ok {
		_spec.SetField(modelcall.FieldVideoResolution, field.TypeString, value)
	}
	if value, ok := _u.mutation.VideoDurationSeconds(); ok {
		_spec.SetField(modelcall.FieldVideoDurationSeconds, field.TypeInt, value)
	}
	if value, ok := _u.mutation.AddedVideoDurationSeconds(); ok {
		_spec.AddField(modelcall.FieldVideoDurationSeconds, field.TypeInt, value)
	}
	if _u.mutation.VideoDurationSecondsCleared() {
		_spec.ClearField(modelcall.FieldVideoDurationSeconds, field.TypeInt)
	}
	if value, ok := _u.mutation.VideoAspectRatio(); ok {
		_spec.SetField(modelcall.FieldVideoAspectRatio, field.TypeString, value)
	}
	if value, ok := _u.mutation.LatencyMs(); ok {
		_spec.SetField(modelcall.FieldLatencyMs, field.TypeInt64, value)
	}
	if value, ok := _u.mutation.AddedLatencyMs(); ok {
		_spec.AddField(modelcall.FieldLatencyMs, field.TypeInt64, value)
	}
	if value, ok := _u.mutation.FinishedAt(); ok {
		_spec.SetField(modelcall.FieldFinishedAt, field.TypeTime, value)
	}
	if _u.mutation.FinishedAtCleared() {
		_spec.ClearField(modelcall.FieldFinishedAt, field.TypeTime)
	}
	if value, ok := _u.mutation.InputPayload(); ok {
		_spec.SetField(modelcall.FieldInputPayload, field.TypeJSON, value)
	}
	if value, ok := _u.mutation.OutputPayload(); ok {
		_spec.SetField(modelcall.FieldOutputPayload, field.TypeJSON, value)
	}
	if value, ok := _u.mutation.UsageDetail(); ok {
		_spec.SetField(modelcall.FieldUsageDetail, field.TypeJSON, value)
	}
	if value, ok := _u.mutation.UpdatedAt(); ok {
		_spec.SetField(modelcall.FieldUpdatedAt, field.TypeTime, value)
	}
	_spec.Node.Schema = _u.schemaConfig.ModelCall
	ctx = internal.NewSchemaConfigContext(ctx, _u.schemaConfig)
	if _node, err = sqlgraph.UpdateNodes(ctx, _u.driver, _spec); err != nil {
		if _, ok := err.(*sqlgraph.NotFoundError); ok {
			err = &NotFoundError{modelcall.Label}
		} else if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return 0, err
	}
	_u.mutation.done = true
	return _node, nil
}

// ModelCallUpdateOne is the builder for updating a single ModelCall entity.
type ModelCallUpdateOne struct {
	config
	fields   []string
	hooks    []Hook
	mutation *ModelCallMutation
}

// SetGenerationTaskID sets the "generation_task_id" field.
func (_u *ModelCallUpdateOne) SetGenerationTaskID(v string) *ModelCallUpdateOne {
	_u.mutation.SetGenerationTaskID(v)
	return _u
}

// SetNillableGenerationTaskID sets the "generation_task_id" field if the given value is not nil.
func (_u *ModelCallUpdateOne) SetNillableGenerationTaskID(v *string) *ModelCallUpdateOne {
	if v != nil {
		_u.SetGenerationTaskID(*v)
	}
	return _u
}

// ClearGenerationTaskID clears the value of the "generation_task_id" field.
func (_u *ModelCallUpdateOne) ClearGenerationTaskID() *ModelCallUpdateOne {
	_u.mutation.ClearGenerationTaskID()
	return _u
}

// SetCallerService sets the "caller_service" field.
func (_u *ModelCallUpdateOne) SetCallerService(v string) *ModelCallUpdateOne {
	_u.mutation.SetCallerService(v)
	return _u
}

// SetNillableCallerService sets the "caller_service" field if the given value is not nil.
func (_u *ModelCallUpdateOne) SetNillableCallerService(v *string) *ModelCallUpdateOne {
	if v != nil {
		_u.SetCallerService(*v)
	}
	return _u
}

// SetBusinessScene sets the "business_scene" field.
func (_u *ModelCallUpdateOne) SetBusinessScene(v string) *ModelCallUpdateOne {
	_u.mutation.SetBusinessScene(v)
	return _u
}

// SetNillableBusinessScene sets the "business_scene" field if the given value is not nil.
func (_u *ModelCallUpdateOne) SetNillableBusinessScene(v *string) *ModelCallUpdateOne {
	if v != nil {
		_u.SetBusinessScene(*v)
	}
	return _u
}

// SetOperation sets the "operation" field.
func (_u *ModelCallUpdateOne) SetOperation(v string) *ModelCallUpdateOne {
	_u.mutation.SetOperation(v)
	return _u
}

// SetNillableOperation sets the "operation" field if the given value is not nil.
func (_u *ModelCallUpdateOne) SetNillableOperation(v *string) *ModelCallUpdateOne {
	if v != nil {
		_u.SetOperation(*v)
	}
	return _u
}

// SetCapability sets the "capability" field.
func (_u *ModelCallUpdateOne) SetCapability(v string) *ModelCallUpdateOne {
	_u.mutation.SetCapability(v)
	return _u
}

// SetNillableCapability sets the "capability" field if the given value is not nil.
func (_u *ModelCallUpdateOne) SetNillableCapability(v *string) *ModelCallUpdateOne {
	if v != nil {
		_u.SetCapability(*v)
	}
	return _u
}

// SetModel sets the "model" field.
func (_u *ModelCallUpdateOne) SetModel(v string) *ModelCallUpdateOne {
	_u.mutation.SetModel(v)
	return _u
}

// SetNillableModel sets the "model" field if the given value is not nil.
func (_u *ModelCallUpdateOne) SetNillableModel(v *string) *ModelCallUpdateOne {
	if v != nil {
		_u.SetModel(*v)
	}
	return _u
}

// SetProvider sets the "provider" field.
func (_u *ModelCallUpdateOne) SetProvider(v string) *ModelCallUpdateOne {
	_u.mutation.SetProvider(v)
	return _u
}

// SetNillableProvider sets the "provider" field if the given value is not nil.
func (_u *ModelCallUpdateOne) SetNillableProvider(v *string) *ModelCallUpdateOne {
	if v != nil {
		_u.SetProvider(*v)
	}
	return _u
}

// SetStatus sets the "status" field.
func (_u *ModelCallUpdateOne) SetStatus(v string) *ModelCallUpdateOne {
	_u.mutation.SetStatus(v)
	return _u
}

// SetNillableStatus sets the "status" field if the given value is not nil.
func (_u *ModelCallUpdateOne) SetNillableStatus(v *string) *ModelCallUpdateOne {
	if v != nil {
		_u.SetStatus(*v)
	}
	return _u
}

// SetDeliveryStatus sets the "delivery_status" field.
func (_u *ModelCallUpdateOne) SetDeliveryStatus(v string) *ModelCallUpdateOne {
	_u.mutation.SetDeliveryStatus(v)
	return _u
}

// SetNillableDeliveryStatus sets the "delivery_status" field if the given value is not nil.
func (_u *ModelCallUpdateOne) SetNillableDeliveryStatus(v *string) *ModelCallUpdateOne {
	if v != nil {
		_u.SetDeliveryStatus(*v)
	}
	return _u
}

// SetErrorCategory sets the "error_category" field.
func (_u *ModelCallUpdateOne) SetErrorCategory(v string) *ModelCallUpdateOne {
	_u.mutation.SetErrorCategory(v)
	return _u
}

// SetNillableErrorCategory sets the "error_category" field if the given value is not nil.
func (_u *ModelCallUpdateOne) SetNillableErrorCategory(v *string) *ModelCallUpdateOne {
	if v != nil {
		_u.SetErrorCategory(*v)
	}
	return _u
}

// SetErrorCode sets the "error_code" field.
func (_u *ModelCallUpdateOne) SetErrorCode(v string) *ModelCallUpdateOne {
	_u.mutation.SetErrorCode(v)
	return _u
}

// SetNillableErrorCode sets the "error_code" field if the given value is not nil.
func (_u *ModelCallUpdateOne) SetNillableErrorCode(v *string) *ModelCallUpdateOne {
	if v != nil {
		_u.SetErrorCode(*v)
	}
	return _u
}

// SetErrorReason sets the "error_reason" field.
func (_u *ModelCallUpdateOne) SetErrorReason(v string) *ModelCallUpdateOne {
	_u.mutation.SetErrorReason(v)
	return _u
}

// SetNillableErrorReason sets the "error_reason" field if the given value is not nil.
func (_u *ModelCallUpdateOne) SetNillableErrorReason(v *string) *ModelCallUpdateOne {
	if v != nil {
		_u.SetErrorReason(*v)
	}
	return _u
}

// SetErrorMessage sets the "error_message" field.
func (_u *ModelCallUpdateOne) SetErrorMessage(v string) *ModelCallUpdateOne {
	_u.mutation.SetErrorMessage(v)
	return _u
}

// SetNillableErrorMessage sets the "error_message" field if the given value is not nil.
func (_u *ModelCallUpdateOne) SetNillableErrorMessage(v *string) *ModelCallUpdateOne {
	if v != nil {
		_u.SetErrorMessage(*v)
	}
	return _u
}

// SetInputTokens sets the "input_tokens" field.
func (_u *ModelCallUpdateOne) SetInputTokens(v int64) *ModelCallUpdateOne {
	_u.mutation.ResetInputTokens()
	_u.mutation.SetInputTokens(v)
	return _u
}

// SetNillableInputTokens sets the "input_tokens" field if the given value is not nil.
func (_u *ModelCallUpdateOne) SetNillableInputTokens(v *int64) *ModelCallUpdateOne {
	if v != nil {
		_u.SetInputTokens(*v)
	}
	return _u
}

// AddInputTokens adds value to the "input_tokens" field.
func (_u *ModelCallUpdateOne) AddInputTokens(v int64) *ModelCallUpdateOne {
	_u.mutation.AddInputTokens(v)
	return _u
}

// ClearInputTokens clears the value of the "input_tokens" field.
func (_u *ModelCallUpdateOne) ClearInputTokens() *ModelCallUpdateOne {
	_u.mutation.ClearInputTokens()
	return _u
}

// SetOutputTokens sets the "output_tokens" field.
func (_u *ModelCallUpdateOne) SetOutputTokens(v int64) *ModelCallUpdateOne {
	_u.mutation.ResetOutputTokens()
	_u.mutation.SetOutputTokens(v)
	return _u
}

// SetNillableOutputTokens sets the "output_tokens" field if the given value is not nil.
func (_u *ModelCallUpdateOne) SetNillableOutputTokens(v *int64) *ModelCallUpdateOne {
	if v != nil {
		_u.SetOutputTokens(*v)
	}
	return _u
}

// AddOutputTokens adds value to the "output_tokens" field.
func (_u *ModelCallUpdateOne) AddOutputTokens(v int64) *ModelCallUpdateOne {
	_u.mutation.AddOutputTokens(v)
	return _u
}

// ClearOutputTokens clears the value of the "output_tokens" field.
func (_u *ModelCallUpdateOne) ClearOutputTokens() *ModelCallUpdateOne {
	_u.mutation.ClearOutputTokens()
	return _u
}

// SetTotalTokens sets the "total_tokens" field.
func (_u *ModelCallUpdateOne) SetTotalTokens(v int64) *ModelCallUpdateOne {
	_u.mutation.ResetTotalTokens()
	_u.mutation.SetTotalTokens(v)
	return _u
}

// SetNillableTotalTokens sets the "total_tokens" field if the given value is not nil.
func (_u *ModelCallUpdateOne) SetNillableTotalTokens(v *int64) *ModelCallUpdateOne {
	if v != nil {
		_u.SetTotalTokens(*v)
	}
	return _u
}

// AddTotalTokens adds value to the "total_tokens" field.
func (_u *ModelCallUpdateOne) AddTotalTokens(v int64) *ModelCallUpdateOne {
	_u.mutation.AddTotalTokens(v)
	return _u
}

// ClearTotalTokens clears the value of the "total_tokens" field.
func (_u *ModelCallUpdateOne) ClearTotalTokens() *ModelCallUpdateOne {
	_u.mutation.ClearTotalTokens()
	return _u
}

// SetCachedTokens sets the "cached_tokens" field.
func (_u *ModelCallUpdateOne) SetCachedTokens(v int64) *ModelCallUpdateOne {
	_u.mutation.ResetCachedTokens()
	_u.mutation.SetCachedTokens(v)
	return _u
}

// SetNillableCachedTokens sets the "cached_tokens" field if the given value is not nil.
func (_u *ModelCallUpdateOne) SetNillableCachedTokens(v *int64) *ModelCallUpdateOne {
	if v != nil {
		_u.SetCachedTokens(*v)
	}
	return _u
}

// AddCachedTokens adds value to the "cached_tokens" field.
func (_u *ModelCallUpdateOne) AddCachedTokens(v int64) *ModelCallUpdateOne {
	_u.mutation.AddCachedTokens(v)
	return _u
}

// ClearCachedTokens clears the value of the "cached_tokens" field.
func (_u *ModelCallUpdateOne) ClearCachedTokens() *ModelCallUpdateOne {
	_u.mutation.ClearCachedTokens()
	return _u
}

// SetReasoningTokens sets the "reasoning_tokens" field.
func (_u *ModelCallUpdateOne) SetReasoningTokens(v int64) *ModelCallUpdateOne {
	_u.mutation.ResetReasoningTokens()
	_u.mutation.SetReasoningTokens(v)
	return _u
}

// SetNillableReasoningTokens sets the "reasoning_tokens" field if the given value is not nil.
func (_u *ModelCallUpdateOne) SetNillableReasoningTokens(v *int64) *ModelCallUpdateOne {
	if v != nil {
		_u.SetReasoningTokens(*v)
	}
	return _u
}

// AddReasoningTokens adds value to the "reasoning_tokens" field.
func (_u *ModelCallUpdateOne) AddReasoningTokens(v int64) *ModelCallUpdateOne {
	_u.mutation.AddReasoningTokens(v)
	return _u
}

// ClearReasoningTokens clears the value of the "reasoning_tokens" field.
func (_u *ModelCallUpdateOne) ClearReasoningTokens() *ModelCallUpdateOne {
	_u.mutation.ClearReasoningTokens()
	return _u
}

// SetImageCount sets the "image_count" field.
func (_u *ModelCallUpdateOne) SetImageCount(v int) *ModelCallUpdateOne {
	_u.mutation.ResetImageCount()
	_u.mutation.SetImageCount(v)
	return _u
}

// SetNillableImageCount sets the "image_count" field if the given value is not nil.
func (_u *ModelCallUpdateOne) SetNillableImageCount(v *int) *ModelCallUpdateOne {
	if v != nil {
		_u.SetImageCount(*v)
	}
	return _u
}

// AddImageCount adds value to the "image_count" field.
func (_u *ModelCallUpdateOne) AddImageCount(v int) *ModelCallUpdateOne {
	_u.mutation.AddImageCount(v)
	return _u
}

// ClearImageCount clears the value of the "image_count" field.
func (_u *ModelCallUpdateOne) ClearImageCount() *ModelCallUpdateOne {
	_u.mutation.ClearImageCount()
	return _u
}

// SetImageSize sets the "image_size" field.
func (_u *ModelCallUpdateOne) SetImageSize(v string) *ModelCallUpdateOne {
	_u.mutation.SetImageSize(v)
	return _u
}

// SetNillableImageSize sets the "image_size" field if the given value is not nil.
func (_u *ModelCallUpdateOne) SetNillableImageSize(v *string) *ModelCallUpdateOne {
	if v != nil {
		_u.SetImageSize(*v)
	}
	return _u
}

// SetImageAspectRatio sets the "image_aspect_ratio" field.
func (_u *ModelCallUpdateOne) SetImageAspectRatio(v string) *ModelCallUpdateOne {
	_u.mutation.SetImageAspectRatio(v)
	return _u
}

// SetNillableImageAspectRatio sets the "image_aspect_ratio" field if the given value is not nil.
func (_u *ModelCallUpdateOne) SetNillableImageAspectRatio(v *string) *ModelCallUpdateOne {
	if v != nil {
		_u.SetImageAspectRatio(*v)
	}
	return _u
}

// SetVideoCount sets the "video_count" field.
func (_u *ModelCallUpdateOne) SetVideoCount(v int) *ModelCallUpdateOne {
	_u.mutation.ResetVideoCount()
	_u.mutation.SetVideoCount(v)
	return _u
}

// SetNillableVideoCount sets the "video_count" field if the given value is not nil.
func (_u *ModelCallUpdateOne) SetNillableVideoCount(v *int) *ModelCallUpdateOne {
	if v != nil {
		_u.SetVideoCount(*v)
	}
	return _u
}

// AddVideoCount adds value to the "video_count" field.
func (_u *ModelCallUpdateOne) AddVideoCount(v int) *ModelCallUpdateOne {
	_u.mutation.AddVideoCount(v)
	return _u
}

// ClearVideoCount clears the value of the "video_count" field.
func (_u *ModelCallUpdateOne) ClearVideoCount() *ModelCallUpdateOne {
	_u.mutation.ClearVideoCount()
	return _u
}

// SetVideoResolution sets the "video_resolution" field.
func (_u *ModelCallUpdateOne) SetVideoResolution(v string) *ModelCallUpdateOne {
	_u.mutation.SetVideoResolution(v)
	return _u
}

// SetNillableVideoResolution sets the "video_resolution" field if the given value is not nil.
func (_u *ModelCallUpdateOne) SetNillableVideoResolution(v *string) *ModelCallUpdateOne {
	if v != nil {
		_u.SetVideoResolution(*v)
	}
	return _u
}

// SetVideoDurationSeconds sets the "video_duration_seconds" field.
func (_u *ModelCallUpdateOne) SetVideoDurationSeconds(v int) *ModelCallUpdateOne {
	_u.mutation.ResetVideoDurationSeconds()
	_u.mutation.SetVideoDurationSeconds(v)
	return _u
}

// SetNillableVideoDurationSeconds sets the "video_duration_seconds" field if the given value is not nil.
func (_u *ModelCallUpdateOne) SetNillableVideoDurationSeconds(v *int) *ModelCallUpdateOne {
	if v != nil {
		_u.SetVideoDurationSeconds(*v)
	}
	return _u
}

// AddVideoDurationSeconds adds value to the "video_duration_seconds" field.
func (_u *ModelCallUpdateOne) AddVideoDurationSeconds(v int) *ModelCallUpdateOne {
	_u.mutation.AddVideoDurationSeconds(v)
	return _u
}

// ClearVideoDurationSeconds clears the value of the "video_duration_seconds" field.
func (_u *ModelCallUpdateOne) ClearVideoDurationSeconds() *ModelCallUpdateOne {
	_u.mutation.ClearVideoDurationSeconds()
	return _u
}

// SetVideoAspectRatio sets the "video_aspect_ratio" field.
func (_u *ModelCallUpdateOne) SetVideoAspectRatio(v string) *ModelCallUpdateOne {
	_u.mutation.SetVideoAspectRatio(v)
	return _u
}

// SetNillableVideoAspectRatio sets the "video_aspect_ratio" field if the given value is not nil.
func (_u *ModelCallUpdateOne) SetNillableVideoAspectRatio(v *string) *ModelCallUpdateOne {
	if v != nil {
		_u.SetVideoAspectRatio(*v)
	}
	return _u
}

// SetLatencyMs sets the "latency_ms" field.
func (_u *ModelCallUpdateOne) SetLatencyMs(v int64) *ModelCallUpdateOne {
	_u.mutation.ResetLatencyMs()
	_u.mutation.SetLatencyMs(v)
	return _u
}

// SetNillableLatencyMs sets the "latency_ms" field if the given value is not nil.
func (_u *ModelCallUpdateOne) SetNillableLatencyMs(v *int64) *ModelCallUpdateOne {
	if v != nil {
		_u.SetLatencyMs(*v)
	}
	return _u
}

// AddLatencyMs adds value to the "latency_ms" field.
func (_u *ModelCallUpdateOne) AddLatencyMs(v int64) *ModelCallUpdateOne {
	_u.mutation.AddLatencyMs(v)
	return _u
}

// SetFinishedAt sets the "finished_at" field.
func (_u *ModelCallUpdateOne) SetFinishedAt(v time.Time) *ModelCallUpdateOne {
	_u.mutation.SetFinishedAt(v)
	return _u
}

// SetNillableFinishedAt sets the "finished_at" field if the given value is not nil.
func (_u *ModelCallUpdateOne) SetNillableFinishedAt(v *time.Time) *ModelCallUpdateOne {
	if v != nil {
		_u.SetFinishedAt(*v)
	}
	return _u
}

// ClearFinishedAt clears the value of the "finished_at" field.
func (_u *ModelCallUpdateOne) ClearFinishedAt() *ModelCallUpdateOne {
	_u.mutation.ClearFinishedAt()
	return _u
}

// SetInputPayload sets the "input_payload" field.
func (_u *ModelCallUpdateOne) SetInputPayload(v map[string]interface{}) *ModelCallUpdateOne {
	_u.mutation.SetInputPayload(v)
	return _u
}

// SetOutputPayload sets the "output_payload" field.
func (_u *ModelCallUpdateOne) SetOutputPayload(v map[string]interface{}) *ModelCallUpdateOne {
	_u.mutation.SetOutputPayload(v)
	return _u
}

// SetUsageDetail sets the "usage_detail" field.
func (_u *ModelCallUpdateOne) SetUsageDetail(v map[string]interface{}) *ModelCallUpdateOne {
	_u.mutation.SetUsageDetail(v)
	return _u
}

// SetUpdatedAt sets the "updated_at" field.
func (_u *ModelCallUpdateOne) SetUpdatedAt(v time.Time) *ModelCallUpdateOne {
	_u.mutation.SetUpdatedAt(v)
	return _u
}

// Mutation returns the ModelCallMutation object of the builder.
func (_u *ModelCallUpdateOne) Mutation() *ModelCallMutation {
	return _u.mutation
}

// Where appends a list predicates to the ModelCallUpdate builder.
func (_u *ModelCallUpdateOne) Where(ps ...predicate.ModelCall) *ModelCallUpdateOne {
	_u.mutation.Where(ps...)
	return _u
}

// Select allows selecting one or more fields (columns) of the returned entity.
// The default is selecting all fields defined in the entity schema.
func (_u *ModelCallUpdateOne) Select(field string, fields ...string) *ModelCallUpdateOne {
	_u.fields = append([]string{field}, fields...)
	return _u
}

// Save executes the query and returns the updated ModelCall entity.
func (_u *ModelCallUpdateOne) Save(ctx context.Context) (*ModelCall, error) {
	_u.defaults()
	return withHooks(ctx, _u.sqlSave, _u.mutation, _u.hooks)
}

// SaveX is like Save, but panics if an error occurs.
func (_u *ModelCallUpdateOne) SaveX(ctx context.Context) *ModelCall {
	node, err := _u.Save(ctx)
	if err != nil {
		panic(err)
	}
	return node
}

// Exec executes the query on the entity.
func (_u *ModelCallUpdateOne) Exec(ctx context.Context) error {
	_, err := _u.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_u *ModelCallUpdateOne) ExecX(ctx context.Context) {
	if err := _u.Exec(ctx); err != nil {
		panic(err)
	}
}

// defaults sets the default values of the builder before save.
func (_u *ModelCallUpdateOne) defaults() {
	if _, ok := _u.mutation.UpdatedAt(); !ok {
		v := modelcall.UpdateDefaultUpdatedAt()
		_u.mutation.SetUpdatedAt(v)
	}
}

func (_u *ModelCallUpdateOne) sqlSave(ctx context.Context) (_node *ModelCall, err error) {
	_spec := sqlgraph.NewUpdateSpec(modelcall.Table, modelcall.Columns, sqlgraph.NewFieldSpec(modelcall.FieldID, field.TypeString))
	id, ok := _u.mutation.ID()
	if !ok {
		return nil, &ValidationError{Name: "id", err: errors.New(`ent: missing "ModelCall.id" for update`)}
	}
	_spec.Node.ID.Value = id
	if fields := _u.fields; len(fields) > 0 {
		_spec.Node.Columns = make([]string, 0, len(fields))
		_spec.Node.Columns = append(_spec.Node.Columns, modelcall.FieldID)
		for _, f := range fields {
			if !modelcall.ValidColumn(f) {
				return nil, &ValidationError{Name: f, err: fmt.Errorf("ent: invalid field %q for query", f)}
			}
			if f != modelcall.FieldID {
				_spec.Node.Columns = append(_spec.Node.Columns, f)
			}
		}
	}
	if ps := _u.mutation.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	if value, ok := _u.mutation.GenerationTaskID(); ok {
		_spec.SetField(modelcall.FieldGenerationTaskID, field.TypeString, value)
	}
	if _u.mutation.GenerationTaskIDCleared() {
		_spec.ClearField(modelcall.FieldGenerationTaskID, field.TypeString)
	}
	if value, ok := _u.mutation.CallerService(); ok {
		_spec.SetField(modelcall.FieldCallerService, field.TypeString, value)
	}
	if value, ok := _u.mutation.BusinessScene(); ok {
		_spec.SetField(modelcall.FieldBusinessScene, field.TypeString, value)
	}
	if value, ok := _u.mutation.Operation(); ok {
		_spec.SetField(modelcall.FieldOperation, field.TypeString, value)
	}
	if value, ok := _u.mutation.Capability(); ok {
		_spec.SetField(modelcall.FieldCapability, field.TypeString, value)
	}
	if value, ok := _u.mutation.Model(); ok {
		_spec.SetField(modelcall.FieldModel, field.TypeString, value)
	}
	if value, ok := _u.mutation.Provider(); ok {
		_spec.SetField(modelcall.FieldProvider, field.TypeString, value)
	}
	if value, ok := _u.mutation.Status(); ok {
		_spec.SetField(modelcall.FieldStatus, field.TypeString, value)
	}
	if value, ok := _u.mutation.DeliveryStatus(); ok {
		_spec.SetField(modelcall.FieldDeliveryStatus, field.TypeString, value)
	}
	if value, ok := _u.mutation.ErrorCategory(); ok {
		_spec.SetField(modelcall.FieldErrorCategory, field.TypeString, value)
	}
	if value, ok := _u.mutation.ErrorCode(); ok {
		_spec.SetField(modelcall.FieldErrorCode, field.TypeString, value)
	}
	if value, ok := _u.mutation.ErrorReason(); ok {
		_spec.SetField(modelcall.FieldErrorReason, field.TypeString, value)
	}
	if value, ok := _u.mutation.ErrorMessage(); ok {
		_spec.SetField(modelcall.FieldErrorMessage, field.TypeString, value)
	}
	if value, ok := _u.mutation.InputTokens(); ok {
		_spec.SetField(modelcall.FieldInputTokens, field.TypeInt64, value)
	}
	if value, ok := _u.mutation.AddedInputTokens(); ok {
		_spec.AddField(modelcall.FieldInputTokens, field.TypeInt64, value)
	}
	if _u.mutation.InputTokensCleared() {
		_spec.ClearField(modelcall.FieldInputTokens, field.TypeInt64)
	}
	if value, ok := _u.mutation.OutputTokens(); ok {
		_spec.SetField(modelcall.FieldOutputTokens, field.TypeInt64, value)
	}
	if value, ok := _u.mutation.AddedOutputTokens(); ok {
		_spec.AddField(modelcall.FieldOutputTokens, field.TypeInt64, value)
	}
	if _u.mutation.OutputTokensCleared() {
		_spec.ClearField(modelcall.FieldOutputTokens, field.TypeInt64)
	}
	if value, ok := _u.mutation.TotalTokens(); ok {
		_spec.SetField(modelcall.FieldTotalTokens, field.TypeInt64, value)
	}
	if value, ok := _u.mutation.AddedTotalTokens(); ok {
		_spec.AddField(modelcall.FieldTotalTokens, field.TypeInt64, value)
	}
	if _u.mutation.TotalTokensCleared() {
		_spec.ClearField(modelcall.FieldTotalTokens, field.TypeInt64)
	}
	if value, ok := _u.mutation.CachedTokens(); ok {
		_spec.SetField(modelcall.FieldCachedTokens, field.TypeInt64, value)
	}
	if value, ok := _u.mutation.AddedCachedTokens(); ok {
		_spec.AddField(modelcall.FieldCachedTokens, field.TypeInt64, value)
	}
	if _u.mutation.CachedTokensCleared() {
		_spec.ClearField(modelcall.FieldCachedTokens, field.TypeInt64)
	}
	if value, ok := _u.mutation.ReasoningTokens(); ok {
		_spec.SetField(modelcall.FieldReasoningTokens, field.TypeInt64, value)
	}
	if value, ok := _u.mutation.AddedReasoningTokens(); ok {
		_spec.AddField(modelcall.FieldReasoningTokens, field.TypeInt64, value)
	}
	if _u.mutation.ReasoningTokensCleared() {
		_spec.ClearField(modelcall.FieldReasoningTokens, field.TypeInt64)
	}
	if value, ok := _u.mutation.ImageCount(); ok {
		_spec.SetField(modelcall.FieldImageCount, field.TypeInt, value)
	}
	if value, ok := _u.mutation.AddedImageCount(); ok {
		_spec.AddField(modelcall.FieldImageCount, field.TypeInt, value)
	}
	if _u.mutation.ImageCountCleared() {
		_spec.ClearField(modelcall.FieldImageCount, field.TypeInt)
	}
	if value, ok := _u.mutation.ImageSize(); ok {
		_spec.SetField(modelcall.FieldImageSize, field.TypeString, value)
	}
	if value, ok := _u.mutation.ImageAspectRatio(); ok {
		_spec.SetField(modelcall.FieldImageAspectRatio, field.TypeString, value)
	}
	if value, ok := _u.mutation.VideoCount(); ok {
		_spec.SetField(modelcall.FieldVideoCount, field.TypeInt, value)
	}
	if value, ok := _u.mutation.AddedVideoCount(); ok {
		_spec.AddField(modelcall.FieldVideoCount, field.TypeInt, value)
	}
	if _u.mutation.VideoCountCleared() {
		_spec.ClearField(modelcall.FieldVideoCount, field.TypeInt)
	}
	if value, ok := _u.mutation.VideoResolution(); ok {
		_spec.SetField(modelcall.FieldVideoResolution, field.TypeString, value)
	}
	if value, ok := _u.mutation.VideoDurationSeconds(); ok {
		_spec.SetField(modelcall.FieldVideoDurationSeconds, field.TypeInt, value)
	}
	if value, ok := _u.mutation.AddedVideoDurationSeconds(); ok {
		_spec.AddField(modelcall.FieldVideoDurationSeconds, field.TypeInt, value)
	}
	if _u.mutation.VideoDurationSecondsCleared() {
		_spec.ClearField(modelcall.FieldVideoDurationSeconds, field.TypeInt)
	}
	if value, ok := _u.mutation.VideoAspectRatio(); ok {
		_spec.SetField(modelcall.FieldVideoAspectRatio, field.TypeString, value)
	}
	if value, ok := _u.mutation.LatencyMs(); ok {
		_spec.SetField(modelcall.FieldLatencyMs, field.TypeInt64, value)
	}
	if value, ok := _u.mutation.AddedLatencyMs(); ok {
		_spec.AddField(modelcall.FieldLatencyMs, field.TypeInt64, value)
	}
	if value, ok := _u.mutation.FinishedAt(); ok {
		_spec.SetField(modelcall.FieldFinishedAt, field.TypeTime, value)
	}
	if _u.mutation.FinishedAtCleared() {
		_spec.ClearField(modelcall.FieldFinishedAt, field.TypeTime)
	}
	if value, ok := _u.mutation.InputPayload(); ok {
		_spec.SetField(modelcall.FieldInputPayload, field.TypeJSON, value)
	}
	if value, ok := _u.mutation.OutputPayload(); ok {
		_spec.SetField(modelcall.FieldOutputPayload, field.TypeJSON, value)
	}
	if value, ok := _u.mutation.UsageDetail(); ok {
		_spec.SetField(modelcall.FieldUsageDetail, field.TypeJSON, value)
	}
	if value, ok := _u.mutation.UpdatedAt(); ok {
		_spec.SetField(modelcall.FieldUpdatedAt, field.TypeTime, value)
	}
	_spec.Node.Schema = _u.schemaConfig.ModelCall
	ctx = internal.NewSchemaConfigContext(ctx, _u.schemaConfig)
	_node = &ModelCall{config: _u.config}
	_spec.Assign = _node.assignValues
	_spec.ScanValues = _node.scanValues
	if err = sqlgraph.UpdateNode(ctx, _u.driver, _spec); err != nil {
		if _, ok := err.(*sqlgraph.NotFoundError); ok {
			err = &NotFoundError{modelcall.Label}
		} else if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return nil, err
	}
	_u.mutation.done = true
	return _node, nil
}
