// Code generated by ent, DO NOT EDIT.

package ent

import (
	"fmt"
	"strings"
	"time"

	"entgo.io/ent"
	"entgo.io/ent/dialect/sql"
	"github.com/wgdl666/wgModelHub/ent/modelhubapikey"
)

// ModelhubAPIKey is the model entity for the ModelhubAPIKey schema.
type ModelhubAPIKey struct {
	config `json:"-"`
	// ID of the ent.
	ID string `json:"id,omitempty"`
	// PrincipalID holds the value of the "principal_id" field.
	PrincipalID string `json:"principal_id,omitempty"`
	// KeyID holds the value of the "key_id" field.
	KeyID string `json:"key_id,omitempty"`
	// SecretSha256 holds the value of the "secret_sha256" field.
	SecretSha256 string `json:"secret_sha256,omitempty"`
	// Name holds the value of the "name" field.
	Name string `json:"name,omitempty"`
	// CreatedBy holds the value of the "created_by" field.
	CreatedBy string `json:"created_by,omitempty"`
	// CreatedAt holds the value of the "created_at" field.
	CreatedAt time.Time `json:"created_at,omitempty"`
	// ExpiresAt holds the value of the "expires_at" field.
	ExpiresAt *time.Time `json:"expires_at,omitempty"`
	// RevokedAt holds the value of the "revoked_at" field.
	RevokedAt    *time.Time `json:"revoked_at,omitempty"`
	selectValues sql.SelectValues
}

// scanValues returns the types for scanning values from sql.Rows.
func (*ModelhubAPIKey) scanValues(columns []string) ([]any, error) {
	values := make([]any, len(columns))
	for i := range columns {
		switch columns[i] {
		case modelhubapikey.FieldID, modelhubapikey.FieldPrincipalID, modelhubapikey.FieldKeyID, modelhubapikey.FieldSecretSha256, modelhubapikey.FieldName, modelhubapikey.FieldCreatedBy:
			values[i] = new(sql.NullString)
		case modelhubapikey.FieldCreatedAt, modelhubapikey.FieldExpiresAt, modelhubapikey.FieldRevokedAt:
			values[i] = new(sql.NullTime)
		default:
			values[i] = new(sql.UnknownType)
		}
	}
	return values, nil
}

// assignValues assigns the values that were returned from sql.Rows (after scanning)
// to the ModelhubAPIKey fields.
func (_m *ModelhubAPIKey) assignValues(columns []string, values []any) error {
	if m, n := len(values), len(columns); m < n {
		return fmt.Errorf("mismatch number of scan values: %d != %d", m, n)
	}
	for i := range columns {
		switch columns[i] {
		case modelhubapikey.FieldID:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field id", values[i])
			} else if value.Valid {
				_m.ID = value.String
			}
		case modelhubapikey.FieldPrincipalID:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field principal_id", values[i])
			} else if value.Valid {
				_m.PrincipalID = value.String
			}
		case modelhubapikey.FieldKeyID:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field key_id", values[i])
			} else if value.Valid {
				_m.KeyID = value.String
			}
		case modelhubapikey.FieldSecretSha256:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field secret_sha256", values[i])
			} else if value.Valid {
				_m.SecretSha256 = value.String
			}
		case modelhubapikey.FieldName:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field name", values[i])
			} else if value.Valid {
				_m.Name = value.String
			}
		case modelhubapikey.FieldCreatedBy:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field created_by", values[i])
			} else if value.Valid {
				_m.CreatedBy = value.String
			}
		case modelhubapikey.FieldCreatedAt:
			if value, ok := values[i].(*sql.NullTime); !ok {
				return fmt.Errorf("unexpected type %T for field created_at", values[i])
			} else if value.Valid {
				_m.CreatedAt = value.Time
			}
		case modelhubapikey.FieldExpiresAt:
			if value, ok := values[i].(*sql.NullTime); !ok {
				return fmt.Errorf("unexpected type %T for field expires_at", values[i])
			} else if value.Valid {
				_m.ExpiresAt = new(time.Time)
				*_m.ExpiresAt = value.Time
			}
		case modelhubapikey.FieldRevokedAt:
			if value, ok := values[i].(*sql.NullTime); !ok {
				return fmt.Errorf("unexpected type %T for field revoked_at", values[i])
			} else if value.Valid {
				_m.RevokedAt = new(time.Time)
				*_m.RevokedAt = value.Time
			}
		default:
			_m.selectValues.Set(columns[i], values[i])
		}
	}
	return nil
}

// Value returns the ent.Value that was dynamically selected and assigned to the ModelhubAPIKey.
// This includes values selected through modifiers, order, etc.
func (_m *ModelhubAPIKey) Value(name string) (ent.Value, error) {
	return _m.selectValues.Get(name)
}

// Update returns a builder for updating this ModelhubAPIKey.
// Note that you need to call ModelhubAPIKey.Unwrap() before calling this method if this ModelhubAPIKey
// was returned from a transaction, and the transaction was committed or rolled back.
func (_m *ModelhubAPIKey) Update() *ModelhubAPIKeyUpdateOne {
	return NewModelhubAPIKeyClient(_m.config).UpdateOne(_m)
}

// Unwrap unwraps the ModelhubAPIKey entity that was returned from a transaction after it was closed,
// so that all future queries will be executed through the driver which created the transaction.
func (_m *ModelhubAPIKey) Unwrap() *ModelhubAPIKey {
	_tx, ok := _m.config.driver.(*txDriver)
	if !ok {
		panic("ent: ModelhubAPIKey is not a transactional entity")
	}
	_m.config.driver = _tx.drv
	return _m
}

// String implements the fmt.Stringer.
func (_m *ModelhubAPIKey) String() string {
	var builder strings.Builder
	builder.WriteString("ModelhubAPIKey(")
	builder.WriteString(fmt.Sprintf("id=%v, ", _m.ID))
	builder.WriteString("principal_id=")
	builder.WriteString(_m.PrincipalID)
	builder.WriteString(", ")
	builder.WriteString("key_id=")
	builder.WriteString(_m.KeyID)
	builder.WriteString(", ")
	builder.WriteString("secret_sha256=")
	builder.WriteString(_m.SecretSha256)
	builder.WriteString(", ")
	builder.WriteString("name=")
	builder.WriteString(_m.Name)
	builder.WriteString(", ")
	builder.WriteString("created_by=")
	builder.WriteString(_m.CreatedBy)
	builder.WriteString(", ")
	builder.WriteString("created_at=")
	builder.WriteString(_m.CreatedAt.Format(time.ANSIC))
	builder.WriteString(", ")
	if v := _m.ExpiresAt; v != nil {
		builder.WriteString("expires_at=")
		builder.WriteString(v.Format(time.ANSIC))
	}
	builder.WriteString(", ")
	if v := _m.RevokedAt; v != nil {
		builder.WriteString("revoked_at=")
		builder.WriteString(v.Format(time.ANSIC))
	}
	builder.WriteByte(')')
	return builder.String()
}

// ModelhubAPIKeys is a parsable slice of ModelhubAPIKey.
type ModelhubAPIKeys []*ModelhubAPIKey
