// Code generated by ent, DO NOT EDIT.

package ent

import (
	"context"
	"errors"
	"fmt"
	"time"

	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/schema/field"
	"github.com/wgdl666/wgModelHub/ent/modelcall"
)

// ModelCallCreate is the builder for creating a ModelCall entity.
type ModelCallCreate struct {
	config
	mutation *ModelCallMutation
	hooks    []Hook
}

// SetGenerationTaskID sets the "generation_task_id" field.
func (_c *ModelCallCreate) SetGenerationTaskID(v string) *ModelCallCreate {
	_c.mutation.SetGenerationTaskID(v)
	return _c
}

// SetNillableGenerationTaskID sets the "generation_task_id" field if the given value is not nil.
func (_c *ModelCallCreate) SetNillableGenerationTaskID(v *string) *ModelCallCreate {
	if v != nil {
		_c.SetGenerationTaskID(*v)
	}
	return _c
}

// SetCallerService sets the "caller_service" field.
func (_c *ModelCallCreate) SetCallerService(v string) *ModelCallCreate {
	_c.mutation.SetCallerService(v)
	return _c
}

// SetNillableCallerService sets the "caller_service" field if the given value is not nil.
func (_c *ModelCallCreate) SetNillableCallerService(v *string) *ModelCallCreate {
	if v != nil {
		_c.SetCallerService(*v)
	}
	return _c
}

// SetBusinessScene sets the "business_scene" field.
func (_c *ModelCallCreate) SetBusinessScene(v string) *ModelCallCreate {
	_c.mutation.SetBusinessScene(v)
	return _c
}

// SetNillableBusinessScene sets the "business_scene" field if the given value is not nil.
func (_c *ModelCallCreate) SetNillableBusinessScene(v *string) *ModelCallCreate {
	if v != nil {
		_c.SetBusinessScene(*v)
	}
	return _c
}

// SetOperation sets the "operation" field.
func (_c *ModelCallCreate) SetOperation(v string) *ModelCallCreate {
	_c.mutation.SetOperation(v)
	return _c
}

// SetCapability sets the "capability" field.
func (_c *ModelCallCreate) SetCapability(v string) *ModelCallCreate {
	_c.mutation.SetCapability(v)
	return _c
}

// SetModel sets the "model" field.
func (_c *ModelCallCreate) SetModel(v string) *ModelCallCreate {
	_c.mutation.SetModel(v)
	return _c
}

// SetProvider sets the "provider" field.
func (_c *ModelCallCreate) SetProvider(v string) *ModelCallCreate {
	_c.mutation.SetProvider(v)
	return _c
}

// SetStatus sets the "status" field.
func (_c *ModelCallCreate) SetStatus(v string) *ModelCallCreate {
	_c.mutation.SetStatus(v)
	return _c
}

// SetDeliveryStatus sets the "delivery_status" field.
func (_c *ModelCallCreate) SetDeliveryStatus(v string) *ModelCallCreate {
	_c.mutation.SetDeliveryStatus(v)
	return _c
}

// SetNillableDeliveryStatus sets the "delivery_status" field if the given value is not nil.
func (_c *ModelCallCreate) SetNillableDeliveryStatus(v *string) *ModelCallCreate {
	if v != nil {
		_c.SetDeliveryStatus(*v)
	}
	return _c
}

// SetErrorCategory sets the "error_category" field.
func (_c *ModelCallCreate) SetErrorCategory(v string) *ModelCallCreate {
	_c.mutation.SetErrorCategory(v)
	return _c
}

// SetNillableErrorCategory sets the "error_category" field if the given value is not nil.
func (_c *ModelCallCreate) SetNillableErrorCategory(v *string) *ModelCallCreate {
	if v != nil {
		_c.SetErrorCategory(*v)
	}
	return _c
}

// SetErrorCode sets the "error_code" field.
func (_c *ModelCallCreate) SetErrorCode(v string) *ModelCallCreate {
	_c.mutation.SetErrorCode(v)
	return _c
}

// SetNillableErrorCode sets the "error_code" field if the given value is not nil.
func (_c *ModelCallCreate) SetNillableErrorCode(v *string) *ModelCallCreate {
	if v != nil {
		_c.SetErrorCode(*v)
	}
	return _c
}

// SetErrorReason sets the "error_reason" field.
func (_c *ModelCallCreate) SetErrorReason(v string) *ModelCallCreate {
	_c.mutation.SetErrorReason(v)
	return _c
}

// SetNillableErrorReason sets the "error_reason" field if the given value is not nil.
func (_c *ModelCallCreate) SetNillableErrorReason(v *string) *ModelCallCreate {
	if v != nil {
		_c.SetErrorReason(*v)
	}
	return _c
}

// SetErrorMessage sets the "error_message" field.
func (_c *ModelCallCreate) SetErrorMessage(v string) *ModelCallCreate {
	_c.mutation.SetErrorMessage(v)
	return _c
}

// SetNillableErrorMessage sets the "error_message" field if the given value is not nil.
func (_c *ModelCallCreate) SetNillableErrorMessage(v *string) *ModelCallCreate {
	if v != nil {
		_c.SetErrorMessage(*v)
	}
	return _c
}

// SetInputTokens sets the "input_tokens" field.
func (_c *ModelCallCreate) SetInputTokens(v int64) *ModelCallCreate {
	_c.mutation.SetInputTokens(v)
	return _c
}

// SetNillableInputTokens sets the "input_tokens" field if the given value is not nil.
func (_c *ModelCallCreate) SetNillableInputTokens(v *int64) *ModelCallCreate {
	if v != nil {
		_c.SetInputTokens(*v)
	}
	return _c
}

// SetOutputTokens sets the "output_tokens" field.
func (_c *ModelCallCreate) SetOutputTokens(v int64) *ModelCallCreate {
	_c.mutation.SetOutputTokens(v)
	return _c
}

// SetNillableOutputTokens sets the "output_tokens" field if the given value is not nil.
func (_c *ModelCallCreate) SetNillableOutputTokens(v *int64) *ModelCallCreate {
	if v != nil {
		_c.SetOutputTokens(*v)
	}
	return _c
}

// SetTotalTokens sets the "total_tokens" field.
func (_c *ModelCallCreate) SetTotalTokens(v int64) *ModelCallCreate {
	_c.mutation.SetTotalTokens(v)
	return _c
}

// SetNillableTotalTokens sets the "total_tokens" field if the given value is not nil.
func (_c *ModelCallCreate) SetNillableTotalTokens(v *int64) *ModelCallCreate {
	if v != nil {
		_c.SetTotalTokens(*v)
	}
	return _c
}

// SetCachedTokens sets the "cached_tokens" field.
func (_c *ModelCallCreate) SetCachedTokens(v int64) *ModelCallCreate {
	_c.mutation.SetCachedTokens(v)
	return _c
}

// SetNillableCachedTokens sets the "cached_tokens" field if the given value is not nil.
func (_c *ModelCallCreate) SetNillableCachedTokens(v *int64) *ModelCallCreate {
	if v != nil {
		_c.SetCachedTokens(*v)
	}
	return _c
}

// SetReasoningTokens sets the "reasoning_tokens" field.
func (_c *ModelCallCreate) SetReasoningTokens(v int64) *ModelCallCreate {
	_c.mutation.SetReasoningTokens(v)
	return _c
}

// SetNillableReasoningTokens sets the "reasoning_tokens" field if the given value is not nil.
func (_c *ModelCallCreate) SetNillableReasoningTokens(v *int64) *ModelCallCreate {
	if v != nil {
		_c.SetReasoningTokens(*v)
	}
	return _c
}

// SetImageCount sets the "image_count" field.
func (_c *ModelCallCreate) SetImageCount(v int) *ModelCallCreate {
	_c.mutation.SetImageCount(v)
	return _c
}

// SetNillableImageCount sets the "image_count" field if the given value is not nil.
func (_c *ModelCallCreate) SetNillableImageCount(v *int) *ModelCallCreate {
	if v != nil {
		_c.SetImageCount(*v)
	}
	return _c
}

// SetImageSize sets the "image_size" field.
func (_c *ModelCallCreate) SetImageSize(v string) *ModelCallCreate {
	_c.mutation.SetImageSize(v)
	return _c
}

// SetNillableImageSize sets the "image_size" field if the given value is not nil.
func (_c *ModelCallCreate) SetNillableImageSize(v *string) *ModelCallCreate {
	if v != nil {
		_c.SetImageSize(*v)
	}
	return _c
}

// SetImageAspectRatio sets the "image_aspect_ratio" field.
func (_c *ModelCallCreate) SetImageAspectRatio(v string) *ModelCallCreate {
	_c.mutation.SetImageAspectRatio(v)
	return _c
}

// SetNillableImageAspectRatio sets the "image_aspect_ratio" field if the given value is not nil.
func (_c *ModelCallCreate) SetNillableImageAspectRatio(v *string) *ModelCallCreate {
	if v != nil {
		_c.SetImageAspectRatio(*v)
	}
	return _c
}

// SetVideoCount sets the "video_count" field.
func (_c *ModelCallCreate) SetVideoCount(v int) *ModelCallCreate {
	_c.mutation.SetVideoCount(v)
	return _c
}

// SetNillableVideoCount sets the "video_count" field if the given value is not nil.
func (_c *ModelCallCreate) SetNillableVideoCount(v *int) *ModelCallCreate {
	if v != nil {
		_c.SetVideoCount(*v)
	}
	return _c
}

// SetVideoResolution sets the "video_resolution" field.
func (_c *ModelCallCreate) SetVideoResolution(v string) *ModelCallCreate {
	_c.mutation.SetVideoResolution(v)
	return _c
}

// SetNillableVideoResolution sets the "video_resolution" field if the given value is not nil.
func (_c *ModelCallCreate) SetNillableVideoResolution(v *string) *ModelCallCreate {
	if v != nil {
		_c.SetVideoResolution(*v)
	}
	return _c
}

// SetVideoDurationSeconds sets the "video_duration_seconds" field.
func (_c *ModelCallCreate) SetVideoDurationSeconds(v int) *ModelCallCreate {
	_c.mutation.SetVideoDurationSeconds(v)
	return _c
}

// SetNillableVideoDurationSeconds sets the "video_duration_seconds" field if the given value is not nil.
func (_c *ModelCallCreate) SetNillableVideoDurationSeconds(v *int) *ModelCallCreate {
	if v != nil {
		_c.SetVideoDurationSeconds(*v)
	}
	return _c
}

// SetVideoAspectRatio sets the "video_aspect_ratio" field.
func (_c *ModelCallCreate) SetVideoAspectRatio(v string) *ModelCallCreate {
	_c.mutation.SetVideoAspectRatio(v)
	return _c
}

// SetNillableVideoAspectRatio sets the "video_aspect_ratio" field if the given value is not nil.
func (_c *ModelCallCreate) SetNillableVideoAspectRatio(v *string) *ModelCallCreate {
	if v != nil {
		_c.SetVideoAspectRatio(*v)
	}
	return _c
}

// SetLatencyMs sets the "latency_ms" field.
func (_c *ModelCallCreate) SetLatencyMs(v int64) *ModelCallCreate {
	_c.mutation.SetLatencyMs(v)
	return _c
}

// SetNillableLatencyMs sets the "latency_ms" field if the given value is not nil.
func (_c *ModelCallCreate) SetNillableLatencyMs(v *int64) *ModelCallCreate {
	if v != nil {
		_c.SetLatencyMs(*v)
	}
	return _c
}

// SetStartedAt sets the "started_at" field.
func (_c *ModelCallCreate) SetStartedAt(v time.Time) *ModelCallCreate {
	_c.mutation.SetStartedAt(v)
	return _c
}

// SetFinishedAt sets the "finished_at" field.
func (_c *ModelCallCreate) SetFinishedAt(v time.Time) *ModelCallCreate {
	_c.mutation.SetFinishedAt(v)
	return _c
}

// SetNillableFinishedAt sets the "finished_at" field if the given value is not nil.
func (_c *ModelCallCreate) SetNillableFinishedAt(v *time.Time) *ModelCallCreate {
	if v != nil {
		_c.SetFinishedAt(*v)
	}
	return _c
}

// SetInputPayload sets the "input_payload" field.
func (_c *ModelCallCreate) SetInputPayload(v map[string]interface{}) *ModelCallCreate {
	_c.mutation.SetInputPayload(v)
	return _c
}

// SetOutputPayload sets the "output_payload" field.
func (_c *ModelCallCreate) SetOutputPayload(v map[string]interface{}) *ModelCallCreate {
	_c.mutation.SetOutputPayload(v)
	return _c
}

// SetUsageDetail sets the "usage_detail" field.
func (_c *ModelCallCreate) SetUsageDetail(v map[string]interface{}) *ModelCallCreate {
	_c.mutation.SetUsageDetail(v)
	return _c
}

// SetCreatedAt sets the "created_at" field.
func (_c *ModelCallCreate) SetCreatedAt(v time.Time) *ModelCallCreate {
	_c.mutation.SetCreatedAt(v)
	return _c
}

// SetNillableCreatedAt sets the "created_at" field if the given value is not nil.
func (_c *ModelCallCreate) SetNillableCreatedAt(v *time.Time) *ModelCallCreate {
	if v != nil {
		_c.SetCreatedAt(*v)
	}
	return _c
}

// SetUpdatedAt sets the "updated_at" field.
func (_c *ModelCallCreate) SetUpdatedAt(v time.Time) *ModelCallCreate {
	_c.mutation.SetUpdatedAt(v)
	return _c
}

// SetNillableUpdatedAt sets the "updated_at" field if the given value is not nil.
func (_c *ModelCallCreate) SetNillableUpdatedAt(v *time.Time) *ModelCallCreate {
	if v != nil {
		_c.SetUpdatedAt(*v)
	}
	return _c
}

// SetID sets the "id" field.
func (_c *ModelCallCreate) SetID(v string) *ModelCallCreate {
	_c.mutation.SetID(v)
	return _c
}

// Mutation returns the ModelCallMutation object of the builder.
func (_c *ModelCallCreate) Mutation() *ModelCallMutation {
	return _c.mutation
}

// Save creates the ModelCall in the database.
func (_c *ModelCallCreate) Save(ctx context.Context) (*ModelCall, error) {
	_c.defaults()
	return withHooks(ctx, _c.sqlSave, _c.mutation, _c.hooks)
}

// SaveX calls Save and panics if Save returns an error.
func (_c *ModelCallCreate) SaveX(ctx context.Context) *ModelCall {
	v, err := _c.Save(ctx)
	if err != nil {
		panic(err)
	}
	return v
}

// Exec executes the query.
func (_c *ModelCallCreate) Exec(ctx context.Context) error {
	_, err := _c.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_c *ModelCallCreate) ExecX(ctx context.Context) {
	if err := _c.Exec(ctx); err != nil {
		panic(err)
	}
}

// defaults sets the default values of the builder before save.
func (_c *ModelCallCreate) defaults() {
	if _, ok := _c.mutation.CallerService(); !ok {
		v := modelcall.DefaultCallerService
		_c.mutation.SetCallerService(v)
	}
	if _, ok := _c.mutation.BusinessScene(); !ok {
		v := modelcall.DefaultBusinessScene
		_c.mutation.SetBusinessScene(v)
	}
	if _, ok := _c.mutation.DeliveryStatus(); !ok {
		v := modelcall.DefaultDeliveryStatus
		_c.mutation.SetDeliveryStatus(v)
	}
	if _, ok := _c.mutation.ErrorCategory(); !ok {
		v := modelcall.DefaultErrorCategory
		_c.mutation.SetErrorCategory(v)
	}
	if _, ok := _c.mutation.ErrorCode(); !ok {
		v := modelcall.DefaultErrorCode
		_c.mutation.SetErrorCode(v)
	}
	if _, ok := _c.mutation.ErrorReason(); !ok {
		v := modelcall.DefaultErrorReason
		_c.mutation.SetErrorReason(v)
	}
	if _, ok := _c.mutation.ErrorMessage(); !ok {
		v := modelcall.DefaultErrorMessage
		_c.mutation.SetErrorMessage(v)
	}
	if _, ok := _c.mutation.ImageSize(); !ok {
		v := modelcall.DefaultImageSize
		_c.mutation.SetImageSize(v)
	}
	if _, ok := _c.mutation.ImageAspectRatio(); !ok {
		v := modelcall.DefaultImageAspectRatio
		_c.mutation.SetImageAspectRatio(v)
	}
	if _, ok := _c.mutation.VideoResolution(); !ok {
		v := modelcall.DefaultVideoResolution
		_c.mutation.SetVideoResolution(v)
	}
	if _, ok := _c.mutation.VideoAspectRatio(); !ok {
		v := modelcall.DefaultVideoAspectRatio
		_c.mutation.SetVideoAspectRatio(v)
	}
	if _, ok := _c.mutation.LatencyMs(); !ok {
		v := modelcall.DefaultLatencyMs
		_c.mutation.SetLatencyMs(v)
	}
	if _, ok := _c.mutation.InputPayload(); !ok {
		v := modelcall.DefaultInputPayload
		_c.mutation.SetInputPayload(v)
	}
	if _, ok := _c.mutation.OutputPayload(); !ok {
		v := modelcall.DefaultOutputPayload
		_c.mutation.SetOutputPayload(v)
	}
	if _, ok := _c.mutation.UsageDetail(); !ok {
		v := modelcall.DefaultUsageDetail
		_c.mutation.SetUsageDetail(v)
	}
	if _, ok := _c.mutation.CreatedAt(); !ok {
		v := modelcall.DefaultCreatedAt()
		_c.mutation.SetCreatedAt(v)
	}
	if _, ok := _c.mutation.UpdatedAt(); !ok {
		v := modelcall.DefaultUpdatedAt()
		_c.mutation.SetUpdatedAt(v)
	}
}

// check runs all checks and user-defined validators on the builder.
func (_c *ModelCallCreate) check() error {
	if _, ok := _c.mutation.CallerService(); !ok {
		return &ValidationError{Name: "caller_service", err: errors.New(`ent: missing required field "ModelCall.caller_service"`)}
	}
	if _, ok := _c.mutation.BusinessScene(); !ok {
		return &ValidationError{Name: "business_scene", err: errors.New(`ent: missing required field "ModelCall.business_scene"`)}
	}
	if _, ok := _c.mutation.Operation(); !ok {
		return &ValidationError{Name: "operation", err: errors.New(`ent: missing required field "ModelCall.operation"`)}
	}
	if _, ok := _c.mutation.Capability(); !ok {
		return &ValidationError{Name: "capability", err: errors.New(`ent: missing required field "ModelCall.capability"`)}
	}
	if _, ok := _c.mutation.Model(); !ok {
		return &ValidationError{Name: "model", err: errors.New(`ent: missing required field "ModelCall.model"`)}
	}
	if _, ok := _c.mutation.Provider(); !ok {
		return &ValidationError{Name: "provider", err: errors.New(`ent: missing required field "ModelCall.provider"`)}
	}
	if _, ok := _c.mutation.Status(); !ok {
		return &ValidationError{Name: "status", err: errors.New(`ent: missing required field "ModelCall.status"`)}
	}
	if _, ok := _c.mutation.DeliveryStatus(); !ok {
		return &ValidationError{Name: "delivery_status", err: errors.New(`ent: missing required field "ModelCall.delivery_status"`)}
	}
	if _, ok := _c.mutation.ErrorCategory(); !ok {
		return &ValidationError{Name: "error_category", err: errors.New(`ent: missing required field "ModelCall.error_category"`)}
	}
	if _, ok := _c.mutation.ErrorCode(); !ok {
		return &ValidationError{Name: "error_code", err: errors.New(`ent: missing required field "ModelCall.error_code"`)}
	}
	if _, ok := _c.mutation.ErrorReason(); !ok {
		return &ValidationError{Name: "error_reason", err: errors.New(`ent: missing required field "ModelCall.error_reason"`)}
	}
	if _, ok := _c.mutation.ErrorMessage(); !ok {
		return &ValidationError{Name: "error_message", err: errors.New(`ent: missing required field "ModelCall.error_message"`)}
	}
	if _, ok := _c.mutation.ImageSize(); !ok {
		return &ValidationError{Name: "image_size", err: errors.New(`ent: missing required field "ModelCall.image_size"`)}
	}
	if _, ok := _c.mutation.ImageAspectRatio(); !ok {
		return &ValidationError{Name: "image_aspect_ratio", err: errors.New(`ent: missing required field "ModelCall.image_aspect_ratio"`)}
	}
	if _, ok := _c.mutation.VideoResolution(); !ok {
		return &ValidationError{Name: "video_resolution", err: errors.New(`ent: missing required field "ModelCall.video_resolution"`)}
	}
	if _, ok := _c.mutation.VideoAspectRatio(); !ok {
		return &ValidationError{Name: "video_aspect_ratio", err: errors.New(`ent: missing required field "ModelCall.video_aspect_ratio"`)}
	}
	if _, ok := _c.mutation.LatencyMs(); !ok {
		return &ValidationError{Name: "latency_ms", err: errors.New(`ent: missing required field "ModelCall.latency_ms"`)}
	}
	if _, ok := _c.mutation.StartedAt(); !ok {
		return &ValidationError{Name: "started_at", err: errors.New(`ent: missing required field "ModelCall.started_at"`)}
	}
	if _, ok := _c.mutation.InputPayload(); !ok {
		return &ValidationError{Name: "input_payload", err: errors.New(`ent: missing required field "ModelCall.input_payload"`)}
	}
	if _, ok := _c.mutation.OutputPayload(); !ok {
		return &ValidationError{Name: "output_payload", err: errors.New(`ent: missing required field "ModelCall.output_payload"`)}
	}
	if _, ok := _c.mutation.UsageDetail(); !ok {
		return &ValidationError{Name: "usage_detail", err: errors.New(`ent: missing required field "ModelCall.usage_detail"`)}
	}
	if _, ok := _c.mutation.CreatedAt(); !ok {
		return &ValidationError{Name: "created_at", err: errors.New(`ent: missing required field "ModelCall.created_at"`)}
	}
	if _, ok := _c.mutation.UpdatedAt(); !ok {
		return &ValidationError{Name: "updated_at", err: errors.New(`ent: missing required field "ModelCall.updated_at"`)}
	}
	return nil
}

func (_c *ModelCallCreate) sqlSave(ctx context.Context) (*ModelCall, error) {
	if err := _c.check(); err != nil {
		return nil, err
	}
	_node, _spec := _c.createSpec()
	if err := sqlgraph.CreateNode(ctx, _c.driver, _spec); err != nil {
		if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return nil, err
	}
	if _spec.ID.Value != nil {
		if id, ok := _spec.ID.Value.(string); ok {
			_node.ID = id
		} else {
			return nil, fmt.Errorf("unexpected ModelCall.ID type: %T", _spec.ID.Value)
		}
	}
	_c.mutation.id = &_node.ID
	_c.mutation.done = true
	return _node, nil
}

func (_c *ModelCallCreate) createSpec() (*ModelCall, *sqlgraph.CreateSpec) {
	var (
		_node = &ModelCall{config: _c.config}
		_spec = sqlgraph.NewCreateSpec(modelcall.Table, sqlgraph.NewFieldSpec(modelcall.FieldID, field.TypeString))
	)
	_spec.Schema = _c.schemaConfig.ModelCall
	if id, ok := _c.mutation.ID(); ok {
		_node.ID = id
		_spec.ID.Value = id
	}
	if value, ok := _c.mutation.GenerationTaskID(); ok {
		_spec.SetField(modelcall.FieldGenerationTaskID, field.TypeString, value)
		_node.GenerationTaskID = &value
	}
	if value, ok := _c.mutation.CallerService(); ok {
		_spec.SetField(modelcall.FieldCallerService, field.TypeString, value)
		_node.CallerService = value
	}
	if value, ok := _c.mutation.BusinessScene(); ok {
		_spec.SetField(modelcall.FieldBusinessScene, field.TypeString, value)
		_node.BusinessScene = value
	}
	if value, ok := _c.mutation.Operation(); ok {
		_spec.SetField(modelcall.FieldOperation, field.TypeString, value)
		_node.Operation = value
	}
	if value, ok := _c.mutation.Capability(); ok {
		_spec.SetField(modelcall.FieldCapability, field.TypeString, value)
		_node.Capability = value
	}
	if value, ok := _c.mutation.Model(); ok {
		_spec.SetField(modelcall.FieldModel, field.TypeString, value)
		_node.Model = value
	}
	if value, ok := _c.mutation.Provider(); ok {
		_spec.SetField(modelcall.FieldProvider, field.TypeString, value)
		_node.Provider = value
	}
	if value, ok := _c.mutation.Status(); ok {
		_spec.SetField(modelcall.FieldStatus, field.TypeString, value)
		_node.Status = value
	}
	if value, ok := _c.mutation.DeliveryStatus(); ok {
		_spec.SetField(modelcall.FieldDeliveryStatus, field.TypeString, value)
		_node.DeliveryStatus = value
	}
	if value, ok := _c.mutation.ErrorCategory(); ok {
		_spec.SetField(modelcall.FieldErrorCategory, field.TypeString, value)
		_node.ErrorCategory = value
	}
	if value, ok := _c.mutation.ErrorCode(); ok {
		_spec.SetField(modelcall.FieldErrorCode, field.TypeString, value)
		_node.ErrorCode = value
	}
	if value, ok := _c.mutation.ErrorReason(); ok {
		_spec.SetField(modelcall.FieldErrorReason, field.TypeString, value)
		_node.ErrorReason = value
	}
	if value, ok := _c.mutation.ErrorMessage(); ok {
		_spec.SetField(modelcall.FieldErrorMessage, field.TypeString, value)
		_node.ErrorMessage = value
	}
	if value, ok := _c.mutation.InputTokens(); ok {
		_spec.SetField(modelcall.FieldInputTokens, field.TypeInt64, value)
		_node.InputTokens = &value
	}
	if value, ok := _c.mutation.OutputTokens(); ok {
		_spec.SetField(modelcall.FieldOutputTokens, field.TypeInt64, value)
		_node.OutputTokens = &value
	}
	if value, ok := _c.mutation.TotalTokens(); ok {
		_spec.SetField(modelcall.FieldTotalTokens, field.TypeInt64, value)
		_node.TotalTokens = &value
	}
	if value, ok := _c.mutation.CachedTokens(); ok {
		_spec.SetField(modelcall.FieldCachedTokens, field.TypeInt64, value)
		_node.CachedTokens = &value
	}
	if value, ok := _c.mutation.ReasoningTokens(); ok {
		_spec.SetField(modelcall.FieldReasoningTokens, field.TypeInt64, value)
		_node.ReasoningTokens = &value
	}
	if value, ok := _c.mutation.ImageCount(); ok {
		_spec.SetField(modelcall.FieldImageCount, field.TypeInt, value)
		_node.ImageCount = &value
	}
	if value, ok := _c.mutation.ImageSize(); ok {
		_spec.SetField(modelcall.FieldImageSize, field.TypeString, value)
		_node.ImageSize = value
	}
	if value, ok := _c.mutation.ImageAspectRatio(); ok {
		_spec.SetField(modelcall.FieldImageAspectRatio, field.TypeString, value)
		_node.ImageAspectRatio = value
	}
	if value, ok := _c.mutation.VideoCount(); ok {
		_spec.SetField(modelcall.FieldVideoCount, field.TypeInt, value)
		_node.VideoCount = &value
	}
	if value, ok := _c.mutation.VideoResolution(); ok {
		_spec.SetField(modelcall.FieldVideoResolution, field.TypeString, value)
		_node.VideoResolution = value
	}
	if value, ok := _c.mutation.VideoDurationSeconds(); ok {
		_spec.SetField(modelcall.FieldVideoDurationSeconds, field.TypeInt, value)
		_node.VideoDurationSeconds = &value
	}
	if value, ok := _c.mutation.VideoAspectRatio(); ok {
		_spec.SetField(modelcall.FieldVideoAspectRatio, field.TypeString, value)
		_node.VideoAspectRatio = value
	}
	if value, ok := _c.mutation.LatencyMs(); ok {
		_spec.SetField(modelcall.FieldLatencyMs, field.TypeInt64, value)
		_node.LatencyMs = value
	}
	if value, ok := _c.mutation.StartedAt(); ok {
		_spec.SetField(modelcall.FieldStartedAt, field.TypeTime, value)
		_node.StartedAt = value
	}
	if value, ok := _c.mutation.FinishedAt(); ok {
		_spec.SetField(modelcall.FieldFinishedAt, field.TypeTime, value)
		_node.FinishedAt = &value
	}
	if value, ok := _c.mutation.InputPayload(); ok {
		_spec.SetField(modelcall.FieldInputPayload, field.TypeJSON, value)
		_node.InputPayload = value
	}
	if value, ok := _c.mutation.OutputPayload(); ok {
		_spec.SetField(modelcall.FieldOutputPayload, field.TypeJSON, value)
		_node.OutputPayload = value
	}
	if value, ok := _c.mutation.UsageDetail(); ok {
		_spec.SetField(modelcall.FieldUsageDetail, field.TypeJSON, value)
		_node.UsageDetail = value
	}
	if value, ok := _c.mutation.CreatedAt(); ok {
		_spec.SetField(modelcall.FieldCreatedAt, field.TypeTime, value)
		_node.CreatedAt = value
	}
	if value, ok := _c.mutation.UpdatedAt(); ok {
		_spec.SetField(modelcall.FieldUpdatedAt, field.TypeTime, value)
		_node.UpdatedAt = value
	}
	return _node, _spec
}

// ModelCallCreateBulk is the builder for creating many ModelCall entities in bulk.
type ModelCallCreateBulk struct {
	config
	err      error
	builders []*ModelCallCreate
}

// Save creates the ModelCall entities in the database.
func (_c *ModelCallCreateBulk) Save(ctx context.Context) ([]*ModelCall, error) {
	if _c.err != nil {
		return nil, _c.err
	}
	specs := make([]*sqlgraph.CreateSpec, len(_c.builders))
	nodes := make([]*ModelCall, len(_c.builders))
	mutators := make([]Mutator, len(_c.builders))
	for i := range _c.builders {
		func(i int, root context.Context) {
			builder := _c.builders[i]
			builder.defaults()
			var mut Mutator = MutateFunc(func(ctx context.Context, m Mutation) (Value, error) {
				mutation, ok := m.(*ModelCallMutation)
				if !ok {
					return nil, fmt.Errorf("unexpected mutation type %T", m)
				}
				if err := builder.check(); err != nil {
					return nil, err
				}
				builder.mutation = mutation
				var err error
				nodes[i], specs[i] = builder.createSpec()
				if i < len(mutators)-1 {
					_, err = mutators[i+1].Mutate(root, _c.builders[i+1].mutation)
				} else {
					spec := &sqlgraph.BatchCreateSpec{Nodes: specs}
					// Invoke the actual operation on the latest mutation in the chain.
					if err = sqlgraph.BatchCreate(ctx, _c.driver, spec); err != nil {
						if sqlgraph.IsConstraintError(err) {
							err = &ConstraintError{msg: err.Error(), wrap: err}
						}
					}
				}
				if err != nil {
					return nil, err
				}
				mutation.id = &nodes[i].ID
				mutation.done = true
				return nodes[i], nil
			})
			for i := len(builder.hooks) - 1; i >= 0; i-- {
				mut = builder.hooks[i](mut)
			}
			mutators[i] = mut
		}(i, ctx)
	}
	if len(mutators) > 0 {
		if _, err := mutators[0].Mutate(ctx, _c.builders[0].mutation); err != nil {
			return nil, err
		}
	}
	return nodes, nil
}

// SaveX is like Save, but panics if an error occurs.
func (_c *ModelCallCreateBulk) SaveX(ctx context.Context) []*ModelCall {
	v, err := _c.Save(ctx)
	if err != nil {
		panic(err)
	}
	return v
}

// Exec executes the query.
func (_c *ModelCallCreateBulk) Exec(ctx context.Context) error {
	_, err := _c.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_c *ModelCallCreateBulk) ExecX(ctx context.Context) {
	if err := _c.Exec(ctx); err != nil {
		panic(err)
	}
}
