// Code generated by ent, DO NOT EDIT.

package ent

import (
	"context"
	"errors"
	"fmt"
	"sync"
	"time"

	"entgo.io/ent"
	"entgo.io/ent/dialect/sql"
	"github.com/wgdl666/wgModelHub/ent/generationtask"
	"github.com/wgdl666/wgModelHub/ent/modelhubapikey"
	"github.com/wgdl666/wgModelHub/ent/predicate"
)

const (
	// Operation types.
	OpCreate    = ent.OpCreate
	OpDelete    = ent.OpDelete
	OpDeleteOne = ent.OpDeleteOne
	OpUpdate    = ent.OpUpdate
	OpUpdateOne = ent.OpUpdateOne

	// Node types.
	TypeGenerationTask = "GenerationTask"
	TypeModelhubAPIKey = "ModelhubAPIKey"
)

// GenerationTaskMutation represents an operation that mutates the GenerationTask nodes in the graph.
type GenerationTaskMutation struct {
	config
	op               Op
	typ              string
	id               *string
	caller           *string
	request_id       *string
	request_hash     *string
	model            *string
	provider         *string
	provider_task_id *string
	state            *string
	error_code       *int32
	adderror_code    *int32
	error_message    *string
	error_reason     *string
	created_at       *time.Time
	updated_at       *time.Time
	clearedFields    map[string]struct{}
	done             bool
	oldValue         func(context.Context) (*GenerationTask, error)
	predicates       []predicate.GenerationTask
}

var _ ent.Mutation = (*GenerationTaskMutation)(nil)

// generationtaskOption allows management of the mutation configuration using functional options.
type generationtaskOption func(*GenerationTaskMutation)

// newGenerationTaskMutation creates new mutation for the GenerationTask entity.
func newGenerationTaskMutation(c config, op Op, opts ...generationtaskOption) *GenerationTaskMutation {
	m := &GenerationTaskMutation{
		config:        c,
		op:            op,
		typ:           TypeGenerationTask,
		clearedFields: make(map[string]struct{}),
	}
	for _, opt := range opts {
		opt(m)
	}
	return m
}

// withGenerationTaskID sets the ID field of the mutation.
func withGenerationTaskID(id string) generationtaskOption {
	return func(m *GenerationTaskMutation) {
		var (
			err   error
			once  sync.Once
			value *GenerationTask
		)
		m.oldValue = func(ctx context.Context) (*GenerationTask, error) {
			once.Do(func() {
				if m.done {
					err = errors.New("querying old values post mutation is not allowed")
				} else {
					value, err = m.Client().GenerationTask.Get(ctx, id)
				}
			})
			return value, err
		}
		m.id = &id
	}
}

// withGenerationTask sets the old GenerationTask of the mutation.
func withGenerationTask(node *GenerationTask) generationtaskOption {
	return func(m *GenerationTaskMutation) {
		m.oldValue = func(context.Context) (*GenerationTask, error) {
			return node, nil
		}
		m.id = &node.ID
	}
}

// Client returns a new `ent.Client` from the mutation. If the mutation was
// executed in a transaction (ent.Tx), a transactional client is returned.
func (m GenerationTaskMutation) Client() *Client {
	client := &Client{config: m.config}
	client.init()
	return client
}

// Tx returns an `ent.Tx` for mutations that were executed in transactions;
// it returns an error otherwise.
func (m GenerationTaskMutation) Tx() (*Tx, error) {
	if _, ok := m.driver.(*txDriver); !ok {
		return nil, errors.New("ent: mutation is not running in a transaction")
	}
	tx := &Tx{config: m.config}
	tx.init()
	return tx, nil
}

// SetID sets the value of the id field. Note that this
// operation is only accepted on creation of GenerationTask entities.
func (m *GenerationTaskMutation) SetID(id string) {
	m.id = &id
}

// ID returns the ID value in the mutation. Note that the ID is only available
// if it was provided to the builder or after it was returned from the database.
func (m *GenerationTaskMutation) ID() (id string, exists bool) {
	if m.id == nil {
		return
	}
	return *m.id, true
}

// IDs queries the database and returns the entity ids that match the mutation's predicate.
// That means, if the mutation is applied within a transaction with an isolation level such
// as sql.LevelSerializable, the returned ids match the ids of the rows that will be updated
// or updated by the mutation.
func (m *GenerationTaskMutation) IDs(ctx context.Context) ([]string, error) {
	switch {
	case m.op.Is(OpUpdateOne | OpDeleteOne):
		id, exists := m.ID()
		if exists {
			return []string{id}, nil
		}
		fallthrough
	case m.op.Is(OpUpdate | OpDelete):
		return m.Client().GenerationTask.Query().Where(m.predicates...).IDs(ctx)
	default:
		return nil, fmt.Errorf("IDs is not allowed on %s operations", m.op)
	}
}

// SetCaller sets the "caller" field.
func (m *GenerationTaskMutation) SetCaller(s string) {
	m.caller = &s
}

// Caller returns the value of the "caller" field in the mutation.
func (m *GenerationTaskMutation) Caller() (r string, exists bool) {
	v := m.caller
	if v == nil {
		return
	}
	return *v, true
}

// OldCaller returns the old "caller" field's value of the GenerationTask entity.
// If the GenerationTask object wasn't provided to the builder, the object is fetched from the database.
// An error is returned if the mutation operation is not UpdateOne, or the database query fails.
func (m *GenerationTaskMutation) OldCaller(ctx context.Context) (v string, err error) {
	if !m.op.Is(OpUpdateOne) {
		return v, errors.New("OldCaller is only allowed on UpdateOne operations")
	}
	if m.id == nil || m.oldValue == nil {
		return v, errors.New("OldCaller requires an ID field in the mutation")
	}
	oldValue, err := m.oldValue(ctx)
	if err != nil {
		return v, fmt.Errorf("querying old value for OldCaller: %w", err)
	}
	return oldValue.Caller, nil
}

// ResetCaller resets all changes to the "caller" field.
func (m *GenerationTaskMutation) ResetCaller() {
	m.caller = nil
}

// SetRequestID sets the "request_id" field.
func (m *GenerationTaskMutation) SetRequestID(s string) {
	m.request_id = &s
}

// RequestID returns the value of the "request_id" field in the mutation.
func (m *GenerationTaskMutation) RequestID() (r string, exists bool) {
	v := m.request_id
	if v == nil {
		return
	}
	return *v, true
}

// OldRequestID returns the old "request_id" field's value of the GenerationTask entity.
// If the GenerationTask object wasn't provided to the builder, the object is fetched from the database.
// An error is returned if the mutation operation is not UpdateOne, or the database query fails.
func (m *GenerationTaskMutation) OldRequestID(ctx context.Context) (v string, err error) {
	if !m.op.Is(OpUpdateOne) {
		return v, errors.New("OldRequestID is only allowed on UpdateOne operations")
	}
	if m.id == nil || m.oldValue == nil {
		return v, errors.New("OldRequestID requires an ID field in the mutation")
	}
	oldValue, err := m.oldValue(ctx)
	if err != nil {
		return v, fmt.Errorf("querying old value for OldRequestID: %w", err)
	}
	return oldValue.RequestID, nil
}

// ResetRequestID resets all changes to the "request_id" field.
func (m *GenerationTaskMutation) ResetRequestID() {
	m.request_id = nil
}

// SetRequestHash sets the "request_hash" field.
func (m *GenerationTaskMutation) SetRequestHash(s string) {
	m.request_hash = &s
}

// RequestHash returns the value of the "request_hash" field in the mutation.
func (m *GenerationTaskMutation) RequestHash() (r string, exists bool) {
	v := m.request_hash
	if v == nil {
		return
	}
	return *v, true
}

// OldRequestHash returns the old "request_hash" field's value of the GenerationTask entity.
// If the GenerationTask object wasn't provided to the builder, the object is fetched from the database.
// An error is returned if the mutation operation is not UpdateOne, or the database query fails.
func (m *GenerationTaskMutation) OldRequestHash(ctx context.Context) (v string, err error) {
	if !m.op.Is(OpUpdateOne) {
		return v, errors.New("OldRequestHash is only allowed on UpdateOne operations")
	}
	if m.id == nil || m.oldValue == nil {
		return v, errors.New("OldRequestHash requires an ID field in the mutation")
	}
	oldValue, err := m.oldValue(ctx)
	if err != nil {
		return v, fmt.Errorf("querying old value for OldRequestHash: %w", err)
	}
	return oldValue.RequestHash, nil
}

// ResetRequestHash resets all changes to the "request_hash" field.
func (m *GenerationTaskMutation) ResetRequestHash() {
	m.request_hash = nil
}

// SetModel sets the "model" field.
func (m *GenerationTaskMutation) SetModel(s string) {
	m.model = &s
}

// Model returns the value of the "model" field in the mutation.
func (m *GenerationTaskMutation) Model() (r string, exists bool) {
	v := m.model
	if v == nil {
		return
	}
	return *v, true
}

// OldModel returns the old "model" field's value of the GenerationTask entity.
// If the GenerationTask object wasn't provided to the builder, the object is fetched from the database.
// An error is returned if the mutation operation is not UpdateOne, or the database query fails.
func (m *GenerationTaskMutation) OldModel(ctx context.Context) (v string, err error) {
	if !m.op.Is(OpUpdateOne) {
		return v, errors.New("OldModel is only allowed on UpdateOne operations")
	}
	if m.id == nil || m.oldValue == nil {
		return v, errors.New("OldModel requires an ID field in the mutation")
	}
	oldValue, err := m.oldValue(ctx)
	if err != nil {
		return v, fmt.Errorf("querying old value for OldModel: %w", err)
	}
	return oldValue.Model, nil
}

// ResetModel resets all changes to the "model" field.
func (m *GenerationTaskMutation) ResetModel() {
	m.model = nil
}

// SetProvider sets the "provider" field.
func (m *GenerationTaskMutation) SetProvider(s string) {
	m.provider = &s
}

// Provider returns the value of the "provider" field in the mutation.
func (m *GenerationTaskMutation) Provider() (r string, exists bool) {
	v := m.provider
	if v == nil {
		return
	}
	return *v, true
}

// OldProvider returns the old "provider" field's value of the GenerationTask entity.
// If the GenerationTask object wasn't provided to the builder, the object is fetched from the database.
// An error is returned if the mutation operation is not UpdateOne, or the database query fails.
func (m *GenerationTaskMutation) OldProvider(ctx context.Context) (v string, err error) {
	if !m.op.Is(OpUpdateOne) {
		return v, errors.New("OldProvider is only allowed on UpdateOne operations")
	}
	if m.id == nil || m.oldValue == nil {
		return v, errors.New("OldProvider requires an ID field in the mutation")
	}
	oldValue, err := m.oldValue(ctx)
	if err != nil {
		return v, fmt.Errorf("querying old value for OldProvider: %w", err)
	}
	return oldValue.Provider, nil
}

// ResetProvider resets all changes to the "provider" field.
func (m *GenerationTaskMutation) ResetProvider() {
	m.provider = nil
}

// SetProviderTaskID sets the "provider_task_id" field.
func (m *GenerationTaskMutation) SetProviderTaskID(s string) {
	m.provider_task_id = &s
}

// ProviderTaskID returns the value of the "provider_task_id" field in the mutation.
func (m *GenerationTaskMutation) ProviderTaskID() (r string, exists bool) {
	v := m.provider_task_id
	if v == nil {
		return
	}
	return *v, true
}

// OldProviderTaskID returns the old "provider_task_id" field's value of the GenerationTask entity.
// If the GenerationTask object wasn't provided to the builder, the object is fetched from the database.
// An error is returned if the mutation operation is not UpdateOne, or the database query fails.
func (m *GenerationTaskMutation) OldProviderTaskID(ctx context.Context) (v string, err error) {
	if !m.op.Is(OpUpdateOne) {
		return v, errors.New("OldProviderTaskID is only allowed on UpdateOne operations")
	}
	if m.id == nil || m.oldValue == nil {
		return v, errors.New("OldProviderTaskID requires an ID field in the mutation")
	}
	oldValue, err := m.oldValue(ctx)
	if err != nil {
		return v, fmt.Errorf("querying old value for OldProviderTaskID: %w", err)
	}
	return oldValue.ProviderTaskID, nil
}

// ResetProviderTaskID resets all changes to the "provider_task_id" field.
func (m *GenerationTaskMutation) ResetProviderTaskID() {
	m.provider_task_id = nil
}

// SetState sets the "state" field.
func (m *GenerationTaskMutation) SetState(s string) {
	m.state = &s
}

// State returns the value of the "state" field in the mutation.
func (m *GenerationTaskMutation) State() (r string, exists bool) {
	v := m.state
	if v == nil {
		return
	}
	return *v, true
}

// OldState returns the old "state" field's value of the GenerationTask entity.
// If the GenerationTask object wasn't provided to the builder, the object is fetched from the database.
// An error is returned if the mutation operation is not UpdateOne, or the database query fails.
func (m *GenerationTaskMutation) OldState(ctx context.Context) (v string, err error) {
	if !m.op.Is(OpUpdateOne) {
		return v, errors.New("OldState is only allowed on UpdateOne operations")
	}
	if m.id == nil || m.oldValue == nil {
		return v, errors.New("OldState requires an ID field in the mutation")
	}
	oldValue, err := m.oldValue(ctx)
	if err != nil {
		return v, fmt.Errorf("querying old value for OldState: %w", err)
	}
	return oldValue.State, nil
}

// ResetState resets all changes to the "state" field.
func (m *GenerationTaskMutation) ResetState() {
	m.state = nil
}

// SetErrorCode sets the "error_code" field.
func (m *GenerationTaskMutation) SetErrorCode(i int32) {
	m.error_code = &i
	m.adderror_code = nil
}

// ErrorCode returns the value of the "error_code" field in the mutation.
func (m *GenerationTaskMutation) ErrorCode() (r int32, exists bool) {
	v := m.error_code
	if v == nil {
		return
	}
	return *v, true
}

// OldErrorCode returns the old "error_code" field's value of the GenerationTask entity.
// If the GenerationTask object wasn't provided to the builder, the object is fetched from the database.
// An error is returned if the mutation operation is not UpdateOne, or the database query fails.
func (m *GenerationTaskMutation) OldErrorCode(ctx context.Context) (v int32, err error) {
	if !m.op.Is(OpUpdateOne) {
		return v, errors.New("OldErrorCode is only allowed on UpdateOne operations")
	}
	if m.id == nil || m.oldValue == nil {
		return v, errors.New("OldErrorCode requires an ID field in the mutation")
	}
	oldValue, err := m.oldValue(ctx)
	if err != nil {
		return v, fmt.Errorf("querying old value for OldErrorCode: %w", err)
	}
	return oldValue.ErrorCode, nil
}

// AddErrorCode adds i to the "error_code" field.
func (m *GenerationTaskMutation) AddErrorCode(i int32) {
	if m.adderror_code != nil {
		*m.adderror_code += i
	} else {
		m.adderror_code = &i
	}
}

// AddedErrorCode returns the value that was added to the "error_code" field in this mutation.
func (m *GenerationTaskMutation) AddedErrorCode() (r int32, exists bool) {
	v := m.adderror_code
	if v == nil {
		return
	}
	return *v, true
}

// ResetErrorCode resets all changes to the "error_code" field.
func (m *GenerationTaskMutation) ResetErrorCode() {
	m.error_code = nil
	m.adderror_code = nil
}

// SetErrorMessage sets the "error_message" field.
func (m *GenerationTaskMutation) SetErrorMessage(s string) {
	m.error_message = &s
}

// ErrorMessage returns the value of the "error_message" field in the mutation.
func (m *GenerationTaskMutation) ErrorMessage() (r string, exists bool) {
	v := m.error_message
	if v == nil {
		return
	}
	return *v, true
}

// OldErrorMessage returns the old "error_message" field's value of the GenerationTask entity.
// If the GenerationTask object wasn't provided to the builder, the object is fetched from the database.
// An error is returned if the mutation operation is not UpdateOne, or the database query fails.
func (m *GenerationTaskMutation) OldErrorMessage(ctx context.Context) (v string, err error) {
	if !m.op.Is(OpUpdateOne) {
		return v, errors.New("OldErrorMessage is only allowed on UpdateOne operations")
	}
	if m.id == nil || m.oldValue == nil {
		return v, errors.New("OldErrorMessage requires an ID field in the mutation")
	}
	oldValue, err := m.oldValue(ctx)
	if err != nil {
		return v, fmt.Errorf("querying old value for OldErrorMessage: %w", err)
	}
	return oldValue.ErrorMessage, nil
}

// ResetErrorMessage resets all changes to the "error_message" field.
func (m *GenerationTaskMutation) ResetErrorMessage() {
	m.error_message = nil
}

// SetErrorReason sets the "error_reason" field.
func (m *GenerationTaskMutation) SetErrorReason(s string) {
	m.error_reason = &s
}

// ErrorReason returns the value of the "error_reason" field in the mutation.
func (m *GenerationTaskMutation) ErrorReason() (r string, exists bool) {
	v := m.error_reason
	if v == nil {
		return
	}
	return *v, true
}

// OldErrorReason returns the old "error_reason" field's value of the GenerationTask entity.
// If the GenerationTask object wasn't provided to the builder, the object is fetched from the database.
// An error is returned if the mutation operation is not UpdateOne, or the database query fails.
func (m *GenerationTaskMutation) OldErrorReason(ctx context.Context) (v string, err error) {
	if !m.op.Is(OpUpdateOne) {
		return v, errors.New("OldErrorReason is only allowed on UpdateOne operations")
	}
	if m.id == nil || m.oldValue == nil {
		return v, errors.New("OldErrorReason requires an ID field in the mutation")
	}
	oldValue, err := m.oldValue(ctx)
	if err != nil {
		return v, fmt.Errorf("querying old value for OldErrorReason: %w", err)
	}
	return oldValue.ErrorReason, nil
}

// ResetErrorReason resets all changes to the "error_reason" field.
func (m *GenerationTaskMutation) ResetErrorReason() {
	m.error_reason = nil
}

// SetCreatedAt sets the "created_at" field.
func (m *GenerationTaskMutation) SetCreatedAt(t time.Time) {
	m.created_at = &t
}

// CreatedAt returns the value of the "created_at" field in the mutation.
func (m *GenerationTaskMutation) CreatedAt() (r time.Time, exists bool) {
	v := m.created_at
	if v == nil {
		return
	}
	return *v, true
}

// OldCreatedAt returns the old "created_at" field's value of the GenerationTask entity.
// If the GenerationTask object wasn't provided to the builder, the object is fetched from the database.
// An error is returned if the mutation operation is not UpdateOne, or the database query fails.
func (m *GenerationTaskMutation) OldCreatedAt(ctx context.Context) (v time.Time, err error) {
	if !m.op.Is(OpUpdateOne) {
		return v, errors.New("OldCreatedAt is only allowed on UpdateOne operations")
	}
	if m.id == nil || m.oldValue == nil {
		return v, errors.New("OldCreatedAt requires an ID field in the mutation")
	}
	oldValue, err := m.oldValue(ctx)
	if err != nil {
		return v, fmt.Errorf("querying old value for OldCreatedAt: %w", err)
	}
	return oldValue.CreatedAt, nil
}

// ResetCreatedAt resets all changes to the "created_at" field.
func (m *GenerationTaskMutation) ResetCreatedAt() {
	m.created_at = nil
}

// SetUpdatedAt sets the "updated_at" field.
func (m *GenerationTaskMutation) SetUpdatedAt(t time.Time) {
	m.updated_at = &t
}

// UpdatedAt returns the value of the "updated_at" field in the mutation.
func (m *GenerationTaskMutation) UpdatedAt() (r time.Time, exists bool) {
	v := m.updated_at
	if v == nil {
		return
	}
	return *v, true
}

// OldUpdatedAt returns the old "updated_at" field's value of the GenerationTask entity.
// If the GenerationTask object wasn't provided to the builder, the object is fetched from the database.
// An error is returned if the mutation operation is not UpdateOne, or the database query fails.
func (m *GenerationTaskMutation) OldUpdatedAt(ctx context.Context) (v time.Time, err error) {
	if !m.op.Is(OpUpdateOne) {
		return v, errors.New("OldUpdatedAt is only allowed on UpdateOne operations")
	}
	if m.id == nil || m.oldValue == nil {
		return v, errors.New("OldUpdatedAt requires an ID field in the mutation")
	}
	oldValue, err := m.oldValue(ctx)
	if err != nil {
		return v, fmt.Errorf("querying old value for OldUpdatedAt: %w", err)
	}
	return oldValue.UpdatedAt, nil
}

// ResetUpdatedAt resets all changes to the "updated_at" field.
func (m *GenerationTaskMutation) ResetUpdatedAt() {
	m.updated_at = nil
}

// Where appends a list predicates to the GenerationTaskMutation builder.
func (m *GenerationTaskMutation) Where(ps ...predicate.GenerationTask) {
	m.predicates = append(m.predicates, ps...)
}

// WhereP appends storage-level predicates to the GenerationTaskMutation builder. Using this method,
// users can use type-assertion to append predicates that do not depend on any generated package.
func (m *GenerationTaskMutation) WhereP(ps ...func(*sql.Selector)) {
	p := make([]predicate.GenerationTask, len(ps))
	for i := range ps {
		p[i] = ps[i]
	}
	m.Where(p...)
}

// Op returns the operation name.
func (m *GenerationTaskMutation) Op() Op {
	return m.op
}

// SetOp allows setting the mutation operation.
func (m *GenerationTaskMutation) SetOp(op Op) {
	m.op = op
}

// Type returns the node type of this mutation (GenerationTask).
func (m *GenerationTaskMutation) Type() string {
	return m.typ
}

// Fields returns all fields that were changed during this mutation. Note that in
// order to get all numeric fields that were incremented/decremented, call
// AddedFields().
func (m *GenerationTaskMutation) Fields() []string {
	fields := make([]string, 0, 12)
	if m.caller != nil {
		fields = append(fields, generationtask.FieldCaller)
	}
	if m.request_id != nil {
		fields = append(fields, generationtask.FieldRequestID)
	}
	if m.request_hash != nil {
		fields = append(fields, generationtask.FieldRequestHash)
	}
	if m.model != nil {
		fields = append(fields, generationtask.FieldModel)
	}
	if m.provider != nil {
		fields = append(fields, generationtask.FieldProvider)
	}
	if m.provider_task_id != nil {
		fields = append(fields, generationtask.FieldProviderTaskID)
	}
	if m.state != nil {
		fields = append(fields, generationtask.FieldState)
	}
	if m.error_code != nil {
		fields = append(fields, generationtask.FieldErrorCode)
	}
	if m.error_message != nil {
		fields = append(fields, generationtask.FieldErrorMessage)
	}
	if m.error_reason != nil {
		fields = append(fields, generationtask.FieldErrorReason)
	}
	if m.created_at != nil {
		fields = append(fields, generationtask.FieldCreatedAt)
	}
	if m.updated_at != nil {
		fields = append(fields, generationtask.FieldUpdatedAt)
	}
	return fields
}

// Field returns the value of a field with the given name. The second boolean
// return value indicates that this field was not set, or was not defined in the
// schema.
func (m *GenerationTaskMutation) Field(name string) (ent.Value, bool) {
	switch name {
	case generationtask.FieldCaller:
		return m.Caller()
	case generationtask.FieldRequestID:
		return m.RequestID()
	case generationtask.FieldRequestHash:
		return m.RequestHash()
	case generationtask.FieldModel:
		return m.Model()
	case generationtask.FieldProvider:
		return m.Provider()
	case generationtask.FieldProviderTaskID:
		return m.ProviderTaskID()
	case generationtask.FieldState:
		return m.State()
	case generationtask.FieldErrorCode:
		return m.ErrorCode()
	case generationtask.FieldErrorMessage:
		return m.ErrorMessage()
	case generationtask.FieldErrorReason:
		return m.ErrorReason()
	case generationtask.FieldCreatedAt:
		return m.CreatedAt()
	case generationtask.FieldUpdatedAt:
		return m.UpdatedAt()
	}
	return nil, false
}

// OldField returns the old value of the field from the database. An error is
// returned if the mutation operation is not UpdateOne, or the query to the
// database failed.
func (m *GenerationTaskMutation) OldField(ctx context.Context, name string) (ent.Value, error) {
	switch name {
	case generationtask.FieldCaller:
		return m.OldCaller(ctx)
	case generationtask.FieldRequestID:
		return m.OldRequestID(ctx)
	case generationtask.FieldRequestHash:
		return m.OldRequestHash(ctx)
	case generationtask.FieldModel:
		return m.OldModel(ctx)
	case generationtask.FieldProvider:
		return m.OldProvider(ctx)
	case generationtask.FieldProviderTaskID:
		return m.OldProviderTaskID(ctx)
	case generationtask.FieldState:
		return m.OldState(ctx)
	case generationtask.FieldErrorCode:
		return m.OldErrorCode(ctx)
	case generationtask.FieldErrorMessage:
		return m.OldErrorMessage(ctx)
	case generationtask.FieldErrorReason:
		return m.OldErrorReason(ctx)
	case generationtask.FieldCreatedAt:
		return m.OldCreatedAt(ctx)
	case generationtask.FieldUpdatedAt:
		return m.OldUpdatedAt(ctx)
	}
	return nil, fmt.Errorf("unknown GenerationTask field %s", name)
}

// SetField sets the value of a field with the given name. It returns an error if
// the field is not defined in the schema, or if the type mismatched the field
// type.
func (m *GenerationTaskMutation) SetField(name string, value ent.Value) error {
	switch name {
	case generationtask.FieldCaller:
		v, ok := value.(string)
		if !ok {
			return fmt.Errorf("unexpected type %T for field %s", value, name)
		}
		m.SetCaller(v)
		return nil
	case generationtask.FieldRequestID:
		v, ok := value.(string)
		if !ok {
			return fmt.Errorf("unexpected type %T for field %s", value, name)
		}
		m.SetRequestID(v)
		return nil
	case generationtask.FieldRequestHash:
		v, ok := value.(string)
		if !ok {
			return fmt.Errorf("unexpected type %T for field %s", value, name)
		}
		m.SetRequestHash(v)
		return nil
	case generationtask.FieldModel:
		v, ok := value.(string)
		if !ok {
			return fmt.Errorf("unexpected type %T for field %s", value, name)
		}
		m.SetModel(v)
		return nil
	case generationtask.FieldProvider:
		v, ok := value.(string)
		if !ok {
			return fmt.Errorf("unexpected type %T for field %s", value, name)
		}
		m.SetProvider(v)
		return nil
	case generationtask.FieldProviderTaskID:
		v, ok := value.(string)
		if !ok {
			return fmt.Errorf("unexpected type %T for field %s", value, name)
		}
		m.SetProviderTaskID(v)
		return nil
	case generationtask.FieldState:
		v, ok := value.(string)
		if !ok {
			return fmt.Errorf("unexpected type %T for field %s", value, name)
		}
		m.SetState(v)
		return nil
	case generationtask.FieldErrorCode:
		v, ok := value.(int32)
		if !ok {
			return fmt.Errorf("unexpected type %T for field %s", value, name)
		}
		m.SetErrorCode(v)
		return nil
	case generationtask.FieldErrorMessage:
		v, ok := value.(string)
		if !ok {
			return fmt.Errorf("unexpected type %T for field %s", value, name)
		}
		m.SetErrorMessage(v)
		return nil
	case generationtask.FieldErrorReason:
		v, ok := value.(string)
		if !ok {
			return fmt.Errorf("unexpected type %T for field %s", value, name)
		}
		m.SetErrorReason(v)
		return nil
	case generationtask.FieldCreatedAt:
		v, ok := value.(time.Time)
		if !ok {
			return fmt.Errorf("unexpected type %T for field %s", value, name)
		}
		m.SetCreatedAt(v)
		return nil
	case generationtask.FieldUpdatedAt:
		v, ok := value.(time.Time)
		if !ok {
			return fmt.Errorf("unexpected type %T for field %s", value, name)
		}
		m.SetUpdatedAt(v)
		return nil
	}
	return fmt.Errorf("unknown GenerationTask field %s", name)
}

// AddedFields returns all numeric fields that were incremented/decremented during
// this mutation.
func (m *GenerationTaskMutation) AddedFields() []string {
	var fields []string
	if m.adderror_code != nil {
		fields = append(fields, generationtask.FieldErrorCode)
	}
	return fields
}

// AddedField returns the numeric value that was incremented/decremented on a field
// with the given name. The second boolean return value indicates that this field
// was not set, or was not defined in the schema.
func (m *GenerationTaskMutation) AddedField(name string) (ent.Value, bool) {
	switch name {
	case generationtask.FieldErrorCode:
		return m.AddedErrorCode()
	}
	return nil, false
}

// AddField adds the value to the field with the given name. It returns an error if
// the field is not defined in the schema, or if the type mismatched the field
// type.
func (m *GenerationTaskMutation) AddField(name string, value ent.Value) error {
	switch name {
	case generationtask.FieldErrorCode:
		v, ok := value.(int32)
		if !ok {
			return fmt.Errorf("unexpected type %T for field %s", value, name)
		}
		m.AddErrorCode(v)
		return nil
	}
	return fmt.Errorf("unknown GenerationTask numeric field %s", name)
}

// ClearedFields returns all nullable fields that were cleared during this
// mutation.
func (m *GenerationTaskMutation) ClearedFields() []string {
	return nil
}

// FieldCleared returns a boolean indicating if a field with the given name was
// cleared in this mutation.
func (m *GenerationTaskMutation) FieldCleared(name string) bool {
	_, ok := m.clearedFields[name]
	return ok
}

// ClearField clears the value of the field with the given name. It returns an
// error if the field is not defined in the schema.
func (m *GenerationTaskMutation) ClearField(name string) error {
	return fmt.Errorf("unknown GenerationTask nullable field %s", name)
}

// ResetField resets all changes in the mutation for the field with the given name.
// It returns an error if the field is not defined in the schema.
func (m *GenerationTaskMutation) ResetField(name string) error {
	switch name {
	case generationtask.FieldCaller:
		m.ResetCaller()
		return nil
	case generationtask.FieldRequestID:
		m.ResetRequestID()
		return nil
	case generationtask.FieldRequestHash:
		m.ResetRequestHash()
		return nil
	case generationtask.FieldModel:
		m.ResetModel()
		return nil
	case generationtask.FieldProvider:
		m.ResetProvider()
		return nil
	case generationtask.FieldProviderTaskID:
		m.ResetProviderTaskID()
		return nil
	case generationtask.FieldState:
		m.ResetState()
		return nil
	case generationtask.FieldErrorCode:
		m.ResetErrorCode()
		return nil
	case generationtask.FieldErrorMessage:
		m.ResetErrorMessage()
		return nil
	case generationtask.FieldErrorReason:
		m.ResetErrorReason()
		return nil
	case generationtask.FieldCreatedAt:
		m.ResetCreatedAt()
		return nil
	case generationtask.FieldUpdatedAt:
		m.ResetUpdatedAt()
		return nil
	}
	return fmt.Errorf("unknown GenerationTask field %s", name)
}

// AddedEdges returns all edge names that were set/added in this mutation.
func (m *GenerationTaskMutation) AddedEdges() []string {
	edges := make([]string, 0, 0)
	return edges
}

// AddedIDs returns all IDs (to other nodes) that were added for the given edge
// name in this mutation.
func (m *GenerationTaskMutation) AddedIDs(name string) []ent.Value {
	return nil
}

// RemovedEdges returns all edge names that were removed in this mutation.
func (m *GenerationTaskMutation) RemovedEdges() []string {
	edges := make([]string, 0, 0)
	return edges
}

// RemovedIDs returns all IDs (to other nodes) that were removed for the edge with
// the given name in this mutation.
func (m *GenerationTaskMutation) RemovedIDs(name string) []ent.Value {
	return nil
}

// ClearedEdges returns all edge names that were cleared in this mutation.
func (m *GenerationTaskMutation) ClearedEdges() []string {
	edges := make([]string, 0, 0)
	return edges
}

// EdgeCleared returns a boolean which indicates if the edge with the given name
// was cleared in this mutation.
func (m *GenerationTaskMutation) EdgeCleared(name string) bool {
	return false
}

// ClearEdge clears the value of the edge with the given name. It returns an error
// if that edge is not defined in the schema.
func (m *GenerationTaskMutation) ClearEdge(name string) error {
	return fmt.Errorf("unknown GenerationTask unique edge %s", name)
}

// ResetEdge resets all changes to the edge with the given name in this mutation.
// It returns an error if the edge is not defined in the schema.
func (m *GenerationTaskMutation) ResetEdge(name string) error {
	return fmt.Errorf("unknown GenerationTask edge %s", name)
}

// ModelhubAPIKeyMutation represents an operation that mutates the ModelhubAPIKey nodes in the graph.
type ModelhubAPIKeyMutation struct {
	config
	op            Op
	typ           string
	id            *string
	principal_id  *string
	key_id        *string
	secret_sha256 *string
	name          *string
	created_by    *string
	created_at    *time.Time
	expires_at    *time.Time
	revoked_at    *time.Time
	clearedFields map[string]struct{}
	done          bool
	oldValue      func(context.Context) (*ModelhubAPIKey, error)
	predicates    []predicate.ModelhubAPIKey
}

var _ ent.Mutation = (*ModelhubAPIKeyMutation)(nil)

// modelhubapikeyOption allows management of the mutation configuration using functional options.
type modelhubapikeyOption func(*ModelhubAPIKeyMutation)

// newModelhubAPIKeyMutation creates new mutation for the ModelhubAPIKey entity.
func newModelhubAPIKeyMutation(c config, op Op, opts ...modelhubapikeyOption) *ModelhubAPIKeyMutation {
	m := &ModelhubAPIKeyMutation{
		config:        c,
		op:            op,
		typ:           TypeModelhubAPIKey,
		clearedFields: make(map[string]struct{}),
	}
	for _, opt := range opts {
		opt(m)
	}
	return m
}

// withModelhubAPIKeyID sets the ID field of the mutation.
func withModelhubAPIKeyID(id string) modelhubapikeyOption {
	return func(m *ModelhubAPIKeyMutation) {
		var (
			err   error
			once  sync.Once
			value *ModelhubAPIKey
		)
		m.oldValue = func(ctx context.Context) (*ModelhubAPIKey, error) {
			once.Do(func() {
				if m.done {
					err = errors.New("querying old values post mutation is not allowed")
				} else {
					value, err = m.Client().ModelhubAPIKey.Get(ctx, id)
				}
			})
			return value, err
		}
		m.id = &id
	}
}

// withModelhubAPIKey sets the old ModelhubAPIKey of the mutation.
func withModelhubAPIKey(node *ModelhubAPIKey) modelhubapikeyOption {
	return func(m *ModelhubAPIKeyMutation) {
		m.oldValue = func(context.Context) (*ModelhubAPIKey, error) {
			return node, nil
		}
		m.id = &node.ID
	}
}

// Client returns a new `ent.Client` from the mutation. If the mutation was
// executed in a transaction (ent.Tx), a transactional client is returned.
func (m ModelhubAPIKeyMutation) Client() *Client {
	client := &Client{config: m.config}
	client.init()
	return client
}

// Tx returns an `ent.Tx` for mutations that were executed in transactions;
// it returns an error otherwise.
func (m ModelhubAPIKeyMutation) Tx() (*Tx, error) {
	if _, ok := m.driver.(*txDriver); !ok {
		return nil, errors.New("ent: mutation is not running in a transaction")
	}
	tx := &Tx{config: m.config}
	tx.init()
	return tx, nil
}

// SetID sets the value of the id field. Note that this
// operation is only accepted on creation of ModelhubAPIKey entities.
func (m *ModelhubAPIKeyMutation) SetID(id string) {
	m.id = &id
}

// ID returns the ID value in the mutation. Note that the ID is only available
// if it was provided to the builder or after it was returned from the database.
func (m *ModelhubAPIKeyMutation) ID() (id string, exists bool) {
	if m.id == nil {
		return
	}
	return *m.id, true
}

// IDs queries the database and returns the entity ids that match the mutation's predicate.
// That means, if the mutation is applied within a transaction with an isolation level such
// as sql.LevelSerializable, the returned ids match the ids of the rows that will be updated
// or updated by the mutation.
func (m *ModelhubAPIKeyMutation) IDs(ctx context.Context) ([]string, error) {
	switch {
	case m.op.Is(OpUpdateOne | OpDeleteOne):
		id, exists := m.ID()
		if exists {
			return []string{id}, nil
		}
		fallthrough
	case m.op.Is(OpUpdate | OpDelete):
		return m.Client().ModelhubAPIKey.Query().Where(m.predicates...).IDs(ctx)
	default:
		return nil, fmt.Errorf("IDs is not allowed on %s operations", m.op)
	}
}

// SetPrincipalID sets the "principal_id" field.
func (m *ModelhubAPIKeyMutation) SetPrincipalID(s string) {
	m.principal_id = &s
}

// PrincipalID returns the value of the "principal_id" field in the mutation.
func (m *ModelhubAPIKeyMutation) PrincipalID() (r string, exists bool) {
	v := m.principal_id
	if v == nil {
		return
	}
	return *v, true
}

// OldPrincipalID returns the old "principal_id" field's value of the ModelhubAPIKey entity.
// If the ModelhubAPIKey object wasn't provided to the builder, the object is fetched from the database.
// An error is returned if the mutation operation is not UpdateOne, or the database query fails.
func (m *ModelhubAPIKeyMutation) OldPrincipalID(ctx context.Context) (v string, err error) {
	if !m.op.Is(OpUpdateOne) {
		return v, errors.New("OldPrincipalID is only allowed on UpdateOne operations")
	}
	if m.id == nil || m.oldValue == nil {
		return v, errors.New("OldPrincipalID requires an ID field in the mutation")
	}
	oldValue, err := m.oldValue(ctx)
	if err != nil {
		return v, fmt.Errorf("querying old value for OldPrincipalID: %w", err)
	}
	return oldValue.PrincipalID, nil
}

// ResetPrincipalID resets all changes to the "principal_id" field.
func (m *ModelhubAPIKeyMutation) ResetPrincipalID() {
	m.principal_id = nil
}

// SetKeyID sets the "key_id" field.
func (m *ModelhubAPIKeyMutation) SetKeyID(s string) {
	m.key_id = &s
}

// KeyID returns the value of the "key_id" field in the mutation.
func (m *ModelhubAPIKeyMutation) KeyID() (r string, exists bool) {
	v := m.key_id
	if v == nil {
		return
	}
	return *v, true
}

// OldKeyID returns the old "key_id" field's value of the ModelhubAPIKey entity.
// If the ModelhubAPIKey object wasn't provided to the builder, the object is fetched from the database.
// An error is returned if the mutation operation is not UpdateOne, or the database query fails.
func (m *ModelhubAPIKeyMutation) OldKeyID(ctx context.Context) (v string, err error) {
	if !m.op.Is(OpUpdateOne) {
		return v, errors.New("OldKeyID is only allowed on UpdateOne operations")
	}
	if m.id == nil || m.oldValue == nil {
		return v, errors.New("OldKeyID requires an ID field in the mutation")
	}
	oldValue, err := m.oldValue(ctx)
	if err != nil {
		return v, fmt.Errorf("querying old value for OldKeyID: %w", err)
	}
	return oldValue.KeyID, nil
}

// ResetKeyID resets all changes to the "key_id" field.
func (m *ModelhubAPIKeyMutation) ResetKeyID() {
	m.key_id = nil
}

// SetSecretSha256 sets the "secret_sha256" field.
func (m *ModelhubAPIKeyMutation) SetSecretSha256(s string) {
	m.secret_sha256 = &s
}

// SecretSha256 returns the value of the "secret_sha256" field in the mutation.
func (m *ModelhubAPIKeyMutation) SecretSha256() (r string, exists bool) {
	v := m.secret_sha256
	if v == nil {
		return
	}
	return *v, true
}

// OldSecretSha256 returns the old "secret_sha256" field's value of the ModelhubAPIKey entity.
// If the ModelhubAPIKey object wasn't provided to the builder, the object is fetched from the database.
// An error is returned if the mutation operation is not UpdateOne, or the database query fails.
func (m *ModelhubAPIKeyMutation) OldSecretSha256(ctx context.Context) (v string, err error) {
	if !m.op.Is(OpUpdateOne) {
		return v, errors.New("OldSecretSha256 is only allowed on UpdateOne operations")
	}
	if m.id == nil || m.oldValue == nil {
		return v, errors.New("OldSecretSha256 requires an ID field in the mutation")
	}
	oldValue, err := m.oldValue(ctx)
	if err != nil {
		return v, fmt.Errorf("querying old value for OldSecretSha256: %w", err)
	}
	return oldValue.SecretSha256, nil
}

// ResetSecretSha256 resets all changes to the "secret_sha256" field.
func (m *ModelhubAPIKeyMutation) ResetSecretSha256() {
	m.secret_sha256 = nil
}

// SetName sets the "name" field.
func (m *ModelhubAPIKeyMutation) SetName(s string) {
	m.name = &s
}

// Name returns the value of the "name" field in the mutation.
func (m *ModelhubAPIKeyMutation) Name() (r string, exists bool) {
	v := m.name
	if v == nil {
		return
	}
	return *v, true
}

// OldName returns the old "name" field's value of the ModelhubAPIKey entity.
// If the ModelhubAPIKey object wasn't provided to the builder, the object is fetched from the database.
// An error is returned if the mutation operation is not UpdateOne, or the database query fails.
func (m *ModelhubAPIKeyMutation) OldName(ctx context.Context) (v string, err error) {
	if !m.op.Is(OpUpdateOne) {
		return v, errors.New("OldName is only allowed on UpdateOne operations")
	}
	if m.id == nil || m.oldValue == nil {
		return v, errors.New("OldName requires an ID field in the mutation")
	}
	oldValue, err := m.oldValue(ctx)
	if err != nil {
		return v, fmt.Errorf("querying old value for OldName: %w", err)
	}
	return oldValue.Name, nil
}

// ResetName resets all changes to the "name" field.
func (m *ModelhubAPIKeyMutation) ResetName() {
	m.name = nil
}

// SetCreatedBy sets the "created_by" field.
func (m *ModelhubAPIKeyMutation) SetCreatedBy(s string) {
	m.created_by = &s
}

// CreatedBy returns the value of the "created_by" field in the mutation.
func (m *ModelhubAPIKeyMutation) CreatedBy() (r string, exists bool) {
	v := m.created_by
	if v == nil {
		return
	}
	return *v, true
}

// OldCreatedBy returns the old "created_by" field's value of the ModelhubAPIKey entity.
// If the ModelhubAPIKey object wasn't provided to the builder, the object is fetched from the database.
// An error is returned if the mutation operation is not UpdateOne, or the database query fails.
func (m *ModelhubAPIKeyMutation) OldCreatedBy(ctx context.Context) (v string, err error) {
	if !m.op.Is(OpUpdateOne) {
		return v, errors.New("OldCreatedBy is only allowed on UpdateOne operations")
	}
	if m.id == nil || m.oldValue == nil {
		return v, errors.New("OldCreatedBy requires an ID field in the mutation")
	}
	oldValue, err := m.oldValue(ctx)
	if err != nil {
		return v, fmt.Errorf("querying old value for OldCreatedBy: %w", err)
	}
	return oldValue.CreatedBy, nil
}

// ResetCreatedBy resets all changes to the "created_by" field.
func (m *ModelhubAPIKeyMutation) ResetCreatedBy() {
	m.created_by = nil
}

// SetCreatedAt sets the "created_at" field.
func (m *ModelhubAPIKeyMutation) SetCreatedAt(t time.Time) {
	m.created_at = &t
}

// CreatedAt returns the value of the "created_at" field in the mutation.
func (m *ModelhubAPIKeyMutation) CreatedAt() (r time.Time, exists bool) {
	v := m.created_at
	if v == nil {
		return
	}
	return *v, true
}

// OldCreatedAt returns the old "created_at" field's value of the ModelhubAPIKey entity.
// If the ModelhubAPIKey object wasn't provided to the builder, the object is fetched from the database.
// An error is returned if the mutation operation is not UpdateOne, or the database query fails.
func (m *ModelhubAPIKeyMutation) OldCreatedAt(ctx context.Context) (v time.Time, err error) {
	if !m.op.Is(OpUpdateOne) {
		return v, errors.New("OldCreatedAt is only allowed on UpdateOne operations")
	}
	if m.id == nil || m.oldValue == nil {
		return v, errors.New("OldCreatedAt requires an ID field in the mutation")
	}
	oldValue, err := m.oldValue(ctx)
	if err != nil {
		return v, fmt.Errorf("querying old value for OldCreatedAt: %w", err)
	}
	return oldValue.CreatedAt, nil
}

// ResetCreatedAt resets all changes to the "created_at" field.
func (m *ModelhubAPIKeyMutation) ResetCreatedAt() {
	m.created_at = nil
}

// SetExpiresAt sets the "expires_at" field.
func (m *ModelhubAPIKeyMutation) SetExpiresAt(t time.Time) {
	m.expires_at = &t
}

// ExpiresAt returns the value of the "expires_at" field in the mutation.
func (m *ModelhubAPIKeyMutation) ExpiresAt() (r time.Time, exists bool) {
	v := m.expires_at
	if v == nil {
		return
	}
	return *v, true
}

// OldExpiresAt returns the old "expires_at" field's value of the ModelhubAPIKey entity.
// If the ModelhubAPIKey object wasn't provided to the builder, the object is fetched from the database.
// An error is returned if the mutation operation is not UpdateOne, or the database query fails.
func (m *ModelhubAPIKeyMutation) OldExpiresAt(ctx context.Context) (v *time.Time, err error) {
	if !m.op.Is(OpUpdateOne) {
		return v, errors.New("OldExpiresAt is only allowed on UpdateOne operations")
	}
	if m.id == nil || m.oldValue == nil {
		return v, errors.New("OldExpiresAt requires an ID field in the mutation")
	}
	oldValue, err := m.oldValue(ctx)
	if err != nil {
		return v, fmt.Errorf("querying old value for OldExpiresAt: %w", err)
	}
	return oldValue.ExpiresAt, nil
}

// ClearExpiresAt clears the value of the "expires_at" field.
func (m *ModelhubAPIKeyMutation) ClearExpiresAt() {
	m.expires_at = nil
	m.clearedFields[modelhubapikey.FieldExpiresAt] = struct{}{}
}

// ExpiresAtCleared returns if the "expires_at" field was cleared in this mutation.
func (m *ModelhubAPIKeyMutation) ExpiresAtCleared() bool {
	_, ok := m.clearedFields[modelhubapikey.FieldExpiresAt]
	return ok
}

// ResetExpiresAt resets all changes to the "expires_at" field.
func (m *ModelhubAPIKeyMutation) ResetExpiresAt() {
	m.expires_at = nil
	delete(m.clearedFields, modelhubapikey.FieldExpiresAt)
}

// SetRevokedAt sets the "revoked_at" field.
func (m *ModelhubAPIKeyMutation) SetRevokedAt(t time.Time) {
	m.revoked_at = &t
}

// RevokedAt returns the value of the "revoked_at" field in the mutation.
func (m *ModelhubAPIKeyMutation) RevokedAt() (r time.Time, exists bool) {
	v := m.revoked_at
	if v == nil {
		return
	}
	return *v, true
}

// OldRevokedAt returns the old "revoked_at" field's value of the ModelhubAPIKey entity.
// If the ModelhubAPIKey object wasn't provided to the builder, the object is fetched from the database.
// An error is returned if the mutation operation is not UpdateOne, or the database query fails.
func (m *ModelhubAPIKeyMutation) OldRevokedAt(ctx context.Context) (v *time.Time, err error) {
	if !m.op.Is(OpUpdateOne) {
		return v, errors.New("OldRevokedAt is only allowed on UpdateOne operations")
	}
	if m.id == nil || m.oldValue == nil {
		return v, errors.New("OldRevokedAt requires an ID field in the mutation")
	}
	oldValue, err := m.oldValue(ctx)
	if err != nil {
		return v, fmt.Errorf("querying old value for OldRevokedAt: %w", err)
	}
	return oldValue.RevokedAt, nil
}

// ClearRevokedAt clears the value of the "revoked_at" field.
func (m *ModelhubAPIKeyMutation) ClearRevokedAt() {
	m.revoked_at = nil
	m.clearedFields[modelhubapikey.FieldRevokedAt] = struct{}{}
}

// RevokedAtCleared returns if the "revoked_at" field was cleared in this mutation.
func (m *ModelhubAPIKeyMutation) RevokedAtCleared() bool {
	_, ok := m.clearedFields[modelhubapikey.FieldRevokedAt]
	return ok
}

// ResetRevokedAt resets all changes to the "revoked_at" field.
func (m *ModelhubAPIKeyMutation) ResetRevokedAt() {
	m.revoked_at = nil
	delete(m.clearedFields, modelhubapikey.FieldRevokedAt)
}

// Where appends a list predicates to the ModelhubAPIKeyMutation builder.
func (m *ModelhubAPIKeyMutation) Where(ps ...predicate.ModelhubAPIKey) {
	m.predicates = append(m.predicates, ps...)
}

// WhereP appends storage-level predicates to the ModelhubAPIKeyMutation builder. Using this method,
// users can use type-assertion to append predicates that do not depend on any generated package.
func (m *ModelhubAPIKeyMutation) WhereP(ps ...func(*sql.Selector)) {
	p := make([]predicate.ModelhubAPIKey, len(ps))
	for i := range ps {
		p[i] = ps[i]
	}
	m.Where(p...)
}

// Op returns the operation name.
func (m *ModelhubAPIKeyMutation) Op() Op {
	return m.op
}

// SetOp allows setting the mutation operation.
func (m *ModelhubAPIKeyMutation) SetOp(op Op) {
	m.op = op
}

// Type returns the node type of this mutation (ModelhubAPIKey).
func (m *ModelhubAPIKeyMutation) Type() string {
	return m.typ
}

// Fields returns all fields that were changed during this mutation. Note that in
// order to get all numeric fields that were incremented/decremented, call
// AddedFields().
func (m *ModelhubAPIKeyMutation) Fields() []string {
	fields := make([]string, 0, 8)
	if m.principal_id != nil {
		fields = append(fields, modelhubapikey.FieldPrincipalID)
	}
	if m.key_id != nil {
		fields = append(fields, modelhubapikey.FieldKeyID)
	}
	if m.secret_sha256 != nil {
		fields = append(fields, modelhubapikey.FieldSecretSha256)
	}
	if m.name != nil {
		fields = append(fields, modelhubapikey.FieldName)
	}
	if m.created_by != nil {
		fields = append(fields, modelhubapikey.FieldCreatedBy)
	}
	if m.created_at != nil {
		fields = append(fields, modelhubapikey.FieldCreatedAt)
	}
	if m.expires_at != nil {
		fields = append(fields, modelhubapikey.FieldExpiresAt)
	}
	if m.revoked_at != nil {
		fields = append(fields, modelhubapikey.FieldRevokedAt)
	}
	return fields
}

// Field returns the value of a field with the given name. The second boolean
// return value indicates that this field was not set, or was not defined in the
// schema.
func (m *ModelhubAPIKeyMutation) Field(name string) (ent.Value, bool) {
	switch name {
	case modelhubapikey.FieldPrincipalID:
		return m.PrincipalID()
	case modelhubapikey.FieldKeyID:
		return m.KeyID()
	case modelhubapikey.FieldSecretSha256:
		return m.SecretSha256()
	case modelhubapikey.FieldName:
		return m.Name()
	case modelhubapikey.FieldCreatedBy:
		return m.CreatedBy()
	case modelhubapikey.FieldCreatedAt:
		return m.CreatedAt()
	case modelhubapikey.FieldExpiresAt:
		return m.ExpiresAt()
	case modelhubapikey.FieldRevokedAt:
		return m.RevokedAt()
	}
	return nil, false
}

// OldField returns the old value of the field from the database. An error is
// returned if the mutation operation is not UpdateOne, or the query to the
// database failed.
func (m *ModelhubAPIKeyMutation) OldField(ctx context.Context, name string) (ent.Value, error) {
	switch name {
	case modelhubapikey.FieldPrincipalID:
		return m.OldPrincipalID(ctx)
	case modelhubapikey.FieldKeyID:
		return m.OldKeyID(ctx)
	case modelhubapikey.FieldSecretSha256:
		return m.OldSecretSha256(ctx)
	case modelhubapikey.FieldName:
		return m.OldName(ctx)
	case modelhubapikey.FieldCreatedBy:
		return m.OldCreatedBy(ctx)
	case modelhubapikey.FieldCreatedAt:
		return m.OldCreatedAt(ctx)
	case modelhubapikey.FieldExpiresAt:
		return m.OldExpiresAt(ctx)
	case modelhubapikey.FieldRevokedAt:
		return m.OldRevokedAt(ctx)
	}
	return nil, fmt.Errorf("unknown ModelhubAPIKey field %s", name)
}

// SetField sets the value of a field with the given name. It returns an error if
// the field is not defined in the schema, or if the type mismatched the field
// type.
func (m *ModelhubAPIKeyMutation) SetField(name string, value ent.Value) error {
	switch name {
	case modelhubapikey.FieldPrincipalID:
		v, ok := value.(string)
		if !ok {
			return fmt.Errorf("unexpected type %T for field %s", value, name)
		}
		m.SetPrincipalID(v)
		return nil
	case modelhubapikey.FieldKeyID:
		v, ok := value.(string)
		if !ok {
			return fmt.Errorf("unexpected type %T for field %s", value, name)
		}
		m.SetKeyID(v)
		return nil
	case modelhubapikey.FieldSecretSha256:
		v, ok := value.(string)
		if !ok {
			return fmt.Errorf("unexpected type %T for field %s", value, name)
		}
		m.SetSecretSha256(v)
		return nil
	case modelhubapikey.FieldName:
		v, ok := value.(string)
		if !ok {
			return fmt.Errorf("unexpected type %T for field %s", value, name)
		}
		m.SetName(v)
		return nil
	case modelhubapikey.FieldCreatedBy:
		v, ok := value.(string)
		if !ok {
			return fmt.Errorf("unexpected type %T for field %s", value, name)
		}
		m.SetCreatedBy(v)
		return nil
	case modelhubapikey.FieldCreatedAt:
		v, ok := value.(time.Time)
		if !ok {
			return fmt.Errorf("unexpected type %T for field %s", value, name)
		}
		m.SetCreatedAt(v)
		return nil
	case modelhubapikey.FieldExpiresAt:
		v, ok := value.(time.Time)
		if !ok {
			return fmt.Errorf("unexpected type %T for field %s", value, name)
		}
		m.SetExpiresAt(v)
		return nil
	case modelhubapikey.FieldRevokedAt:
		v, ok := value.(time.Time)
		if !ok {
			return fmt.Errorf("unexpected type %T for field %s", value, name)
		}
		m.SetRevokedAt(v)
		return nil
	}
	return fmt.Errorf("unknown ModelhubAPIKey field %s", name)
}

// AddedFields returns all numeric fields that were incremented/decremented during
// this mutation.
func (m *ModelhubAPIKeyMutation) AddedFields() []string {
	return nil
}

// AddedField returns the numeric value that was incremented/decremented on a field
// with the given name. The second boolean return value indicates that this field
// was not set, or was not defined in the schema.
func (m *ModelhubAPIKeyMutation) AddedField(name string) (ent.Value, bool) {
	return nil, false
}

// AddField adds the value to the field with the given name. It returns an error if
// the field is not defined in the schema, or if the type mismatched the field
// type.
func (m *ModelhubAPIKeyMutation) AddField(name string, value ent.Value) error {
	switch name {
	}
	return fmt.Errorf("unknown ModelhubAPIKey numeric field %s", name)
}

// ClearedFields returns all nullable fields that were cleared during this
// mutation.
func (m *ModelhubAPIKeyMutation) ClearedFields() []string {
	var fields []string
	if m.FieldCleared(modelhubapikey.FieldExpiresAt) {
		fields = append(fields, modelhubapikey.FieldExpiresAt)
	}
	if m.FieldCleared(modelhubapikey.FieldRevokedAt) {
		fields = append(fields, modelhubapikey.FieldRevokedAt)
	}
	return fields
}

// FieldCleared returns a boolean indicating if a field with the given name was
// cleared in this mutation.
func (m *ModelhubAPIKeyMutation) FieldCleared(name string) bool {
	_, ok := m.clearedFields[name]
	return ok
}

// ClearField clears the value of the field with the given name. It returns an
// error if the field is not defined in the schema.
func (m *ModelhubAPIKeyMutation) ClearField(name string) error {
	switch name {
	case modelhubapikey.FieldExpiresAt:
		m.ClearExpiresAt()
		return nil
	case modelhubapikey.FieldRevokedAt:
		m.ClearRevokedAt()
		return nil
	}
	return fmt.Errorf("unknown ModelhubAPIKey nullable field %s", name)
}

// ResetField resets all changes in the mutation for the field with the given name.
// It returns an error if the field is not defined in the schema.
func (m *ModelhubAPIKeyMutation) ResetField(name string) error {
	switch name {
	case modelhubapikey.FieldPrincipalID:
		m.ResetPrincipalID()
		return nil
	case modelhubapikey.FieldKeyID:
		m.ResetKeyID()
		return nil
	case modelhubapikey.FieldSecretSha256:
		m.ResetSecretSha256()
		return nil
	case modelhubapikey.FieldName:
		m.ResetName()
		return nil
	case modelhubapikey.FieldCreatedBy:
		m.ResetCreatedBy()
		return nil
	case modelhubapikey.FieldCreatedAt:
		m.ResetCreatedAt()
		return nil
	case modelhubapikey.FieldExpiresAt:
		m.ResetExpiresAt()
		return nil
	case modelhubapikey.FieldRevokedAt:
		m.ResetRevokedAt()
		return nil
	}
	return fmt.Errorf("unknown ModelhubAPIKey field %s", name)
}

// AddedEdges returns all edge names that were set/added in this mutation.
func (m *ModelhubAPIKeyMutation) AddedEdges() []string {
	edges := make([]string, 0, 0)
	return edges
}

// AddedIDs returns all IDs (to other nodes) that were added for the given edge
// name in this mutation.
func (m *ModelhubAPIKeyMutation) AddedIDs(name string) []ent.Value {
	return nil
}

// RemovedEdges returns all edge names that were removed in this mutation.
func (m *ModelhubAPIKeyMutation) RemovedEdges() []string {
	edges := make([]string, 0, 0)
	return edges
}

// RemovedIDs returns all IDs (to other nodes) that were removed for the edge with
// the given name in this mutation.
func (m *ModelhubAPIKeyMutation) RemovedIDs(name string) []ent.Value {
	return nil
}

// ClearedEdges returns all edge names that were cleared in this mutation.
func (m *ModelhubAPIKeyMutation) ClearedEdges() []string {
	edges := make([]string, 0, 0)
	return edges
}

// EdgeCleared returns a boolean which indicates if the edge with the given name
// was cleared in this mutation.
func (m *ModelhubAPIKeyMutation) EdgeCleared(name string) bool {
	return false
}

// ClearEdge clears the value of the edge with the given name. It returns an error
// if that edge is not defined in the schema.
func (m *ModelhubAPIKeyMutation) ClearEdge(name string) error {
	return fmt.Errorf("unknown ModelhubAPIKey unique edge %s", name)
}

// ResetEdge resets all changes to the edge with the given name in this mutation.
// It returns an error if the edge is not defined in the schema.
func (m *ModelhubAPIKeyMutation) ResetEdge(name string) error {
	return fmt.Errorf("unknown ModelhubAPIKey edge %s", name)
}
