// Code generated by ent, DO NOT EDIT.

package ent

import (
	"time"

	"github.com/wgdl666/wgModelHub/ent/generationtask"
	"github.com/wgdl666/wgModelHub/ent/modelcall"
	"github.com/wgdl666/wgModelHub/ent/modelhubapikey"
	"github.com/wgdl666/wgModelHub/ent/schema"
)

// The init function reads all schema descriptors with runtime code
// (default values, validators, hooks and policies) and stitches it
// to their package variables.
func init() {
	generationtaskFields := schema.GenerationTask{}.Fields()
	_ = generationtaskFields
	// generationtaskDescProviderTaskID is the schema descriptor for provider_task_id field.
	generationtaskDescProviderTaskID := generationtaskFields[6].Descriptor()
	// generationtask.DefaultProviderTaskID holds the default value on creation for the provider_task_id field.
	generationtask.DefaultProviderTaskID = generationtaskDescProviderTaskID.Default.(string)
	// generationtaskDescErrorCode is the schema descriptor for error_code field.
	generationtaskDescErrorCode := generationtaskFields[8].Descriptor()
	// generationtask.DefaultErrorCode holds the default value on creation for the error_code field.
	generationtask.DefaultErrorCode = generationtaskDescErrorCode.Default.(int32)
	// generationtaskDescErrorMessage is the schema descriptor for error_message field.
	generationtaskDescErrorMessage := generationtaskFields[9].Descriptor()
	// generationtask.DefaultErrorMessage holds the default value on creation for the error_message field.
	generationtask.DefaultErrorMessage = generationtaskDescErrorMessage.Default.(string)
	// generationtaskDescErrorReason is the schema descriptor for error_reason field.
	generationtaskDescErrorReason := generationtaskFields[10].Descriptor()
	// generationtask.DefaultErrorReason holds the default value on creation for the error_reason field.
	generationtask.DefaultErrorReason = generationtaskDescErrorReason.Default.(string)
	// generationtaskDescCreatedAt is the schema descriptor for created_at field.
	generationtaskDescCreatedAt := generationtaskFields[11].Descriptor()
	// generationtask.DefaultCreatedAt holds the default value on creation for the created_at field.
	generationtask.DefaultCreatedAt = generationtaskDescCreatedAt.Default.(func() time.Time)
	// generationtaskDescUpdatedAt is the schema descriptor for updated_at field.
	generationtaskDescUpdatedAt := generationtaskFields[12].Descriptor()
	// generationtask.DefaultUpdatedAt holds the default value on creation for the updated_at field.
	generationtask.DefaultUpdatedAt = generationtaskDescUpdatedAt.Default.(func() time.Time)
	// generationtask.UpdateDefaultUpdatedAt holds the default value on update for the updated_at field.
	generationtask.UpdateDefaultUpdatedAt = generationtaskDescUpdatedAt.UpdateDefault.(func() time.Time)
	modelcallFields := schema.ModelCall{}.Fields()
	_ = modelcallFields
	// modelcallDescCallerService is the schema descriptor for caller_service field.
	modelcallDescCallerService := modelcallFields[2].Descriptor()
	// modelcall.DefaultCallerService holds the default value on creation for the caller_service field.
	modelcall.DefaultCallerService = modelcallDescCallerService.Default.(string)
	// modelcallDescBusinessScene is the schema descriptor for business_scene field.
	modelcallDescBusinessScene := modelcallFields[3].Descriptor()
	// modelcall.DefaultBusinessScene holds the default value on creation for the business_scene field.
	modelcall.DefaultBusinessScene = modelcallDescBusinessScene.Default.(string)
	// modelcallDescDeliveryStatus is the schema descriptor for delivery_status field.
	modelcallDescDeliveryStatus := modelcallFields[9].Descriptor()
	// modelcall.DefaultDeliveryStatus holds the default value on creation for the delivery_status field.
	modelcall.DefaultDeliveryStatus = modelcallDescDeliveryStatus.Default.(string)
	// modelcallDescErrorCategory is the schema descriptor for error_category field.
	modelcallDescErrorCategory := modelcallFields[10].Descriptor()
	// modelcall.DefaultErrorCategory holds the default value on creation for the error_category field.
	modelcall.DefaultErrorCategory = modelcallDescErrorCategory.Default.(string)
	// modelcallDescErrorCode is the schema descriptor for error_code field.
	modelcallDescErrorCode := modelcallFields[11].Descriptor()
	// modelcall.DefaultErrorCode holds the default value on creation for the error_code field.
	modelcall.DefaultErrorCode = modelcallDescErrorCode.Default.(string)
	// modelcallDescErrorReason is the schema descriptor for error_reason field.
	modelcallDescErrorReason := modelcallFields[12].Descriptor()
	// modelcall.DefaultErrorReason holds the default value on creation for the error_reason field.
	modelcall.DefaultErrorReason = modelcallDescErrorReason.Default.(string)
	// modelcallDescErrorMessage is the schema descriptor for error_message field.
	modelcallDescErrorMessage := modelcallFields[13].Descriptor()
	// modelcall.DefaultErrorMessage holds the default value on creation for the error_message field.
	modelcall.DefaultErrorMessage = modelcallDescErrorMessage.Default.(string)
	// modelcallDescImageSize is the schema descriptor for image_size field.
	modelcallDescImageSize := modelcallFields[20].Descriptor()
	// modelcall.DefaultImageSize holds the default value on creation for the image_size field.
	modelcall.DefaultImageSize = modelcallDescImageSize.Default.(string)
	// modelcallDescImageAspectRatio is the schema descriptor for image_aspect_ratio field.
	modelcallDescImageAspectRatio := modelcallFields[21].Descriptor()
	// modelcall.DefaultImageAspectRatio holds the default value on creation for the image_aspect_ratio field.
	modelcall.DefaultImageAspectRatio = modelcallDescImageAspectRatio.Default.(string)
	// modelcallDescVideoResolution is the schema descriptor for video_resolution field.
	modelcallDescVideoResolution := modelcallFields[23].Descriptor()
	// modelcall.DefaultVideoResolution holds the default value on creation for the video_resolution field.
	modelcall.DefaultVideoResolution = modelcallDescVideoResolution.Default.(string)
	// modelcallDescVideoAspectRatio is the schema descriptor for video_aspect_ratio field.
	modelcallDescVideoAspectRatio := modelcallFields[25].Descriptor()
	// modelcall.DefaultVideoAspectRatio holds the default value on creation for the video_aspect_ratio field.
	modelcall.DefaultVideoAspectRatio = modelcallDescVideoAspectRatio.Default.(string)
	// modelcallDescLatencyMs is the schema descriptor for latency_ms field.
	modelcallDescLatencyMs := modelcallFields[26].Descriptor()
	// modelcall.DefaultLatencyMs holds the default value on creation for the latency_ms field.
	modelcall.DefaultLatencyMs = modelcallDescLatencyMs.Default.(int64)
	// modelcallDescInputPayload is the schema descriptor for input_payload field.
	modelcallDescInputPayload := modelcallFields[29].Descriptor()
	// modelcall.DefaultInputPayload holds the default value on creation for the input_payload field.
	modelcall.DefaultInputPayload = modelcallDescInputPayload.Default.(map[string]interface{})
	// modelcallDescOutputPayload is the schema descriptor for output_payload field.
	modelcallDescOutputPayload := modelcallFields[30].Descriptor()
	// modelcall.DefaultOutputPayload holds the default value on creation for the output_payload field.
	modelcall.DefaultOutputPayload = modelcallDescOutputPayload.Default.(map[string]interface{})
	// modelcallDescUsageDetail is the schema descriptor for usage_detail field.
	modelcallDescUsageDetail := modelcallFields[31].Descriptor()
	// modelcall.DefaultUsageDetail holds the default value on creation for the usage_detail field.
	modelcall.DefaultUsageDetail = modelcallDescUsageDetail.Default.(map[string]interface{})
	// modelcallDescCreatedAt is the schema descriptor for created_at field.
	modelcallDescCreatedAt := modelcallFields[32].Descriptor()
	// modelcall.DefaultCreatedAt holds the default value on creation for the created_at field.
	modelcall.DefaultCreatedAt = modelcallDescCreatedAt.Default.(func() time.Time)
	// modelcallDescUpdatedAt is the schema descriptor for updated_at field.
	modelcallDescUpdatedAt := modelcallFields[33].Descriptor()
	// modelcall.DefaultUpdatedAt holds the default value on creation for the updated_at field.
	modelcall.DefaultUpdatedAt = modelcallDescUpdatedAt.Default.(func() time.Time)
	// modelcall.UpdateDefaultUpdatedAt holds the default value on update for the updated_at field.
	modelcall.UpdateDefaultUpdatedAt = modelcallDescUpdatedAt.UpdateDefault.(func() time.Time)
	modelhubapikeyFields := schema.ModelhubAPIKey{}.Fields()
	_ = modelhubapikeyFields
	// modelhubapikeyDescName is the schema descriptor for name field.
	modelhubapikeyDescName := modelhubapikeyFields[4].Descriptor()
	// modelhubapikey.DefaultName holds the default value on creation for the name field.
	modelhubapikey.DefaultName = modelhubapikeyDescName.Default.(string)
	// modelhubapikeyDescCreatedAt is the schema descriptor for created_at field.
	modelhubapikeyDescCreatedAt := modelhubapikeyFields[6].Descriptor()
	// modelhubapikey.DefaultCreatedAt holds the default value on creation for the created_at field.
	modelhubapikey.DefaultCreatedAt = modelhubapikeyDescCreatedAt.Default.(func() time.Time)
}
