// Code generated by ent, DO NOT EDIT.

package predicate

import (
	"entgo.io/ent/dialect/sql"
)

// GenerationTask is the predicate function for generationtask builders.
type GenerationTask func(*sql.Selector)
